/-
Copyright (c) 2025 Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Winter
-/

import Mathlib.Geometry.Convex.Cone.Pointed
import Mathlib.RingTheory.LocalRing.Basic

import Polyhedral.Mathlib.Algebra.Module.Submodule.Basic

/-! This file proces basic facts about cones that are intended to go into
Pointed/Basic. -/

namespace PointedCone

section CommSemiring

variable {R : Type*} [CommSemiring R] [PartialOrder R] [IsOrderedRing R]

local notation "R≥0" => {c : R // 0 ≤ c}

instance : Algebra R≥0 R where
  algebraMap := Nonneg.coeRingHom
  commutes' r x := mul_comm ..
  smul_def' r x := by aesop

example : CommSemiring R≥0 := inferInstance

end CommSemiring

section Semiring

open Module Function
open Submodule (span)

variable {R M : Type*} [Semiring R] [PartialOrder R] [IsOrderedRing R] [AddCommMonoid M]
  [Module R M] {S : Set M}

-- allows us to use dot notation for lemmas in Submodule.FG or PointedCone.FG
abbrev FG (C : PointedCone R M) : Prop := Submodule.FG C

-- ## COE

lemma coe_inf (S T : Submodule R M) : S ⊓ T = (S ⊓ T : PointedCone R M)
    := Submodule.restrictScalars_inf _ _ _

lemma sInf_coe (s : Set (Submodule R M)) : sInf s = sInf (ofSubmodule '' s) :=
  Submodule.restrictScalars_sInf _ _

lemma iInf_coe (s : Set (Submodule R M)) : ⨅ S ∈ s, S = ⨅ S ∈ s, (S : PointedCone R M) := by
  rw [← sInf_eq_iInf, sInf_coe, sInf_eq_iInf, iInf_image]

lemma coe_sup (S T : Submodule R M) : S ⊔ T = (S ⊔ T : PointedCone R M)
    := Submodule.restrictScalars_sup _ _ _

lemma sSup_coe (s : Set (Submodule R M)) : sSup s = sSup (ofSubmodule '' s) :=
  Submodule.restrictScalars_sSup _ _

lemma iSup_coe (s : Set (Submodule R M)) : ⨆ S ∈ s, S = ⨆ S ∈ s, (S : PointedCone R M) := by
  rw [← sSup_eq_iSup, sSup_coe, sSup_eq_iSup, iSup_image]

-- ## HULL

/- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
/-- Notation for the ray generated by a point `x`, short for `PointedCone.hull R {x}`. -/
notation:70 R:70 " ∙₊ " x:70 => hull R (singleton x)

/-- Unexpander for `R ∙₊ x` notation. This needs to be defined separately because the `{_}`
notation is ambiguous, so we have to specify that it is the `«term{_}»` notation. -/
@[app_unexpander hull]
meta def hull.unexpander : Lean.PrettyPrinter.Unexpander
  | `($_ $R $s) => match s with
    | `(«term{_}»| {$a}) => `($R ∙₊ $a)
    | _ => throw ()
  | _ => throw ()

lemma hull_singleton_le_iff_mem {C : PointedCone R M} {x : M} : R ∙₊ x ≤ C ↔ x ∈ C :=
  Submodule.span_singleton_le_iff_mem x C

lemma hull_singleton_le {C : PointedCone R M} {x : M} (hx : x ∈ C) : R ∙₊ x ≤ C :=
  hull_singleton_le_iff_mem.mpr hx

lemma le_hull {s : Set M} : s ≤ hull R s := Submodule.subset_span

lemma hull_hull {s : Set M} : hull R (hull R s) = hull R s := Submodule.span_span

lemma hull_eq {S : PointedCone R M} : hull R S = S := Submodule.span_eq S

lemma hull_mono {s t : Set M} (h : s ⊆ t) : hull R s ≤ hull R t := Submodule.span_mono h

def hull_gi : GaloisInsertion (hull R : Set M → PointedCone R M) (↑) where
  choice s _ := hull R s
  gc _ _ := Submodule.span_le
  le_l_u _ := subset_hull
  choice_eq _ _ := rfl

@[simp] lemma span_hull_eq_submodule_span (s : Set M) :
    span R (hull R s) = span R s := Submodule.span_span_of_tower ..

-- TODO: this is only needed because `Submodule.span_insert` is restricted to rings
lemma hull_insert (x) (s : Set M) : hull R (insert x s) = hull R {x} ⊔ hull R s :=
  Submodule.span_insert x s

lemma coe_sup_submodule_span' {s t : Set M} :
    Submodule.span R (s ∪ t) = Submodule.span R (hull R s ⊔ hull R t) := by simp

-- Has this anything to do with cones? See version above
lemma coe_sup_submodule_span {C D : PointedCone R M} :
    Submodule.span R ((C : Set M) ∪ (D : Set M)) = Submodule.span R (C ⊔ D : PointedCone R M) := by
  rw [← span_hull_eq_submodule_span]
  simp [Submodule.span_union]

lemma hull_le_submodule_span (s : Set M) : hull R s ≤ Submodule.span R s :=
    Submodule.span_le_restrictScalars _ _ s

lemma le_span {C : PointedCone R M} : C ≤ span R (C : Set M) := Submodule.subset_span

lemma hull_union (s t : Set M) : hull R (s ∪ t) = hull R s ⊔ hull R t :=
  Submodule.span_union s t

lemma sup_eq_hull_union (C D : PointedCone R M) : C ⊔ D = hull R (C ∪ D) := by
  rw [← hull_eq (S := C), ← hull_eq (S := D), hull_union]
  simp

lemma sSup_eq_hull_iUnion (S : Set (PointedCone R M)) :
    sSup S = hull R (sSup (SetLike.coe '' S)) := by
  apply le_antisymm
  · refine sSup_le fun C hC _ hx => ?_
    have : (C : Set M) ∈ SetLike.coe '' S := ⟨C, hC, rfl⟩
    exact le_hull <| (le_sSup this) hx
  · refine Submodule.span_le.mpr fun x hx => ?_
    rw [Set.sSup_eq_sUnion] at hx
    obtain ⟨_, ⟨_, hC, rfl⟩, hx⟩ := hx
    exact (le_sSup hC) hx

end Semiring

section Ring

open Submodule (span)

variable {R : Type*} [Ring R] [PartialOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

-- TODO: write version with `restrictScalars` instead. (Or is there already one?)
lemma sup_inf_submodule_span_of_disjoint {C : PointedCone R M} {S : Submodule R M}
  (hS : Disjoint (span R C) S) : (C ⊔ S) ⊓ span R (C : Set M) = C := by
  rw [sup_inf_assoc_of_le_submodule]
  · rw [inf_comm, ← coe_inf, disjoint_iff.mp hS]; simp
  · exact Submodule.subset_span

end Ring

section AddCommGroup

variable {R : Type*} [Semiring R] [PartialOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

@[simps!]
def linealCone (C : PointedCone R M) : PointedCone R M where
  __ := C.support
  smul_mem' r _ hx := by
    by_cases hr : 0 ≤ r
    · simpa using And.intro (C.smul_mem hr hx.1) (C.smul_mem hr hx.2)
    · by_contra; exact hr r.2

end AddCommGroup

section Ring

section PartialOrder

variable {R : Type*} [Ring R] [PartialOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

section Pointwise

open Pointwise

@[simp] lemma neg_coe (S : Submodule R M) : -(S : PointedCone R M) = S := by ext x; simp

lemma map_id_eq_neg (C : PointedCone R M) : C.map (-.id) = -C := by
  ext x
  simp only [Submodule.mem_neg, mem_map, LinearMap.neg_apply, LinearMap.id_coe, id_eq]
  constructor
  · intro h
    obtain ⟨y, hyC, rfl⟩ := h
    simpa using hyC
  · exact fun h => by use -x; simp [h]

lemma comap_id_eq_neg (C : PointedCone R M) : C.comap (-.id) = -C := by
  ext x; simp

variable {N : Type*} [AddCommGroup N] [Module R N]

lemma map_neg (C : PointedCone R M) (f : M →ₗ[R] N) : map (-f) C = map f (-C) := by
  ext x
  simp only [mem_map, LinearMap.neg_apply, Submodule.mem_neg]
  constructor <;> {
    intro h
    obtain ⟨x, hx⟩ := h
    exact ⟨-x, by simpa using hx⟩
  }

lemma map_neg_apply (C : PointedCone R M) (f : M →ₗ[R] N) : - map f C = map f (-C) := by
  ext x
  simp only [Submodule.mem_neg, mem_map]
  constructor <;> {
    intro h
    obtain ⟨x, hx⟩ := h
    exact ⟨-x, by simpa [neg_eq_iff_eq_neg] using hx⟩
  }

lemma comap_neg (C : PointedCone R M) (f : N →ₗ[R] M) : comap (-f) C = comap f (-C) := by
  ext x; simp

lemma comap_neg_apply (C : PointedCone R M) (f : N →ₗ[R] M) : -comap f C = comap f (-C) := by
  ext x; simp

end Pointwise

end PartialOrder

section DirectedOrder

-- ## NEG INTERACTION

/- NOTE: there is already a mathlib PR (#36605) with a cleaner implementation of what is found
below. It will however take a while to be merged since it requires another PR (#42611).
-/

open Submodule (span)

variable {R : Type*} [Ring R] [PartialOrder R] [IsDirectedOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

-- lemma neg_self_iff_eq_span_submodule {C : PointedCone R M} (hC : -C = C) :
--     Submodule.span R (C : Set M) = C := by
--   suffices h : ∀ C, Submodule.span R (C : Set M) ≥ C from by
--     rw [le_antisymm_iff]
--     constructor
--     · rw [← Submodule.neg_le_neg]
--       sorry
--     · exact h C
--   intro C
--   exact Submodule.subset_span

-- lemma foo {α : Type} [InvolutiveNeg α] [SupSet α] (s : Set α) :
--     ⨆ a ∈ s ⊔ -s, a = ⨆ a ∈ α × FinSet 2,  := by sorry

-- lemma foo (s : Set (PointedCone R M)) :
--     ⨆ C ∈ s ⊔ -s, C = ⨆ C ∈ s, (C ⊔ -C) := by
--   simp
--   rw [le_antisymm_iff]
--   constructor
--   · intro h

--     sorry
--   · sorry

-- NOTE: I changed the statement of the lemma and added the `rw` to the first line that
--  transforms it into the previous statement. Maybe there is a shorter proof now?
-- TODO: simplify proof?
--
-- Mathematically, this lemma is equivalent to directedness of the order on `R`: for `M = R`
-- and `x = 1`, it says every element of `R` is a difference of two nonnegative elements.
variable (R) in
@[simp] lemma hull_neg_pair_eq_span_singleton (x : M) : hull R {-x, x} = R ∙ x := by
  rw [← Submodule.span_insert_eq_span_of_mem (Set.mem_singleton x)]
  ext y
  simp only [Submodule.restrictScalars_mem, Submodule.mem_span_pair, smul_neg, Subtype.exists]
  constructor
  · rintro ⟨a, _, b, _, rfl⟩
    exact ⟨a, b, rfl⟩
  · rintro ⟨a, b, rfl⟩
    obtain ⟨c, hac, hbc⟩ := exists_ge_ge a b
    refine ⟨c - b, sub_nonneg.mpr hbc, c - a, sub_nonneg.mpr hac, ?_⟩
    calc
      -((c - b) • x) + (c - a) • x = (-(c - b) + (c - a)) • x := by
        rw [← neg_smul, ← add_smul]
      _ = (b - a) • x := by
        congr 1
        abel
      _ = -(a • x) + b • x := by
        rw [sub_smul]
        abel

@[simp] lemma hull_sup_hull_neg_eq_submodule_span (s : Set M) :
    hull R s ⊔ hull R (-s) = span R s := by
  ext x
  constructor <;> intro h
  · obtain ⟨_, hy, _, hz, rfl⟩ := Submodule.mem_sup.mp h
    exact add_mem
      (Submodule.mem_span.mpr fun p hp => Submodule.mem_span.mp hy p hp)
      (Submodule.mem_span.mpr fun p hp => Submodule.mem_span.mp hz p <| by
        intro y hy
        simpa using p.neg_mem (hp (Set.mem_neg.mp hy)))
  · rw [Submodule.restrictScalars_mem, Submodule.mem_span_set'] at h
    obtain ⟨n, f, g, rfl⟩ := h
    have hx : ∑ i, f i • (g i : M) ∈ hull R (-s ∪ s) := by
      refine sum_mem ?_
      intro i _
      have hpair : f i • (g i : M) ∈ hull R ({-(g i : M), (g i : M)} : Set M) := by
        rw [hull_neg_pair_eq_span_singleton (R := R) (x := (g i : M))]
        exact Submodule.mem_span_singleton.mpr ⟨f i, by simp⟩
      exact Set.mem_of_subset_of_mem (Submodule.span_mono <| by
        intro z hz
        rcases Set.mem_insert_iff.mp hz with rfl | hz
        · exact Set.mem_union_left _ (by simp [(g i).property])
        · rcases Set.mem_singleton_iff.mp hz with rfl
          exact Set.mem_union_right _ (g i).property) hpair
    simpa [hull_union, sup_comm, Set.union_comm] using hx

-- NOTE: if this is implemented, it is more general than what mathlib already provides
-- for converting submodules into pointed cones. Especially the proof that R≥0 is an FG
-- submodule of R should be easier with this.
@[simp] lemma hull_union_neg_eq_submodule_span (s : Set M) :
    hull R (-s ∪ s) = span R s := by
  ext x
  simp only [Submodule.mem_span, Set.union_subset_iff, and_imp,
    Submodule.restrictScalars_mem]
  constructor <;> intros h B sB
  · refine h (B.restrictScalars _) ?_ sB
    rw [Submodule.coe_restrictScalars]
    exact fun _ tm => neg_mem_iff.mp (sB tm)
  · intro nsB
    have : x ∈ (Submodule.span R s : PointedCone R M) :=
      h (Submodule.span R s) Submodule.subset_span
    rw [← hull_sup_hull_neg_eq_submodule_span] at this
    obtain ⟨_, h₁, _, h₂, h⟩ := Submodule.mem_sup.mp this
    rw [← h]
    apply add_mem
    · exact Set.mem_of_subset_of_mem (Submodule.span_le.mpr nsB) h₁
    · exact Set.mem_of_subset_of_mem (Submodule.span_le.mpr sB) h₂

lemma hull_eq_submodule_span_of_neg_self {s : Set M} (hs : s = -s) :
    hull R s = Submodule.span R s := by
  nth_rw 1 [← Set.union_self s, hs]
  exact hull_union_neg_eq_submodule_span s

section Pointwise

open Pointwise

lemma sup_neg_eq_linSpan (C : PointedCone R M) : -C ⊔ C = span R (C : Set M) := by
  nth_rw 1 2 [← Submodule.span_eq C]
  rw [← Submodule.span_neg_eq_neg, ← Submodule.span_union]
  exact hull_union_neg_eq_submodule_span (C : Set M)

-- NOTE: I think only one of `neg_eq_iff_eq_linSpan` and `neg_eq_iff_eq_linSpan` is needed.
--  I don't know which.

lemma neg_eq_iff_eq_linSpan {C : PointedCone R M} : -C = C ↔ span R (C : Set M) = C := by
  rw [← sup_neg_eq_linSpan, sup_eq_right]
  exact Submodule.neg_eq_self_iff_neg_le

lemma neg_le_iff_eq_linSpan {C : PointedCone R M} : -C ≤ C ↔ span R (C : Set M) = C :=
  Iff.trans Submodule.neg_eq_self_iff_neg_le.symm neg_eq_iff_eq_linSpan

end Pointwise

lemma mem_span {C : PointedCone R M} {x : M} :
    x ∈ span R C ↔ ∃ p ∈ C, ∃ n ∈ C, p = x + n := by
  rw [← mem_ofSubmodule_iff, ← sup_neg_eq_linSpan, Submodule.mem_sup]
  simp only [Submodule.mem_neg]
  constructor <;> intro h
  · obtain ⟨y, hy', z, hz, rfl⟩ := h
    exact ⟨z, hz, -y, hy', by simp⟩
  · obtain ⟨p, hp, n, hn, rfl⟩ := h
    exact ⟨-n, by simp [hn], x + n, hp, by simp⟩

end DirectedOrder

section PartialOrder

variable {R M : Type*} [Ring R] [PartialOrder R] [IsOrderedRing R] [AddCommGroup M] [Module R M]

-- This lemma is used in Faces/Basic.lean. It should probably be moved there.
open Submodule in
lemma uniq_decomp_of_zero_inter {C D : PointedCone R M} {xC xD yC yD : M}
    (mxc : xC ∈ C) (myc : yC ∈ C) (mxd : xD ∈ D) (myd : yD ∈ D)
    (hCD : Disjoint (span R (C : Set M)) (span R D))
    (s : xC + xD = yC + yD) :
    xC = yC ∧ xD = yD := by
  let sub_mem_span {C : PointedCone R M} {x y} (mx : x ∈ C) (my : y ∈ C) :=
    (span R (C : Set M)).sub_mem (mem_span_of_mem my) (mem_span_of_mem mx)
  replace hCD := disjoint_def.mp hCD
  constructor
  · refine (sub_eq_zero.mp <| hCD _ (sub_mem_span mxc myc) ?_).symm
    rw [add_comm] at s
    rw [sub_eq_sub_iff_add_eq_add.mpr s.symm]
    exact sub_mem_span myd mxd
  · refine (sub_eq_zero.mp <| hCD _ ?_ (sub_mem_span mxd myd)).symm
    nth_rewrite 2 [add_comm] at s
    rw [← sub_eq_sub_iff_add_eq_add.mpr s]
    exact sub_mem_span myc mxc

end PartialOrder

section LinearOrder

variable {R : Type*} [Ring R] [LinearOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

section Map

variable {M' : Type*} [AddCommMonoid M'] [Module R M']

lemma map_hull (f : M →ₗ[R] M') (s : Set M) : map f (hull R s) = hull R (f '' s) :=
  Submodule.map_span _ _

end Map

-- -- ## LINEAR EQUIV

-- variable {R : Type*} [Ring R] [PartialOrder R] [IsOrderedRing R]
-- variable {M : Type*} [AddCommGroup M] [Module R M]
-- variable {N : Type*} [AddCommGroup N] [Module R N]

-- local notation "R≥0" => {c : R // 0 ≤ c}

-- noncomputable def IsCompl.map_mkQ_equiv_inf {S T : Submodule R M} (hST : IsCompl S T)
--     {C : PointedCone R M} (hSC : S ≤ C) : map S.mkQ C ≃ₗ[R≥0] (C ⊓ T : PointedCone R M) :=
--   Submodule.IsCompl.map_mkQ_equiv_inf hST hSC

-- structure LinearlyEquiv (s : Set M) (t : Set N) where
--   toFun : M →ₗ[R] N
--   toInv : N →ₗ[R] M
--   inv_fun : ∀ x ∈ s, toInv (toFun x) = x
--   fun_inv : ∀ x ∈ t, toFun (toInv x) = x
-- example (S : PointedCone R M) (T : PointedCone R N) : S ≃ₗ[R≥0] T := sorry

end LinearOrder

end Ring


-- # QUOTIENTS

/- Most, if not everything, from this section should be proven for general restricted scalars. -/

section Quotient

open Submodule (span)

variable {R M : Type*} [Ring R] [PartialOrder R] [IsOrderedRing R] [AddCommGroup M]
  [Module R M] {S : Set M}

variable {C : PointedCone R M}

/-- The quotient of a cone along a submodule. -/
abbrev quot (C : PointedCone R M) (S : Submodule R M) : PointedCone R (M ⧸ S) := C.map S.mkQ

lemma quot_def (C : PointedCone R M) (S : Submodule R M) : C.quot S = C.map S.mkQ := rfl

lemma quot_eq_bot_iff (C : PointedCone R M) (S : Submodule R M) :
    C.quot S = ⊥ ↔ C ≤ S := by
  simp only [quot, PointedCone.ext_iff, PointedCone.map]
  constructor
  · intro h x hx
    exact (Submodule.Quotient.mk_eq_zero _).mp <| (h (S.mkQ x)).mp ⟨x, hx, rfl⟩
  · intro h y
    simp only [Submodule.mem_map, LinearMap.coe_restrictScalars, Submodule.mkQ_apply,
      Submodule.mem_bot]
    constructor
    · rintro ⟨y₁, hy₁, rfl⟩
      exact (Submodule.Quotient.mk_eq_zero S).mpr (h hy₁)
    · rintro rfl
      exact ⟨0, C.zero_mem, Submodule.Quotient.mk_zero S⟩

lemma quot_bot_of_le {S : Submodule R M} (h : C ≤ S) : C.quot S = ⊥ := (quot_eq_bot_iff C S).mpr h

lemma quot_span : C.quot (.span R C) = ⊥ := quot_bot_of_le Submodule.le_span

lemma quot_fg (hC : C.FG) (S : Submodule R M) : (C.quot S).FG := hC.map _

/-- The span of a quotient cone is the image of the span under the quotient map. -/
@[simp] lemma span_quot (C : PointedCone R M) (S : Submodule R M) :
    span R (C.quot S) = Submodule.map S.mkQ (span R C) := by
  simp [PointedCone.quot]

@[simp] lemma sup_quot_eq_quot (C : PointedCone R M) (S : Submodule R M) :
    (C ⊔ S).quot S = C.quot S :=
  Submodule.map_mkQ_eq_iff_sup_eq.mpr (by simp)

@[simp]
lemma quot_eq_iff_sup_eq {S : Submodule R M} {C D : PointedCone R M} :
    C.quot S = D.quot S ↔ C ⊔ S = D ⊔ S := Submodule.map_mkQ_eq_iff_sup_eq

@[simp] lemma map_mkQ_le_iff_sup_le {p : Submodule R M} {s t : PointedCone R M} :
    map p.mkQ s ≤ map p.mkQ t ↔ s ⊔ p ≤ t ⊔ p := Submodule.map_mkQ_le_iff_sup_le

@[simp] lemma map_mkQ_eq_iff_sup_eq {p : Submodule R M} {s t : PointedCone R M} :
    map p.mkQ s = map p.mkQ t ↔ s ⊔ p = t ⊔ p := Submodule.map_mkQ_eq_iff_sup_eq

section CommRing

variable {R M : Type*} [CommRing R] [PartialOrder R] [IsOrderedRing R] [AddCommGroup M]
  [Module R M] {S : Set M}

local notation "R≥0" => {c : R // 0 ≤ c}

noncomputable def IsCompl.map_mkQ_equiv_inf {S T : Submodule R M} (hST : IsCompl S T)
    {C : PointedCone R M} (hSC : S ≤ C) : C.quot S ≃ₗ[R≥0] (C ⊓ T : PointedCone R M) :=
  Submodule.IsCompl.map_mkQ_equiv_inf hST hSC

end CommRing

end Quotient

section DivisionRing

variable {R M : Type*} [DivisionRing R] [LinearOrder R] [IsOrderedRing R] [AddCommGroup M]
  [Module R M] {S : Set M}

-- -- TODO: golf this
-- theorem smul_mem_iff {C : PointedCone R M} {c : R} (hc : 0 < c) {x : M} : c • x ∈ C ↔ x ∈ C := by
--   constructor <;> intro h
--   · have h := C.smul_mem (le_of_lt <| inv_pos.mpr hc) h
--     rw [inv_smul_smul₀ (ne_of_lt hc).symm] at h
--     exact h
--   · exact C.smul_mem (le_of_lt hc) h

-- analogue of `Submodule.span_singleton_smul_eq`
theorem hull_singleton_smul_eq {r : R} (hr : r > 0) (x : M) : R ∙₊ (r • x) = R ∙₊ x := by
  ext y
  simp only [Submodule.mem_span_singleton, Subtype.exists, Nonneg.mk_smul, exists_prop]
  constructor <;> intro h <;> obtain ⟨a, ha, h⟩ := h
  · use a * r
    constructor
    · exact mul_nonneg ha (le_of_lt hr)
    · simpa [smul_smul] using h
  · use a * r⁻¹
    constructor
    · exact mul_nonneg ha (le_of_lt (inv_pos.mpr hr))
    · simpa [smul_smul, inv_mul_cancel_right₀ (ne_of_lt hr).symm] using h

end DivisionRing

section Field

variable {R M : Type*} [Field R] [LinearOrder R] [IsOrderedRing R] [AddCommGroup M]
  [Module R M] {S : Set M}

open Set Pointwise

/-- If there is a linear map that is positive on the entire cone except 0, the cone is the sMul-span
of any positive level set of the map. -/
lemma eq_Ioi_zero_smul_inter_preimage_of_pos {C : PointedCone R M} {f : M →ₗ[R] R} {r : R}
    (hf : ∀ x ∈ C, x ≠ 0 → 0 < f x) (hr : 0 < r) :
    (C : Set M) \ {0} = Set.Ioi (0 : R) • ((C : Set M) ∩ f ⁻¹' {r}) := by
  ext x
  constructor
  · intro ⟨hxC, hx0⟩
    refine ⟨r⁻¹ • f x, smul_pos (inv_pos.mpr hr) <| hf x hxC hx0, (r • (f x)⁻¹) • x, ⟨?_, ?_⟩, ?_⟩
    · exact C.smul_mem (smul_pos hr <| inv_pos.mpr (hf _ hxC hx0)).le hxC
    · simp [inv_mul_cancel₀ (ne_of_gt (hf x hxC hx0)), mul_assoc]
    · simp only [smul_eq_mul, smul_smul]
      field_simp [ne_of_gt (hf x hxC hx0)]
      exact MulAction.one_smul x
  · rintro ⟨r, hri, y, ⟨hyC, hfy⟩, rfl⟩
    have hy0 : y ≠ 0 := by intro hc; simp only [hc, mem_preimage, map_zero,
      Set.mem_singleton_iff] at hfy; exact hr.ne hfy
    exact ⟨C.smul_mem (mem_Ioi.mp hri).le hyC, by simp [ne_of_gt hri, hy0]⟩

/-- If there is a linear map that is positive on the entire cone except 0, the cone is the closed
sMul-span of any positive level set of the map. -/
lemma eq_Ici_zero_smul_inter_preimage_of_pos_of_ne_bot {C : PointedCone R M} {f : M →ₗ[R] R} {r : R}
    (hf : ∀ x ∈ C, x ≠ 0 → 0 < f x) (hr : 0 < r) (hC : C ≠ ⊥) :
    C = Set.Ici (0 : R) • ((C : Set M) ∩ f ⁻¹' {r}) := by
  ext x
  by_cases hx : x = 0
  · subst hx
    simp only [SetLike.mem_coe, zero_mem, true_iff]
    use 0, le_rfl
    simp only [mem_inter_iff, SetLike.mem_coe, mem_preimage, mem_singleton_iff, zero_smul, and_true]
    obtain ⟨x, hx⟩ := C.ne_bot_iff.mp hC
    use r • (f x)⁻¹ • x
    have fxpos : 0 < f x := hf x hx.1 hx.2
    simp only [← smul_assoc, smul_eq_mul, map_smul]
    refine ⟨C.smul_mem (mul_pos hr (inv_pos.mpr fxpos)).le hx.1, ?_⟩
    simp [mul_assoc, inv_mul_cancel₀ fxpos.ne.symm]
  · constructor <;> intro h
    · apply Set.smul_subset_smul_right Ioi_subset_Ici_self
      exact eq_Ioi_zero_smul_inter_preimage_of_pos hf hr ▸ mem_sdiff_singleton.mpr ⟨h, hx⟩
    · obtain ⟨_, hr, _, hy, b⟩ := h
      simpa [← b] using C.smul_mem hr (mem_of_mem_inter_left hy)

end Field

end PointedCone
