/-
Copyright (c) 2025 Justus Springer, Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Justus Springer, Martin Winter
-/
import Mathlib.LinearAlgebra.Dual.Defs
import Mathlib.LinearAlgebra.PerfectPairing.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.SesquilinearForm.Basic

import Polyhedral.Mathlib.Algebra.Module.Submodule.FG
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.CoFG

/-!
# Polyhedral cones

Given a bilinear pairing `p` between two `R`-modules `M` and `N`, we define
polyhedral cones to be pointed cones in `N` that are the dual of a finite set
in `M` (this means they are the intersection of finitely many halfspaces).

The main statement is that if both `M` and `N` are finite and the pairing is injective
in both arguments, then polyhedral cones are precisely the finitely generated cones, see
`isPolyhedral_iff_fg`. Moreover, we obtain that the dual of a polyhedral cone is again polyhedral
(`IsPolyhedral.dual`) and that the double dual of a polyhedral cone is the cone itself
(`IsPolyhedral.dual_dual_flip`, `IsPolyhedral.dual_flip_dual`).
-/

open Function Module LinearMap
open Submodule hiding span dual

variable {𝕜 M N : Type*}

namespace PointedCone

alias sup_fg := Submodule.FG.sup

section LinearOrder

variable [Field 𝕜] [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜] [AddCommGroup M] [AddCommGroup N]
  [Module 𝕜 M] [Module 𝕜 N] {p : M →ₗ[𝕜] N →ₗ[𝕜] 𝕜} {C : PointedCone 𝕜 M} {s : Set M} {w : N}

variable (p s w) in
/-- A set whose dual cone is `span R {w} ⊔ dual p s`, see `dual_sup_span_singleton_eq_dual` -/
private noncomputable abbrev auxGenSet : Set M :=
  {x ∈ s | 0 ≤ p x w} ∪
    .image2 (fun x y ↦ p x w • y - p y w • x) {x ∈ s | 0 ≤ p x w} {y ∈ s | p y w < 0}

variable (w) in
omit [IsStrictOrderedRing 𝕜] in
private lemma auxGenSet_finite (hs : s.Finite) :
    (auxGenSet p s w).Finite := .union (hs.sep _) <| .image2 _ (hs.sep _) (hs.sep _)

private lemma auxGenSet_subset_span :
    (auxGenSet p s w : Set M) ⊆ span 𝕜 (s : Set M) := by
  simp only [Set.union_subset_iff, Set.image2_subset_iff, Set.mem_setOf_eq, and_imp]
  refine ⟨subset_trans (fun x hx ↦ hx.1) subset_span, fun x hxS hxw y hyS hyw ↦ ?_⟩
  -- simpa [sub_eq_add_neg] using add_mem (smul_mem (span 𝕜 s) ⟨p x w, hxw⟩ (subset_span hyS))
  --   (smul_mem _ ⟨-p y w, neg_nonneg.mpr hyw.le⟩ (subset_span hxS))
  sorry -- this code broke on mathlib/Lean update ...

private lemma span_singleton_le_dual_auxGenSet :
    span 𝕜 {w} ≤ dual p (auxGenSet p s w) := by
  simp only [span_singleton_le_iff_mem, mem_dual, Set.mem_union, Set.mem_setOf_eq, Set.mem_image2]
  rintro z (hz | ⟨x, ⟨hxS, hxw⟩, y, ⟨hyS, hyw⟩, rfl⟩)
  · exact hz.2
  · simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg]
    rw [mul_comm]

/-- The crucial lemma in the proof that a finitely generated cone is polyhedral:
The sum of a polyhedral cone and the cone generated by a single ray is again polyhedral. -/
private lemma dual_auxGenSet (hs : s.Finite) :
    dual p (auxGenSet p s w) = span 𝕜 {w} ⊔ dual p s := by
  classical
  apply ge_antisymm
  · rw [← dual_span]
    exact sup_le span_singleton_le_dual_auxGenSet <| dual_le_dual auxGenSet_subset_span
  obtain hSw | hSw := {y ∈ s | p y w < 0}.eq_empty_or_nonempty
  · simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    exact le_sup_of_le_right <| dual_le_dual fun x hx => .inl ⟨hx, hSw _ hx⟩
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]
  replace hv2 {x y : M} (hx : x ∈ s ∧ 0 ≤ p x w) (hy : y ∈ s ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_setOf_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2
  obtain hSv | ⟨y, hy⟩ := {y ∈ s | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · simp +contextual only [Set.sep_and, Set.eq_empty_iff_forall_notMem, Set.mem_inter_iff,
      Set.mem_setOf_eq, not_and, true_and, not_lt, and_imp] at hSv
    refine ⟨0, zero_mem _, v, fun x hx => ?_, zero_add _⟩
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hx, hxw⟩
    · exact hSv x hx (lt_of_not_ge hxw)
  lift s to Finset M using hs
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' <| by
    simpa [Finset.Nonempty, Set.Nonempty] using hSw.image _
  have hu : 0 ≤ u := by
    refine le_trans (mul_nonneg_of_nonpos_of_nonpos hy.2.2.le (inv_nonpos.mpr hy.2.1.le))
      (Finset.le_max' _ (p y v * (p y w)⁻¹) ?_)
    simp only [Finset.mem_image, Finset.mem_filter]
    exact ⟨y, ⟨hy.1, hy.2.1⟩, rfl⟩
  refine ⟨u • w, ?_, v - u • w, fun z hzS ↦ ?_, add_sub_cancel _ _⟩
  · rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)
  simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
  obtain hzw | hzw := lt_or_ge (p z w) 0
  · rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw), mul_inv_cancel_right₀ hzw.ne]
    exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
      Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
  obtain ⟨y, hy, t_eq : _ = u⟩ := Finset.mem_image.mp <|
    ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem <| by
      simpa [Finset.Nonempty, Set.Nonempty] using hSw.image _
  rw [Finset.mem_filter] at hy
  rw [← t_eq, ← _root_.mul_le_mul_left_of_neg hy.2, ← mul_assoc]
  nth_rw 4 [mul_comm]
  rw [mul_inv_cancel_left₀ hy.2.ne]
  exact hv2 ⟨hzS, hzw⟩ hy

/-- The union of an FG cone and a CoFG cone is CoFG. -/
lemma sup_fg_cofg {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.CoFG p) : (C ⊔ D).CoFG p
    := by classical
  obtain ⟨s, rfl⟩ := hC
  induction s using Finset.induction with
  | empty => simp [hD]
  | insert w s hws hs =>
    obtain ⟨t, ht⟩ := hs
    use (auxGenSet p t.toSet w).toFinset
    simp [span_insert, sup_assoc, ← ht]
    exact dual_auxGenSet t.finite_toSet

lemma sup_cofg_fg {C D : PointedCone 𝕜 N} (hC : C.CoFG p) (hD : D.FG) : (C ⊔ D).CoFG p
    := by rw [sup_comm]; exact sup_fg_cofg hD hC

variable (p) [Fact p.IsFaithfulPair] in
/-- An FG cone can be written as the intersection of a CoFG cone and an FG submodule. -/
lemma FG.exists_cofg_inf_submodule {C : PointedCone 𝕜 N} (hC : C.FG)
    {S : Submodule 𝕜 N} (hS : S.FG) (hCS : C ≤ S) :
      ∃ D : PointedCone 𝕜 N, D.CoFG p ∧ D ⊓ S = C := by
  wlog hC' : C = ⊥ with h
  · specialize h p fg_bot hS bot_le rfl
    obtain ⟨D, hcofg, hD⟩ := h
    exact ⟨_, sup_fg_cofg hC hcofg, by simp [← sup_inf_assoc_of_le_submodule D hCS, hD]⟩
  · obtain ⟨D, hcofg, hD⟩ := hS.exists_cofg_inf_bot p
    exact ⟨_, coe_cofg.mpr hcofg, by simp [← restrictScalars_inf, inf_comm, hD, hC']⟩

variable (p) [Fact p.IsFaithfulPair] in
/-- An FG cone can be written as the intersection of its linear span with a CoFG cone. -/
lemma FG.exists_cofg_sup_span {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.CoFG p ∧ D ⊓ Submodule.span 𝕜 (M := N) C = C :=
  exists_cofg_inf_submodule p hC (span_fg hC) Submodule.subset_span

variable (p) [Fact p.IsFaithfulPair] in
/-- An FG cone can be written as the intersection of a CoFG cone and an FG submodule. -/
lemma FG.exists_cofg_sup_fg_submodule {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.CoFG p ∧ ∃ S : Subspace 𝕜 N, S.FG ∧ D ⊓ S = C := by
  obtain ⟨D, hcofg, hD⟩ := exists_cofg_sup_span p hC
  exact ⟨D, hcofg, Submodule.span 𝕜 C, submodule_span_fg hC, hD⟩

variable (p) [Fact p.IsFaithfulPair] in
/-- An FG cone is the dual of a CoFG cone. -/
lemma FG.exists_cofg_flip_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.CoFG p.flip ∧ dual p D = C := by
  obtain ⟨D, hD, S, hS, rfl⟩ := exists_cofg_sup_fg_submodule p hC
  obtain ⟨C', hfg, rfl⟩ := hD.exists_fg_dual
  use C' ⊔ dual p.flip S
  constructor
  · exact sup_fg_cofg hfg <| cofg_of_fg p.flip (ofSubmodule_fg_of_fg hS)
  · simp [dual_sup_dual_inf_dual, Submodule.fg_dual_dual_flip hS]
    -- TODO: prove `Submodule.fg_dual_dual_flip` (the equivalent for cones was already proven here).

variable (p) [Fact p.flip.IsFaithfulPair] in
/-- An FG cone is the dual of a CoFG cone. -/
lemma FG.exists_cofg_dual_flip {C : PointedCone 𝕜 M} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.CoFG p ∧ dual p.flip D = C := by
  rw [← flip_flip p]; exact exists_cofg_flip_dual p.flip hC

variable (p) [Fact p.IsFaithfulPair] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp]
lemma FG.dual_dual_flip {C : PointedCone 𝕜 N} (hC : C.FG) : dual p (dual p.flip C) = C := by
  obtain ⟨D, hcofg, rfl⟩ := exists_cofg_flip_dual p hC
  exact dual_dual_flip_dual (p := p) D

variable (p) [Fact p.flip.IsFaithfulPair] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp]
lemma FG.dual_flip_dual {C : PointedCone 𝕜 M} (hC : C.FG) : dual p.flip (dual p C) = C := by
  rw [← flip_flip p]; exact dual_dual_flip p.flip hC

variable (p) [Fact p.IsFaithfulPair] in
/-- The double dual of a finite set is its span. -/
@[simp]
lemma FG.dual_dual_flip_eq_span (s : Finset N) : dual p (dual p.flip s) = span 𝕜 s := by
  nth_rw 2 [← dual_span]
  exact dual_dual_flip p (fg_span s.finite_toSet)

variable (p) [Fact p.flip.IsFaithfulPair] in
/-- The double dual of a finite set is its span. -/
@[simp]
lemma FG.dual_flip_dual_eq_span (s : Finset M) : dual p.flip (dual p s) = span 𝕜 s := by
  rw [← flip_flip p]; exact dual_dual_flip_eq_span p.flip s

variable (p) [Fact p.IsFaithfulPair] in
lemma FG.dual_flip_inj {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FG)
    (h : dual p.flip C = dual p.flip D) : C = D := by
  have h := congrArg (dual p) <| congrArg SetLike.coe h
  rw [dual_dual_flip _ hC, dual_dual_flip _ hD] at h
  exact h

variable (p) [Fact p.flip.IsFaithfulPair] in
lemma FG.dual_inj {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG)
    (h : dual p C = dual p D) : C = D := by
  rw [← flip_flip p] at h; exact dual_flip_inj p.flip hC hD h

variable [Fact p.IsFaithfulPair] in
@[simp] lemma FG.dual_flip_inj_iff {C D : PointedCone 𝕜 N} {hC : C.FG} {hD : D.FG} :
    dual p.flip C = dual p.flip D ↔ C = D := ⟨dual_flip_inj p hC hD, by simp +contextual⟩

variable [Fact p.flip.IsFaithfulPair] in
@[simp] lemma FG.dual_inj_iff {C D : PointedCone 𝕜 M} {hC : C.FG} {hD : D.FG} :
    dual p C = dual p D ↔ C = D := ⟨dual_inj p hC hD, by simp +contextual⟩

variable [Fact p.IsFaithfulPair] in
/-- The dual of a CoFG cone is FG. -/
lemma CoFG.dual_fg {C : PointedCone 𝕜 M} (hC : C.CoFG p.flip) : (dual p C).FG := by
  obtain ⟨D, hfg, rfl⟩ := exists_fg_dual hC
  rw [FG.dual_dual_flip p hfg]
  exact hfg

variable [Fact p.flip.IsFaithfulPair] in
/-- The dual of a CoFG cone is FG. -/
lemma CoFG.dual_flip_fg {C : PointedCone 𝕜 N} (hC : C.CoFG p) : (dual p.flip C).FG := by
  rw [← flip_flip p] at hC; exact dual_fg hC

section Module.Finite

variable [Module.Finite 𝕜 N]

variable (p) [Fact p.IsFaithfulPair] in
/-- A finite dimensional FG cone is also CoFG. -/
lemma FG.cofg {C : PointedCone 𝕜 N} (hC : C.FG) : C.CoFG p := by
  obtain ⟨D, hcofg, rfl⟩ := exists_cofg_inf_submodule p hC Finite.fg_top (by simp)
  simpa using hcofg

/-- A finite dimensional CoFG cone is also FG. -/
lemma CoFG.fg {C : PointedCone 𝕜 N} (hC : C.CoFG p) : C.FG := by
  obtain ⟨D, hfg, rfl⟩ := (cofg_id hC).exists_fg_dual
  exact CoFG.dual_fg <| FG.cofg _ hfg

-- variable [Module.Finite 𝕜 N] in
-- variable [Fact p.IsFaithfulPair] in
-- /-- A finite dimensional cone is FG if and only if it is CoFG. -/
-- lemma fg_iff_cofg {C : PointedCone 𝕜 N} : C.CoFG p ↔ C.FG := ⟨CoFG.fg, FG.cofg p⟩

variable (p) in
/-- In finite dimensional space, the dual of and FG cone is itself FG. -/
lemma FG.dual_fg {C : PointedCone 𝕜 M} (hC : C.FG) : (dual p C).FG := by
  rw [dual_id_map]
  exact CoFG.dual_fg <| FG.cofg _ <| FG.map (LinearMap.restrictScalars _ p) hC

/-- In finite dimensional space, the dual of and CoFG cone is itself CoFG. -/
lemma CoFG.dual_cofg {C : PointedCone 𝕜 N} (hC : C.CoFG p) : (dual p.flip C).CoFG p.flip
  := FG.dual_cofg p.flip (CoFG.fg hC)

-- TODO: implement pairing lemmas that allow inference of `Module.Finite 𝕜 M`.
--  We should preferably assume `Module.Finite 𝕜 N`
omit [Module.Finite 𝕜 N] in
variable (p) [Module.Finite 𝕜 M] [Fact p.IsFaithfulPair] in
lemma FG.exists_fg_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ dual p D = C := by
  use dual p.flip C
  exact ⟨FG.dual_fg p.flip hC, FG.dual_dual_flip p hC⟩

-- -- see `inf_fg` for version not assuming Module.Finite
-- variable [Module.Finite 𝕜 M] in
-- private lemma inf_fg' {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) : (C ⊓ D).FG := by
--   exact CoFG.fg <| inf_cofg (FG.cofg .id hC) (FG.cofg .id hD)

-- -- see `FG.restrict_fg` for version not assuming Module.Finite
-- variable [Module.Finite 𝕜 M] in
-- private lemma FG.restrict_fg' (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
--     (C.restrict S).FG := by
--   rw [← restrict_inf_submodule]
--   refine restrict_fg_of_fg_le (by simp) ?_
--   exact inf_fg' hC <| restrictedScalars_fg_of_fg _ (IsNoetherian.noetherian S)

-- -- NOTE: assumption `p.flip.IsFaithfulPair` cannot be dropped!
-- variable (p) [Fact p.flip.IsFaithfulPair] [Fact p.IsFaithfulPair] in
-- private lemma FG.dual_inf_dual_sup_dual' {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
--     dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
--   nth_rw 1 [← FG.dual_flip_dual p hC]
--   nth_rw 1 [← FG.dual_flip_dual p hD]
--   rw [← dual_sup_dual_inf_dual]
--   rw [FG.dual_dual_flip]
--   exact sup_fg (FG.dual_fg p hC) (FG.dual_fg p hD)

-- NOTE: assumption `p.flip.IsFaithfulPair` cannot be dropped!
variable (p) [Fact p.flip.IsFaithfulPair] in
private lemma FG.dual_inf_dual_sup_dual' {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨C', hC', rfl⟩ := FG.exists_cofg_dual_flip p hC
  obtain ⟨D', hD', rfl⟩ := FG.exists_cofg_dual_flip p hD
  rw [← dual_sup_dual_inf_dual, CoFG.dual_dual_flip <| sup_fg_cofg (CoFG.fg hC') hD',
    CoFG.dual_dual_flip hC', CoFG.dual_dual_flip hD']

end Module.Finite

/-- The intersection of two FG cones is an FG cone. -/
lemma inf_fg {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) : (C ⊓ D).FG := by
  wlog _ : Module.Finite 𝕜 M with h
  · let CD : Submodule 𝕜 M := .span 𝕜 (C ⊔ D : PointedCone 𝕜 M)
    have hCle : C ≤ CD := le_submodule_span_of_le le_sup_left
    have hDle : D ≤ CD := le_submodule_span_of_le le_sup_right
    specialize h (restrict_fg_of_fg_le hCle hC) (restrict_fg_of_fg_le hDle hD)
      (Finite.iff_fg.mpr <| span_fg <| sup_fg hC hD)
    rw [← restrict_inf] at h
    exact fg_of_restrict_le (le_submodule_span_of_le inf_le_sup) h
  · exact CoFG.fg <| cofg_inf (FG.cofg .id hC) (FG.cofg .id hD) -- inf_fg' hC hD

/- TODO: the equivalent of the below statement with CoFG instead of FG can likely be proven
  under rather weak assumptions (Noetherian or so). -/

/-- The intersection of an FG cone with an arbitrary submodule is FG. -/
lemma inf_fg_submodule {C : PointedCone 𝕜 M} (hC : C.FG) (S : Submodule 𝕜 M) : (C ⊓ S).FG := by
  rw [left_eq_inf.mpr (le_submodule_span_self C), inf_assoc, ← coe_inf]
  exact inf_fg hC <| coe_fg <| inf_fg_left (span_fg hC) S

lemma inf_submodule_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG)
    : (S ⊓ C : PointedCone 𝕜 M).FG := by rw [inf_comm]; exact inf_fg_submodule hC S

/-- The restriction of an FG cone to an arbitrary submodule is FG. -/
lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
    (C.restrict S).FG := by
  rw [restrict_fg_iff_inf_fg]; exact inf_submodule_fg S hC

/-- The intersection of an FG cone and a CoFG cone is FG. -/
lemma inf_fg_cofg {C D : PointedCone 𝕜 N}
    (hC : C.FG) (hD : D.CoFG p) : (C ⊓ D).FG := by
  obtain ⟨C', hCcofg, rfl⟩ := FG.exists_cofg_flip_dual .id hC
  obtain ⟨D', hDfg, rfl⟩ := CoFG.exists_fg_dual (cofg_id hD)
  rw [← dual_sup_dual_inf_dual]
  exact CoFG.dual_fg (sup_cofg_fg hCcofg hDfg)

/-- The intersection of a CoFG cone and an FG cone is FG. -/
lemma inf_cofg_fg {C D : PointedCone 𝕜 N} (hC : C.CoFG p) (hD : D.FG) : (C ⊓ D).FG
    := by rw [inf_comm]; exact inf_fg_cofg hD hC

-- TODO: Should *not* rely on `p.flip.IsFaithfulPair`.
variable (p) [Fact p.IsFaithfulPair] [Fact p.flip.IsFaithfulPair] in
lemma dual_fg_inf_cofg_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.CoFG p.flip) : dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨C', hC', rfl⟩ := FG.exists_cofg_dual_flip p hC
  obtain ⟨D', hD', rfl⟩ := CoFG.exists_fg_dual hD
  rw [← dual_sup_dual_inf_dual]
  rw [CoFG.dual_dual_flip <| sup_cofg_fg hC' hD']
  rw [CoFG.dual_dual_flip hC']
  rw [FG.dual_dual_flip p hD']

lemma dual_fg_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.FG) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

lemma dual_cofg_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.CoFG p.flip) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

-- TODO: this should not rely on `p.flip.IsFaithfulPair`
variable (p) [Fact p.IsFaithfulPair] [Fact p.flip.IsFaithfulPair] in
lemma dual_inf_cofg_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨D', hcofg, S, hfg, rfl⟩ := FG.exists_cofg_sup_fg_submodule p.flip hD
  rw [inf_comm, inf_assoc, inf_comm]
  rw [dual_fg_inf_cofg_dual_sup_dual _ (inf_fg (coe_fg hfg) hC) hcofg]
  rw [inf_comm]
  rw [dual_fg_inf_submodule_dual_sup_dual hC hfg]
  rw [sup_assoc]; nth_rw 2 [sup_comm]
  rw [← dual_cofg_inf_submodule_dual_sup_dual hcofg hfg]

-- lemma foo (C : PointedCone 𝕜 M) (S : Submodule 𝕜 N) :
--   ∃ T : Submodule 𝕜 M, (dual p C).restrict S = dual (Dual.eval 𝕜 T) (C.restrict T) := by sorry

-- private lemma inf_submodule_cofg (S : Submodule 𝕜 N) {C : PointedCone 𝕜 N} (hC : C.CoFG p) :
--     (C.restrict S).CoFG p := by
--   sorry


-- ----------------- ^^^^^^^ everything up there is proven vvvvv down there is work

-- lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog hCS : C ≤ S with h
--   · let S' : Submodule 𝕜 M := .span 𝕜 C
--     have hCS : C ≤ S' := le_submodule_span_self C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (.restrict S' C)
--       (restrict_fg_of_fg_le hCS hC)
--     sorry -- restrict_mono
--   · exact restrict_fg_of_fg_le hCS hC

-- lemma FG.restrict_fg2 (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog _ : Module.Finite 𝕜 M with h
--   · let S' := Submodule.span 𝕜 (M := M) C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (restrict S' C) _ _
--     · exact restrict_fg_of_fg_le (le_submodule_span_self C) hC
--     · exact Finite.iff_fg.mpr (span_fg hC)
--     · have hfgS : (restrict S' S).FG := sorry
--       have hfgC : (restrict S' C).FG := sorry
--       sorry
--   · exact restrict_fg' S hC

lemma CoFG.dual_sup_dual_inf_dual {C D : PointedCone 𝕜 M}
    (hC : C.CoFG p.flip) (hD : D.CoFG p.flip) : dual p (C ⊓ D) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨C', hCfg', rfl⟩ := CoFG.exists_fg_dual hC
  obtain ⟨D', hDfg', rfl⟩ := CoFG.exists_fg_dual hD
  simp only [Set.inf_eq_inter, ← coe_inf, ← dual_union, ← dual_sup]
  sorry

lemma inf_fg_submodule_cofg' {S : Submodule 𝕜 N} (hS : S.FG) {C : PointedCone 𝕜 N} (hC : C.CoFG p) :
    (S ⊓ C : PointedCone 𝕜 N).FG := by
  sorry -- I think we first need to do finite theory, and then apply here

variable [Fact p.IsFaithfulPair] in
lemma inf_fg_cofg' {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.CoFG p) : (C ⊓ D).FG := by
  obtain ⟨C', hCcofg, S, hSfg, rfl⟩ := FG.exists_cofg_sup_fg_submodule p hC
  -- obtain ⟨C', hCfg, rfl⟩ := FG.exists_cofg_flip_dual p hC
  -- obtain ⟨D', hDfg, rfl⟩ := CoFG.exists_fg_dual hD
  rw [inf_comm, ← inf_assoc]
  sorry -- can be reduced to the question "is inf of FG submodule and CoFG halfspace always FG?"

lemma CoFG.exists_fg_sup_submodule {C : PointedCone 𝕜 N} (hC : C.CoFG p)
    {S : Submodule 𝕜 N} (hS : S.CoFG p) (hCS : S ≤ C) :
      ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ S = C := by
  sorry

lemma sup_cofg {C D : PointedCone 𝕜 N} (hC : C.CoFG p) (hD : D.CoFG p) : (C ⊔ D).CoFG p := by
  obtain ⟨C', hCfg, rfl⟩ := CoFG.exists_fg_dual hC
  obtain ⟨D', hDfg, rfl⟩ := CoFG.exists_fg_dual hD
  -- need dual(C ⊓ D) = dual(C) ⊔ dual(D)
  sorry

variable (p) [Fact p.flip.IsFaithfulPair] in
lemma dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ⊓ D) = (dual p C) ⊔ (dual p D) := by
  -- obtain ⟨C', hCcofg, rfl⟩ := FG.exists_cofg_dual_flip p hC
  -- obtain ⟨D', hDcofg, rfl⟩ := FG.exists_cofg_dual_flip p hD
  -- simp only [Set.inf_eq_inter]
  -- rw [← coe_inf] -- or Submodule.coe_inf
  -- rw [← dual_sup_dual_inf_dual]
  -- -- rw [CoFG.fg_dual_dual_flip p.flip hfg]
  -- -- needs C.CoFG ∧ D.CoFG → (C ⊔ D).CoFG
  sorry

lemma CoFG.is_dual_finite_inf_span''''' {C : PointedCone 𝕜 N} (hC : C.FG)
    (S : Submodule 𝕜 N) (hFG : S.FG) (hS : C ≤ S) : ∃ s : Set M, s.Finite ∧ dual p s ⊓ S = C := by
  sorry

lemma CoFG.is_dual_finite_inf_span'''' {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p s ⊓ Submodule.span (M := N) 𝕜 C = C := by
  sorry

lemma FG.dual_span_finite_sup_lineal (hC : C.FG) :
    ∃ s : Set N, s.Finite ∧ dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma FG.dual_span_finset_sup_lineal (hC : C.FG) :
    ∃ s : Finset N, dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma CoFG.dual_sup_lineal (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ dual p C = D ⊔ (dual p C).lineal := by
  sorry

lemma CoFG.is_sup_cofg_fg (hC : C.CoFG p.flip) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ D ⊔ C.lineal = C := by
  sorry

lemma CoFG.lineal_cofg (hC : C.CoFG p.flip) : C.lineal.CoFG p.flip := by
  sorry

lemma FG.is_dual_dual_of_finite (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p.flip (dual p s) = C := by
  sorry

lemma FG.is_dual_dual_of_cofg (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.CoFG p ∧ dual p.flip D = C := by
  sorry

/- The following lemmas are proven because they have equivalents for general cones that do
  not hold without the FG assumption -/

-- @[simp] lemma dual_flip_dual_inter {C C' : PointedCone 𝕜 M} (hC : C.FG) (hC' : C'.FG) :
--     dual p.flip (dual p (C ∩ C')) = C ⊓ C' := by
--   rw [← dual_flip_dual (p := p) <| inf_fg hC hC']; simp

-- @[simp] lemma dual_dual_flip_inter {C C' : PointedCone 𝕜 N} (hC : C.FG) (hC' : C'.FG) :
--     dual p (dual p.flip (C ∩ C')) = C ⊓ C' := by
--   rw [← dual_dual_flip (p := p) <| inf_fg hC hC']; simp

end LinearOrder

end PointedCone
