import Mathlib.Geometry.Convex.Cone.Dual
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.PerfectPairing.Basic
import Mathlib.Algebra.Module.Submodule.Pointwise
import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.SetTheory.Cardinal.Defs
import Mathlib.Geometry.Convex.ConvexSpace.AffineSpace

import Polyhedral.Mathlib.Algebra.Order.Nonneg.Ring
import Polyhedral.Mathlib.Algebra.Module.Submodule.FG
import Polyhedral.Mathlib.Algebra.Module.Submodule.Dual

/-! This file contains results in the intersectin of cones and linear maps. -/

namespace LinearMap

section Semiring

variable {R : Type*} [Semiring R] [PartialOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommMonoid M] [Module R M]

/-- The cone of points at which the linear form `f` is non-negative. -/
def nonneg (f : M →ₗ[R] R) : PointedCone R M where
  carrier := {x : M | 0 ≤ f x}
  add_mem' hx hy := by simpa using add_nonneg hx hy
  zero_mem' := by simp
  smul_mem' r x hx := by simpa using smul_nonneg r.2 hx

@[simp] lemma mem_nonneg {f : M →ₗ[R] R} {x : M} :
  x ∈ f.nonneg ↔ 0 ≤ f x := .rfl

@[simp] lemma nonneg_zero : nonneg (0 : M →ₗ[R] R) = ⊤ := by ext x; simp

lemma ker_le_nonneg {f : M →ₗ[R] R} : f.ker ≤ f.nonneg := fun _ => by simp +contextual

end Semiring

section IsStrictOrderedRing

variable {R : Type*} [Semiring R] [PartialOrder R] [IsStrictOrderedRing R]
variable {M : Type*} [AddCommMonoid M] [Module R M]

/-- The cone generated by the points at which the linear form `f` is positive. -/
def positive (f : M →ₗ[R] R) : PointedCone R M where
  carrier := {x : M | x ≠ 0 → 0 < f x}
  add_mem' := by
    intro x y hx hy
    by_cases hx0 : x = 0
    · simpa [hx0] using hy
    by_cases hy0 : y = 0
    · simpa [hy0] using hx
    intro _
    simpa using add_pos (hx hx0) (hy hy0)
  zero_mem' := by simp
  smul_mem' r x hx := by
    by_cases hx0 : x = 0
    · simp [hx0]
    by_cases hr : r = 0
    · simp [hr]
    intro _
    have hr : r.1 ≠ 0 := by simp [hr]
    simpa using smul_pos (lt_of_le_of_ne r.2 hr.symm) (hx hx0)

@[simp] lemma mem_positive {f : M →ₗ[R] R} {x : M} : x ∈ f.positive ↔ (x ≠ 0 → 0 < f x) := .rfl

lemma mem_positive' {f : M →ₗ[R] R} {x : M} : x ∈ f.positive ↔ (0 ≤ f x ∧ (f x = 0 → x = 0)) where
  mp h := by
    by_cases hx0 : x = 0
    · simp [hx0]
    specialize h hx0
    exact ⟨le_of_lt h, fun h' => by simp [h'] at h⟩
  mpr := by
    intro h h'
    rw [LE.le.lt_iff_ne h.1, ne_comm]
    by_contra h''
    exact h' <| h.2 h''

lemma positive_le_nonneg {f : M →ₗ[R] R} : f.positive ≤ f.nonneg := by
  intro x hx
  by_cases hx0 : x = 0
  · simp [hx0]
  exact le_of_lt (hx hx0)

lemma positive_inf_ker {f : M →ₗ[R] R} : f.positive ⊓ f.ker = ⊥ := by
  ext x
  constructor
  · intro h
    by_contra hx
    exact ne_of_lt (h.1 hx) h.2.symm
  · simp +contextual

@[simp] lemma positive_zero : positive (0 : M →ₗ[R] R) = ⊥ := by ext x; simp

lemma positive_eq_hull_preimage_singleton (f : M →ₗ[R] R) (c : R) (hc : c ≠ 0) :
    f.positive = PointedCone.hull R (f ⁻¹' {c}) := by
  sorry

lemma hull_le_positive_of_subset_preimage_singleton {f : M →ₗ[R] R} {s : Set M} {c : R}
    (hc : c ≠ 0) (hs : s ⊆ f ⁻¹' {c}) :
    PointedCone.hull R s ≤ f.positive := by
  rw [positive_eq_hull_preimage_singleton f c hc]
  exact Submodule.span_mono hs

end IsStrictOrderedRing

section Ring

variable {R M : Type*} [Ring R] [LinearOrder R] [IsOrderedRing R] [AddCommGroup M]
  [Module R M] {S : Set M}

open PointedCone Pointwise

@[simp] lemma nonneg_lineal_eq_ker {f : M →ₗ[R] R} : f.nonneg.lineal = f.ker := by
  ext x
  simp only [mem_lineal, LinearMap.mem_nonneg, map_neg, Left.nonneg_neg_iff,
    LinearMap.mem_ker]
  rw [and_comm]
  exact le_antisymm_iff.symm

@[simp] lemma neg_nonneg {f : M →ₗ[R] R} : (-f).nonneg = -f.nonneg := by
  ext x; simp

end Ring

end LinearMap
