/-
Copyright (c) 2025 Justus Springer, Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Justus Springer, Martin Winter
-/
import Mathlib.LinearAlgebra.Dual.Defs
import Mathlib.LinearAlgebra.PerfectPairing.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.SesquilinearForm.Basic

import Polyhedral.Mathlib.Algebra.Module.Submodule.DualClosed
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.FGDual

/-!
# Polyhedral cones

Given a bilinear pairing `p` between two `R`-modules `M` and `N`, we define
polyhedral cones to be pointed cones in `N` that are the dual of a finite set
in `M` (this means they are the intersection of finitely many halfspaces).

The main statement is that if both `M` and `N` are finite and the pairing is injective
in both arguments, then polyhedral cones are precisely the finitely generated cones, see
`isPolyhedral_iff_fg`. Moreover, we obtain that the dual of a polyhedral cone is again polyhedral
(`IsPolyhedral.dual`) and that the double dual of a polyhedral cone is the cone itself
(`IsPolyhedral.dual_dual_flip`, `IsPolyhedral.dual_flip_dual`).
-/

open Function Module LinearMap
open Submodule hiding span dual
open Set

variable {𝕜 M N : Type*}

namespace PointedCone

alias sup_fg := Submodule.FG.sup

section LinearOrder

variable [Field 𝕜] [LinearOrder 𝕜] [IsOrderedRing 𝕜] [AddCommGroup M] [AddCommGroup N]
  [Module 𝕜 M] [Module 𝕜 N] {p : M →ₗ[𝕜] N →ₗ[𝕜] 𝕜} {C : PointedCone 𝕜 M} {s : Set M} {w : N}

variable (p s w) in
/-- A set whose dual cone is `span R {w} ⊔ dual p s`, see `dual_sup_span_singleton_eq_dual` -/
private noncomputable abbrev auxGenSet : Set M :=
  {x ∈ s | 0 ≤ p x w} ∪
    .image2 (fun x y ↦ p x w • y - p y w • x) {x ∈ s | 0 ≤ p x w} {y ∈ s | p y w < 0}

variable (w) in
omit [IsOrderedRing 𝕜] in
private lemma auxGenSet_finite (hs : s.Finite) :
    (auxGenSet p s w).Finite := .union (hs.sep _) <| .image2 _ (hs.sep _) (hs.sep _)

private lemma auxGenSet_subset_span :
    (auxGenSet p s w : Set M) ⊆ span 𝕜 (s : Set M) := by
  simp only [Set.union_subset_iff, Set.image2_subset_iff, Set.mem_setOf_eq, and_imp]
  refine ⟨subset_trans (fun x hx ↦ hx.1) subset_span, fun x hxS hxw y hyS hyw ↦ ?_⟩
  simpa [sub_eq_add_neg, ← neg_smul] using add_mem (smul_mem (span 𝕜 s) hxw (subset_span hyS))
    (smul_mem _ (neg_nonneg.mpr hyw.le) (subset_span hxS))

private lemma span_singleton_le_dual_auxGenSet :
    span 𝕜 {w} ≤ dual p (auxGenSet p s w) := by
  simp only [span_singleton_le_iff_mem, mem_dual, Set.mem_union, Set.mem_setOf_eq, Set.mem_image2]
  rintro z (hz | ⟨x, ⟨hxS, hxw⟩, y, ⟨hyS, hyw⟩, rfl⟩)
  · exact hz.2
  · simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg]
    rw [mul_comm]

/-- The crucial lemma in the proof that a finitely generated cone is polyhedral:
The sum of a polyhedral cone and the cone generated by a single ray is again polyhedral. -/
private lemma dual_auxGenSet (hs : s.Finite) :
    dual p (auxGenSet p s w) = span 𝕜 {w} ⊔ dual p s := by
  classical
  apply ge_antisymm
  · rw [← dual_span]
    exact sup_le span_singleton_le_dual_auxGenSet <| dual_le_dual auxGenSet_subset_span
  obtain hSw | hSw := {y ∈ s | p y w < 0}.eq_empty_or_nonempty
  · simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    exact le_sup_of_le_right <| dual_le_dual fun x hx => .inl ⟨hx, hSw _ hx⟩
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]
  replace hv2 {x y : M} (hx : x ∈ s ∧ 0 ≤ p x w) (hy : y ∈ s ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_setOf_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2
  obtain hSv | ⟨y, hy⟩ := {y ∈ s | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · simp +contextual only [Set.sep_and, Set.eq_empty_iff_forall_notMem, Set.mem_inter_iff,
      Set.mem_setOf_eq, not_and, true_and, not_lt, and_imp] at hSv
    refine ⟨0, zero_mem _, v, fun x hx => ?_, zero_add _⟩
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hx, hxw⟩
    · exact hSv x hx (lt_of_not_ge hxw)
  lift s to Finset M using hs
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' <| by
    simpa [Finset.Nonempty, Set.Nonempty] using hSw
  have hu : 0 ≤ u := by
    refine le_trans (mul_nonneg_of_nonpos_of_nonpos hy.2.2.le (inv_nonpos.mpr hy.2.1.le))
      (Finset.le_max' _ (p y v * (p y w)⁻¹) ?_)
    simp only [Finset.mem_image, Finset.mem_filter]
    exact ⟨y, ⟨hy.1, hy.2.1⟩, rfl⟩
  refine ⟨u • w, ?_, v - u • w, fun z hzS ↦ ?_, add_sub_cancel _ _⟩
  · rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)
  simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
  obtain hzw | hzw := lt_or_ge (p z w) 0
  · rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw), mul_inv_cancel_right₀ hzw.ne]
    exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
      Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
  obtain ⟨y, hy, t_eq : _ = u⟩ := Finset.mem_image.mp <|
    ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem <| by
      simpa [Finset.Nonempty, Set.Nonempty] using hSw
  rw [Finset.mem_filter] at hy
  rw [← t_eq, ← _root_.mul_le_mul_left_of_neg hy.2, ← mul_assoc]
  nth_rw 4 [mul_comm]
  rw [mul_inv_cancel_left₀ hy.2.ne]
  exact hv2 ⟨hzS, hzw⟩ hy

-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- lemma xxx {g : M →ₗ[𝕜] 𝕜} (hg : ∀ x ∈ C, 0 ≤ g x) : ∀ x ∈ C.lineal, g x = 0 := sorry

def max {C : PointedCone 𝕜 M} (f : M →ₗ[𝕜] 𝕜) {g : M →ₗ[𝕜] 𝕜}
    (hg : ∀ x ∈ C, 0 ≤ g x ∧ (g x = 0 → x = 0)) : PointedCone 𝕜 M where
  carrier := {x ∈ C | x ≠ 0 → ∀ y ∈ C, y ≠ 0 → f y / g y ≤ f x / g x}
  add_mem' := by
    simp only [ne_eq, mem_setOf_eq, map_add, and_imp]
    intro x y hxC hx hyC hy
    constructor
    · exact C.add_mem hxC hyC
    intro hxy z hzC hz0
    --specialize hx
    sorry
  zero_mem' := by simp
  smul_mem' := by
    simp only [ne_eq, mem_setOf_eq, smul_eq_zero, not_or, map_smul_of_tower, and_imp,
      Subtype.forall, Nonneg.mk_smul, Nonneg.mk_eq_zero, smul_eq_mul]
    intro _ ha _ hxC h
    constructor
    · exact C.smul_mem ha hxC
    intro ha'
    simp only [div_eq_mul_inv, mul_inv_rev] at ⊢ h
    rw [mul_comm, mul_assoc]
    nth_rw 2 [← mul_assoc]
    rw [inv_mul_cancel₀ ha', one_mul, mul_comm]
    exact h

def max_isFaceOf {C : PointedCone 𝕜 M} (f : M →ₗ[𝕜] 𝕜) {g : M →ₗ[𝕜] 𝕜} (hg : ∀ x ∈ C, 0 ≤ g x) :
    (C.max f hg).IsFaceOf C := sorry

def max_nonempty {C : PointedCone 𝕜 M} (hfg : C.FG) (f : M →ₗ[𝕜] 𝕜) {g : M →ₗ[𝕜] 𝕜}
    (hg : ∀ x ∈ C, 0 ≤ g x) : Nonempty (C.max f hg) := by
  obtain ⟨s, rfl⟩ := hfg
  by_cases hs : s.Nonempty
  · let s' := s.image fun x => f x / g x
    have hs' : s'.Nonempty := by simp [s', hs]
    have hcx := Finset.max'_mem s' hs'
    obtain ⟨x, hxs, hfx⟩ := Finset.mem_image.mp hcx
    use x
    simp only [max, ne_eq, mem_mk, AddSubmonoid.mem_mk, AddSubsemigroup.mem_mk, mem_setOf_eq]
    constructor
    · exact subset_span hxs
    intro hx0 y hy hy0
    have := Finset.le_max' s' (f y / g y) (by simp [s']; use y)
    sorry
  · simp at hs
    simp [max, hs]

lemma FG.max_of_hom_nonempty {C : PointedCone 𝕜 M} (hfg : C.FG) (f : M →ₗ[𝕜] 𝕜) (hf : PosHom f) :
    Nonempty (C.max_of_hom hf) := by
  obtain ⟨s, rfl⟩ := hfg
  by_cases hs' : s.Nonempty
  · let s' := s.image fun x => f x
    have hs' : s'.Nonempty := Finset.image_nonempty.mpr hs'
    let cx := s'.max' hs'
    have hcx := Finset.max'_mem (s.image fun x => f x) hs'
    obtain ⟨x, hxs, hfx⟩ := Finset.mem_image.mp hcx
    use x
    constructor
    · exact subset_span hxs
    rw [hfx]
    -- obtain ⟨z, hzs, hfz⟩ := Finset.mem_image.mp hcx
    -- rw [← hfz]; clear hfz
    -- have := Finset.le_max' s' (f z) (by sorry)
    -- simp [s'] at this
    intro y hy
    have := Finset.le_max' s' (f y)
    have : f y ∈ s' := by
      simp [s']
      use y
    sorry
  · simp at hs'
    use 0
    simp [hs']


lemma span_le_of_le {s : Set M} {C : PointedCone 𝕜 M} (hs : s ⊆ C) : span 𝕜 s ≤ C := by
  simpa using (Submodule.span_mono hs : span 𝕜 s ≤ span 𝕜 C)

lemma aux {s : Set M} {x : M} (hx : x ∈ span 𝕜 s) {w : N} (hw : p x w < 0) :
    ∃ y ∈ s, p y w < 0 := by
  by_contra h
  push_neg at h
  absurd hw
  push_neg
  have : s ⊆ dual p.flip {w} := fun x hx => by simp [h x hx]
  simpa using (span_mono this) hx

private lemma dual_auxGenSet'' {C : PointedCone 𝕜 M} (hC : C.FG) :
    dual p (auxGenSet p C w) = .span 𝕜 {w} ⊔ dual p C := by classical

  apply ge_antisymm
  · -- easy direction: RHS ≤ LHS
    rw [← dual_span]
    exact sup_le span_singleton_le_dual_auxGenSet <|
      dual_le_dual auxGenSet_subset_span

  -- hard direction: LHS ≤ RHS
  -- We'll reuse your proof, but we’ll take max over a finite generator finset S.
  obtain hSw | hSw := {y ∈ (C : Set M) | p y w < 0}.eq_empty_or_nonempty
  · -- If nothing in C has p _ w < 0, then every x∈C satisfies 0≤p x w, hence C ⊆ first part of auxGenSet
    simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    exact le_sup_of_le_right <|
      dual_le_dual (fun x hxC => .inl ⟨hxC, hSw _ hxC⟩)

  -- Now {y∈C | p y w < 0} is nonempty.
  -- Expand auxGenSet = A ∪ B and unpack membership in the dual.
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]

  -- The same key inequality extracted from hv2 as in your finite proof:
  replace hv2 {x y : M}
      (hx : x ∈ (C : Set M) ∧ 0 ≤ p x w)
      (hy : y ∈ (C : Set M) ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_setOf_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply,
      smul_eq_mul, sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2

  -- Next split exactly as before, but over C (not generators):
  obtain hSv | ⟨y, hy⟩ :=
      {y ∈ (C : Set M) | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · -- If no y in C is simultaneously w-negative and v-negative, then v ∈ dual p C directly (same argument)
    simp +contextual only [Set.sep_and, Set.eq_empty_iff_forall_notMem, Set.mem_inter_iff,
      Set.mem_setOf_eq, not_and, true_and, not_lt, and_imp] at hSv
    refine ⟨0, zero_mem _, v, ?_, zero_add _⟩
    -- show v ∈ dual p C
    intro x hxC
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hxC, hxw⟩
    · exact hSv x hxC (lt_of_not_ge hxw)

  ----------------------------------------------------------------
  -- Hardest branch: there exists y∈C with p y w <0 and p y v <0.
  -- Here we use FG to extract a finite generator finset S and run the max argument on S.
  ----------------------------------------------------------------

  -- Extract generators: C = span S
  obtain ⟨s, hCS⟩ := hC
  -- We will rewrite dual p C to dual p (S : Set M) using dual_span.
  have hdualC : dual p C = dual p s := by
    -- C = span S, then dual p C = dual p (span S) = dual p S
    -- adjust lemma names if needed
    simpa [hCS] using (dual_span (p := p) (s := s))

  -- A convenient lemma: any generator z ∈ S is in C
  have hS_sub : (s : Set M) ⊆ (C : Set M) := by
    intro z hzS
    -- z ∈ span S = C
    -- adjust lemma name: typically `PointedCone.subset_span` or `Submodule.subset_span`
    simpa [hCS] using (PointedCone.subset_span (R := 𝕜) (s := (s : Set M)) hzS)

  have hysw : {y ∈ s | (p y) w < 0}.Nonempty := by -- TODO: improve this code
    obtain ⟨y, hy⟩ := hSw
    simp at hy
    rw [← hCS] at hy
    obtain ⟨y, hy⟩ := aux hy.1 hy.2
    use y
    simpa using hy
      -- nonempty: we need at least one generator with p _ w < 0.
      -- This follows from hSw plus the fact C is generated by S:
      -- if all generators had 0 ≤ p _ w, then every x∈C would satisfy 0 ≤ p x w, contradicting hSw.
      -- You may already have a lemma for this; otherwise prove it with a small conic-combination argument.

  -- Define u as max of ratios over the NEGATIVE-on-w generators.
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' (by simp [hysw])

  -- Show u ≥ 0. In the finite proof this came from picking y with p y w <0 and p y v <0.
  -- We do the same, but we need a generator y0 with BOTH negatives.
  have hu : 0 ≤ u := by
    -- From ⟨y, hy⟩ with y∈C and both negatives, and v∈dual(auxGenSet),
    -- one shows there exists y0∈S with p y0 w <0 and p y0 v <0.
    -- Then ratio(y0) ≥ 0 and u, being the max, is ≥ ratio(y0).
    -- This is the only additional “generator extraction” sub-lemma you need.
    have : ∃ y0 ∈ s, p y0 w < 0 ∧ p y0 v < 0 := by

      -- Sketch:
      -- 1) write y as conic combination of generators (using hCS and hy.1 : y∈C)
      -- 2) use hv1 to show any generator with 0≤p _ w must have 0≤p _ v (since it lies in A)
      -- 3) since p y v < 0, some generator must have p _ v < 0, hence also p _ w < 0
      -- Implement using the representation lemma for `PointedCone.mem_span`.
      sorry
    rcases this with ⟨y0, hy0S, hy0w, hy0v⟩
    refine le_trans ?_ (Finset.le_max' _ (p y0 v * (p y0 w)⁻¹) ?_)
    · -- ratio(y0) ≥ 0 since both numerator and denominator are < 0
      exact mul_nonneg_of_nonpos_of_nonpos hy0v.le (inv_nonpos.mpr hy0w.le)
    · -- show ratio(y0) is in the finset image
      simp only [Finset.mem_image, Finset.mem_filter]
      exact ⟨y0, ⟨hy0S, hy0w⟩, rfl⟩

  -- Now decompose v = (u•w) + (v - u•w)
  refine ⟨u • w, ?_, v - u • w, ?_, add_sub_cancel _ _⟩
  · -- u•w ∈ span{w} with u≥0 (pointed span)
    rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)

  -- show v - u•w ∈ dual p C; rewrite to generators via hdualC
  -- (this is where FG really matters)
  -- Goal becomes: ∀ z ∈ S, 0 ≤ p z (v - u•w)
  -- after simp it’s the same split-by-sign proof as your finite-set version.
  -- Use `hdualC` to replace `dual p C` by `dual p (S:Set M)`:
  have : v - u • w ∈ dual p s := by
    intro z hzS
    -- We need: 0 ≤ p z (v - u•w)
    simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
    -- split on sign of p z w
    obtain hzw | hzw := lt_or_ge (p z w) 0
    · -- z has p z w < 0: u is a max over those ratios, identical to your finite proof
      rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw),
        mul_inv_cancel_right₀ hzw.ne]
      exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
        Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
    · -- z has 0 ≤ p z w: use the key inequality hv2 with y that attains the max
      obtain ⟨y0, hy0, H⟩ := Finset.mem_image.mp <|
        ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem (by simp [hysw])
      -- unpack hy0 : y0 ∈ S ∧ p y0 w < 0
      have hy0S : y0 ∈ (s : Set M) := by
        simpa [Finset.mem_filter] using (Finset.mem_filter.mp hy0).1
      have hy0w : p y0 w < 0 := by
        simpa [Finset.mem_filter] using (Finset.mem_filter.mp hy0).2
      -- Now apply hv2 with x=z (needs z∈C and 0≤p z w) and y=y0 (needs y0∈C and p y0 w <0)
      have hzC : z ∈ (C : Set M) := hS_sub hzS
      have hy0C : y0 ∈ (C : Set M) := hS_sub hy0S
      -- Rearrangement is exactly your last 6 lines:
      rw [← _root_.mul_le_mul_left_of_neg hy0w, ← mul_assoc]
      nth_rw 4 [mul_comm]
      rw [mul_inv_cancel_left₀ hy0w.ne]
      exact hv2 ⟨hzC, hzw⟩ ⟨hy0C, hy0w⟩

  -- Convert back to dual p C using hdualC
  simpa [hdualC] using this

private lemma dual_auxGenSet' {C : PointedCone 𝕜 M} (hC : C.FG) :
    dual p (auxGenSet p C w) = span 𝕜 {w} ⊔ dual p C := by
  classical
  apply ge_antisymm
  · rw [← dual_span]
    exact sup_le span_singleton_le_dual_auxGenSet <| dual_le_dual auxGenSet_subset_span
  obtain hSw | hSw := {y ∈ C | p y w < 0}.eq_empty_or_nonempty
  · -- simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    -- exact le_sup_of_le_right <| dual_le_dual fun x hx => .inl ⟨hx, hSw _ hx⟩
    sorry
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]
  replace hv2 {x y : M} (hx : x ∈ C ∧ 0 ≤ p x w) (hy : y ∈ C ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_setOf_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2
  obtain hSv | ⟨y, hy⟩ := {y ∈ C | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · simp +contextual only [Set.eq_empty_iff_forall_notMem, Set.mem_setOf_eq, not_and, not_lt] at hSv
    refine ⟨0, zero_mem _, v, fun x hx => ?_, zero_add _⟩
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hx, hxw⟩
    · exact hSv x hx (lt_of_not_ge hxw)
  obtain ⟨s, rfl⟩ := hC
  rw [dual_span]
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' <| by
    simp
    -- use hSw
    sorry -- simpa [Finset.Nonempty, Set.Nonempty] using hSw
  have hu : 0 ≤ u := by
    refine le_trans (mul_nonneg_of_nonpos_of_nonpos hy.2.2.le (inv_nonpos.mpr hy.2.1.le))
      (Finset.le_max' _ (p y v * (p y w)⁻¹) ?_)
    simp only [Finset.mem_image, Finset.mem_filter]
    exact ⟨y, ⟨hy.1, hy.2.1⟩, rfl⟩
  refine ⟨u • w, ?_, v - u • w, fun z hzS ↦ ?_, add_sub_cancel _ _⟩
  · rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)
  simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
  obtain hzw | hzw := lt_or_ge (p z w) 0
  · rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw), mul_inv_cancel_right₀ hzw.ne]
    exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
      Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
  obtain ⟨y, hy, t_eq : _ = u⟩ := Finset.mem_image.mp <|
    ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem <| by
      simpa [Finset.Nonempty, Set.Nonempty] using hSw
  rw [Finset.mem_filter] at hy
  rw [← t_eq, ← _root_.mul_le_mul_left_of_neg hy.2, ← mul_assoc]
  nth_rw 4 [mul_comm]
  rw [mul_inv_cancel_left₀ hy.2.ne]
  exact hv2 ⟨hzS, hzw⟩ hy

variable (p 𝕜) in
lemma auxGenSet_eq_dual_inf {C : PointedCone 𝕜 M} (w : N) :
    auxGenSet p C w = (dual p.flip {w} : Set M) ∩ C := by
  ext x
  simp only [auxGenSet, SetLike.mem_coe, Set.mem_union, Set.mem_setOf_eq, Set.mem_inter_iff,
    mem_dual, Set.mem_singleton_iff, flip_apply, forall_eq]
  constructor
  · rintro (⟨xS, px⟩ | ⟨r, hr, t, ht, rfl⟩)
    · exact ⟨px, xS⟩
    · simp_rw [map_sub, map_smul, sub_apply, smul_apply, smul_eq_mul, mul_comm, sub_self,
      le_refl, true_and, sub_eq_add_neg, ← neg_smul]
      exact C.add_mem (C.smul_mem hr.2 ht.1) <| C.smul_mem (neg_nonneg.mpr (le_of_lt ht.2)) hr.1
  · rintro ⟨xS, px⟩
    exact Or.inl ⟨px, xS⟩

lemma auxGenSet_mono (s t : Set M) (hst : s ⊆ t) : auxGenSet p s w ⊆ auxGenSet p t w := by
  -- intro x
  -- simp
  -- rintro (⟨hx, h⟩ | h)
  -- · left; exact ⟨hst hx, h⟩
  -- right
  -- obtain ⟨y, ⟨hy, hyw⟩, z, ⟨hz, hzw⟩, h⟩ := h
  -- use y
  -- constructor
  -- · exact ⟨hst hy, hyw⟩
  -- use z
  -- · exact ⟨hst hz, hzw⟩
  sorry

lemma span_auxGenSet (s : Set M) :
    span 𝕜 (auxGenSet p s w) = auxGenSet p (span 𝕜 s) w := by
  -- unfold auxGenSet
  -- rw [span_union]
  -- simp
  -- #check mem_span_set
  -- rw [span_image]
  sorry

variable (p 𝕜) in
lemma span_auxGenSet_eq_dual_inf_span (hs : s.Finite) (w : N) :
    span 𝕜 (auxGenSet p s w) = (dual p.flip {w} : Set M) ∩ span 𝕜 s := by
  simpa [← SetLike.coe_set_eq, span_auxGenSet] using auxGenSet_eq_dual_inf _ _ w

------- vvvvvvvv Experiments below

-- There is something that should follow immediately from the above, but does not because
-- the proof looses information about these details. Can we reconstruct it?

variable (p 𝕜) in
lemma span_auxGenSet_eq_dual_inf_span' (hs : s.Finite) (w : N) :
    span 𝕜 (auxGenSet p s w) = dual p.flip {w} ⊓ span 𝕜 s := by
  ext x
  simp
  unfold auxGenSet
  rw [span_union]
  rw [mem_sup]
  sorry

variable (p 𝕜) in
private lemma span_sup_dual_eq_dual_dual_inf_span {C : PointedCone 𝕜 M} (hC : C.FG) (w : N) :
    span 𝕜 {w} ⊔ dual p C = dual p (dual p.flip {w} ∩ C) := by
  have ⟨s, hs⟩ := hC
  simp [← hs, ← span_auxGenSet_eq_dual_inf_span, dual_auxGenSet]

variable (p 𝕜) in
private lemma span_sup_dual_eq_dual_dual_inf_span' {C : PointedCone 𝕜 M} (hC : C.FG) (w : N) :
    span 𝕜 {w} ⊔ dual p C = dual p (dual p.flip {w} ∩ C) := by
  simp [← auxGenSet_eq_dual_inf, ← dual_auxGenSet' hC]

variable (p 𝕜) in
private lemma span_sup_dual_eq_dual_dual_inf_span'' (s : Finset N) (t : Finset M) :
    span 𝕜 s ⊔ dual p t = dual p (dual p.flip s ∩ span 𝕜 (t : Set M)) := by classical
  induction s using Finset.induction with
  | empty => simp
  | insert w s hwr hs =>
    simp only [Finset.coe_insert, span]
    rw [span_insert, sup_assoc, sup_comm, hs, dual_insert]
    repeat rw [← Submodule.coe_inf]
    rw [inf_assoc]
    nth_rw 2 [inf_comm]
    -- now use that span R {w} is dual closed.
    sorry

variable (p) in
lemma dual_fg_inf_fgdual_dual_sup_dual' {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  sorry

------- ^^^^^^ Experiments above

/-- The union of an FG cone and a FGDual cone is FGDual. -/
lemma sup_fg_fgdual {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FGDual p) : (C ⊔ D).FGDual p
    := by classical
  obtain ⟨s, rfl⟩ := hC
  induction s using Finset.induction with
  | empty => simp [hD]
  | insert w s hws hs =>
    obtain ⟨t, ht⟩ := hs
    use (auxGenSet p t.toSet w).toFinset
    simp [span_insert, sup_assoc, ← ht]
    exact dual_auxGenSet t.finite_toSet

lemma sup_fgdual_fg {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FG) : (C ⊔ D).FGDual p
    := by rw [sup_comm]; exact sup_fg_fgdual hD hC

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of a FGDual cone and an FG submodule. -/
lemma FG.exists_fgdual_inf_submodule {C : PointedCone 𝕜 N} (hC : C.FG)
    {S : Submodule 𝕜 N} (hS : S.FG) (hCS : C ≤ S) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ D ⊓ S = C := by
  wlog hC' : C = ⊥ with h
  · specialize h p fg_bot hS bot_le rfl
    obtain ⟨D, hfgdual, hD⟩ := h
    exact ⟨_, sup_fg_fgdual hC hfgdual, by simp [← sup_inf_assoc_of_le_submodule D hCS, hD]⟩
  · obtain ⟨D, hfgdual, hD⟩ := hS.exists_fgdual_disjoint p  -- <-- submodule duality theory
    exact ⟨_, coe_fgdual_iff.mpr hfgdual, by simp [← restrictScalars_inf, inf_comm, hC', hD.eq_bot]⟩

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of its linear span with a FGDual cone. -/
lemma FG.exists_fgdual_inf_span {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ D ⊓ Submodule.span 𝕜 (M := N) C = C :=
  exists_fgdual_inf_submodule p hC (submodule_span_fg hC) Submodule.subset_span

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of a FGDual cone and an FG submodule. -/
lemma FG.exists_fgdual_inf_fg_submodule {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ ∃ S : Subspace 𝕜 N, S.FG ∧ D ⊓ S = C := by
  obtain ⟨D, hfgdual, hD⟩ := exists_fgdual_inf_span p hC
  exact ⟨D, hfgdual, Submodule.span 𝕜 C, submodule_span_fg hC, hD⟩

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone is the dual of a FGDual cone. -/
lemma FG.exists_fgdual_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.FGDual p.flip ∧ dual p D = C := by
  obtain ⟨D, hD, S, hS, rfl⟩ := exists_fgdual_inf_fg_submodule p hC
  obtain ⟨C', hfg, rfl⟩ := hD.exists_fg_dual
  use C' ⊔ dual p.flip S
  constructor
  · exact sup_fg_fgdual hfg <| fgdual_of_fg p.flip (coe_fg hS)
  · rw [dual_sup_dual_inf_dual]
    simp [Submodule.FG.dual_dual_flip _ hS] -- <-- submodule duality theory

@[deprecated FG.exists_fgdual_dual (since := "")]
alias FG.exists_fgdual_flip_dual := FG.exists_fgdual_dual

-- variable (p) [Fact p.flip.IsFaithfulPair] in
-- /-- An FG cone is the dual of a FGDual cone. -/
-- lemma FG.exists_fgdual_dual_flip {C : PointedCone 𝕜 M} (hC : C.FG) :
--     ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ dual p.flip D = C := exists_fgdual_flip_dual p.flip hC

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_dual_flip {C : PointedCone 𝕜 N} (hC : C.FG) : dual p (dual p.flip C) = C := by
  obtain ⟨D, hfgdual, rfl⟩ := exists_fgdual_dual p hC
  exact dual_dual_flip_dual (p := p) D

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_flip_dual {C : PointedCone 𝕜 M} (hC : C.FG) : dual p.flip (dual p C) = C :=
  FG.dual_dual_flip p.flip hC

variable (p) [Fact p.SeparatingLeft] in
lemma FG.isDualClosed {C : PointedCone 𝕜 M} (hC : C.FG) : C.DualClosed p
    := FG.dual_flip_dual p hC

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_dual_flip_eq_span (s : Finset N) : dual p (dual p.flip s) = span 𝕜 s := by
  nth_rw 2 [← dual_span]
  exact dual_dual_flip p (fg_span s.finite_toSet)

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_flip_dual_eq_span (s : Finset M) : dual p.flip (dual p s) = span 𝕜 s :=
    dual_dual_flip_eq_span p.flip s

variable [Fact p.SeparatingLeft] in
lemma FG.dual_inj {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG)
    (h : dual p C = dual p D) : C = D := by
  have h := congrArg (dual p.flip) <| congrArg SetLike.coe h
  simpa [dual_flip_dual _ hC, dual_flip_dual _ hD] using h

-- variable [Fact p.IsFaithfulPair] in
-- lemma FG.dual_flip_inj {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FG)
--     (h : dual p.flip C = dual p.flip D) : C = D := dual_inj hC hD h

variable [Fact p.SeparatingLeft] in
@[simp] lemma FG.dual_inj_iff {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p C = dual p D ↔ C = D := ⟨dual_inj hC hD, by simp +contextual⟩

-- variable [Fact p.IsFaithfulPair] in
-- @[simp] lemma FG.dual_flip_inj_iff {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FG) :
--     dual p.flip C = dual p.flip D ↔ C = D := dual_inj_iff hC hD

variable [Fact p.SeparatingRight] in
/-- The dual of a FGDual cone is FG. -/
lemma FGDual.dual_fg {C : PointedCone 𝕜 M} (hC : C.FGDual p.flip) : (dual p C).FG := by
  obtain ⟨D, hfg, rfl⟩ := exists_fg_dual hC
  rw [FG.dual_dual_flip p hfg]
  exact hfg

-- variable [Fact p.flip.IsFaithfulPair] in
-- /-- The dual of a FGDual cone is FG. -/
-- lemma FGDual.dual_flip_fg {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
--    (dual p.flip C).FG := dual_fg hC

/- TODO: For submodules we have an alternative proof that avoids `p.SeparatingRight`.
  Can we have this here as well? -/
variable [Fact p.SeparatingRight] in
lemma FGDual.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M}
    (hC : C.FGDual p.flip) (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← FGDual.dual_flip_dual hC, ← FGDual.dual_flip_dual hD,
    ← Submodule.coe_inf, ← dual_sup_dual_inf_dual]
  exact FG.dual_dual_flip p <| sup_fg (FGDual.dual_fg hC) (FGDual.dual_fg hD)


section Module.Finite

variable [Module.Finite 𝕜 N]

variable (p) [Fact p.SeparatingRight] in
/-- A finite dimensional FG cone is also FGDual. -/
lemma FG.fgdual {C : PointedCone 𝕜 N} (hC : C.FG) : C.FGDual p := by
  obtain ⟨D, hfgdual, rfl⟩ := exists_fgdual_inf_submodule p hC Finite.fg_top (by simp)
  simpa using hfgdual

/-- A finite dimensional FGDual cone is also FG. -/
lemma FGDual.fg {C : PointedCone 𝕜 N} (hC : C.FGDual p) : C.FG := by
  obtain ⟨D, hfg, rfl⟩ := hC.to_id.exists_fg_dual
  exact FGDual.dual_fg <| FG.fgdual _ hfg

variable [Fact p.SeparatingRight] in
/-- A cone in finite dimensional space is FG if and only if it is FGDual. -/
lemma fg_iff_fgdual {C : PointedCone 𝕜 N} : C.FG ↔ C.FGDual p := ⟨FG.fgdual p, FGDual.fg⟩

-- variable [Module.Finite 𝕜 N] in
-- variable [Fact p.IsFaithfulPair] in
-- /-- A finite dimensional cone is FG if and only if it is FGDual. -/
-- lemma fg_iff_fgdual {C : PointedCone 𝕜 N} : C.FGDual p ↔ C.FG := ⟨FGDual.fg, FG.fgdual p⟩

variable (p) in
/-- In finite dimensional space, the dual of and FG cone is itself FG. -/
lemma FG.dual_fg {C : PointedCone 𝕜 M} (hC : C.FG) : (dual p C).FG := by
  rw [dual_id_map]
  exact FGDual.dual_fg <| FG.fgdual _ <| FG.map (LinearMap.restrictScalars _ p) hC

/-- In finite dimensional space, the dual of and FGDual cone is itself FGDual. -/
lemma FGDual.dual_fgdual {C : PointedCone 𝕜 N} (hC : C.FGDual p) : (dual p.flip C).FGDual p.flip
  := FG.dual_fgdual p.flip (FGDual.fg hC)

-- TODO: implement pairing lemmas that allow inference of `Module.Finite 𝕜 M`.
--  We should preferably assume `Module.Finite 𝕜 N`
omit [Module.Finite 𝕜 N] in
variable (p) [Module.Finite 𝕜 M] [Fact p.IsFaithfulPair] in
lemma FG.exists_fg_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ dual p D = C := by
  use dual p.flip C
  exact ⟨FG.dual_fg p.flip hC, FG.dual_dual_flip p hC⟩

end Module.Finite

/- NOTE: the below theorem is the basis for generalizations to certain rings. If R is an
  ordered ring that embeds discretelety in its fraction field (essentually ℤ), then
  intersections of FG cones stay FG (Gordan's lemma).
  recall at https://chatgpt.com/c/691078e5-7f50-8326-8f04-98ae7185da74 -/

/-- The intersection of two FG cones is an FG cone. -/
lemma inf_fg {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) : (C ⊓ D).FG := by
  wlog _ : Module.Finite 𝕜 M with h
  · let CD : Submodule 𝕜 M := .span 𝕜 (C ⊔ D : PointedCone 𝕜 M)
    have hCle : C ≤ CD := le_submodule_span_of_le le_sup_left
    have hDle : D ≤ CD := le_submodule_span_of_le le_sup_right
    specialize h (restrict_fg_of_fg_le hCle hC) (restrict_fg_of_fg_le hDle hD)
      (Finite.iff_fg.mpr <| submodule_span_fg <| sup_fg hC hD)
    rw [← restrict_inf] at h
    exact fg_of_restrict_le (le_submodule_span_of_le inf_le_sup) h
  · exact FGDual.fg <| inf_fgdual (FG.fgdual .id hC) (FG.fgdual .id hD) -- inf_fg' hC hD

/- TODO: the equivalent of the below statement with FGDual instead of FG can likely be proven
  under rather weak assumptions (Noetherian or so). -/

/-- The intersection of an FG cone with an arbitrary submodule is FG. -/
lemma inf_fg_submodule {C : PointedCone 𝕜 M} (hC : C.FG) (S : Submodule 𝕜 M) : (C ⊓ S).FG := by
  rw [left_eq_inf.mpr (le_submodule_span C), inf_assoc, ← coe_inf]
  exact inf_fg hC <| coe_fg <| FG.of_le (submodule_span_fg hC) inf_le_left

lemma inf_submodule_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG)
    : (S ⊓ C : PointedCone 𝕜 M).FG := by rw [inf_comm]; exact inf_fg_submodule hC S

/-- The restriction of an FG cone to an arbitrary submodule is FG. -/
lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
    (C.restrict S).FG := by
  rw [restrict_fg_iff_inf_fg]; exact inf_submodule_fg S hC

/-- The intersection of an FG cone and a FGDual cone is FG. -/
lemma inf_fg_fgdual {C D : PointedCone 𝕜 N}
    (hC : C.FG) (hD : D.FGDual p) : (C ⊓ D).FG := by
  obtain ⟨C', hCfgdual, rfl⟩ := FG.exists_fgdual_dual .id hC
  obtain ⟨D', hDfg, rfl⟩ := FGDual.exists_fg_dual hD.to_id
  rw [← dual_sup_dual_inf_dual]
  exact FGDual.dual_fg (sup_fgdual_fg hCfgdual hDfg)

/-- The intersection of a FGDual cone and an FG cone is FG. -/
lemma inf_fgdual_fg {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FG) : (C ⊓ D).FG
    := by rw [inf_comm]; exact inf_fg_fgdual hD hC

variable (p) in
lemma exists_fg_sup_dual (s : Finset M) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p s = dual p s := by
  obtain ⟨S, hS⟩ := Submodule.exists_isCompl (dual p s).lineal
  use (dual p s) ⊓ S
  constructor
  · rw [dual_span_lineal_dual] at hS
    have h := CoFG.fg_of_isCompl hS (dual_finset_cofg p s)
    exact inf_fgdual_fg (fgdual_of_finset p s) (coe_fg h) -- h instead if coe_fg h would work
  · rw [← dual_span_lineal_dual]
    exact inf_sup_lineal hS.codisjoint

variable (p) in
lemma FG.exists_fg_sup_dual {C : PointedCone 𝕜 M} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p C = dual p C := by
  obtain ⟨s, rfl⟩ := hC
  simpa using PointedCone.exists_fg_sup_dual p s

lemma FGDual.exists_fg_sup_lineal {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ C.lineal = C := by
  obtain ⟨s, rfl⟩ := hC
  rw [dual_span_lineal_dual]
  exact PointedCone.exists_fg_sup_dual p s

/-- The sum of FGDual cones is FGDual. -/
lemma sup_fgdual {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FGDual p) :
    (C ⊔ D).FGDual p := by
  obtain ⟨C', hCfg, hC'⟩ := hC.exists_fg_sup_lineal
  obtain ⟨D', hDfg, hD'⟩ := hD.exists_fg_sup_lineal
  rw [← hC', ← hD', sup_assoc]
  nth_rw 2 [sup_comm]
  rw [sup_assoc, ← sup_assoc]
  refine sup_fg_fgdual (sup_fg hCfg hDfg) ?_
  rw [← coe_sup, coe_fgdual_iff]
  exact Submodule.sup_fgdual hD.lineal_fgdual _  -- <-- submodule duality theory

-- NOTE: Assumption `p.SeparatingLeft` cannot be avoided, see analogous proof for submodules. -/
variable (p) [Fact p.SeparatingLeft] in
lemma FG.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← FG.dual_flip_dual p hC, ← FG.dual_flip_dual p hD,
    ← Submodule.coe_inf, ← dual_sup_dual_inf_dual]
  exact FGDual.dual_dual_flip <| sup_fgdual (FG.dual_fgdual p hC) (FG.dual_fgdual p hD)

-- variable [Fact p.flip.IsFaithfulPair] in
-- lemma inf_fgdual_submodule {C : PointedCone 𝕜 N} {S : Submodule 𝕜 N}
--     (hC : C.FGDual p) (hS : S.FG) :
--     (C ⊓ S).FG := by
--   obtain ⟨D, hfg, hD⟩ := hC.exists_fg_sup_lineal
--   rw [← hD]
--   rw [← sup_inf_assoc_of_le_submodule]
--   refine sup_fg hfg ?_
--   rw [← coe_inf]
--   exact coe_fg (inf_fg_right _ hS)
--   --rw []
--   sorry

/- TODO: For submodules we have an alternative proof that avoids `p.Nondegenerate`.
  Can we have this here as well? -/
variable (p) [Fact p.Nondegenerate] in
lemma dual_fg_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨C', hC', rfl⟩ := FG.exists_fgdual_dual p.flip hC
  obtain ⟨D', hD', rfl⟩ := FGDual.exists_fg_dual hD
  rw [← Submodule.coe_inf]
  rw [← dual_sup_dual_inf_dual]
  rw [flip_flip] at hC'
  rw [FGDual.dual_dual_flip <| sup_fgdual_fg hC' hD']
  rw [FGDual.dual_dual_flip hC']
  rw [FG.dual_dual_flip p hD']

-- -- TODO: Should not need to rely on `p.flip.IsFaithfulPair`. Or maybe actually it should?
-- variable (p) [Fact p.IsFaithfulPair] [Fact p.flip.IsFaithfulPair] in
-- lemma dual_fg_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
--     (hD : D.FGDual p.flip) : dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
--   obtain ⟨C', hC', rfl⟩ := FG.exists_fgdual_dual p.flip hC
--   obtain ⟨D', hD', rfl⟩ := FGDual.exists_fg_dual hD
--   rw [← dual_sup_dual_inf_dual]
--   rw [flip_flip] at hC'
--   rw [FGDual.dual_dual_flip <| sup_fgdual_fg hC' hD']
--   rw [FGDual.dual_dual_flip hC']
--   rw [FG.dual_dual_flip p hD']

lemma dual_fg_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.FG) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

lemma dual_fgdual_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.FGDual p.flip) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

-- TODO: this should *not* rely on `p.flip.IsFaithfulPair`
-- variable (p)[Fact p.flip.IsFaithfulPair] in -- [Fact p.IsFaithfulPair]
-- lemma dual_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
--     dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
--   simp
--   exact FG.dual_inf_dual_sup_dual p hC hD
--   -- obtain ⟨D', hfgdual, S, hfg, rfl⟩ := FG.exists_fgdual_inf_fg_submodule p.flip hD
--   -- rw [inf_comm, inf_assoc, inf_comm]
--   -- rw [dual_fg_inf_fgdual_dual_sup_dual _ (inf_fg (coe_fg hfg) hC) hfgdual]
--   -- rw [inf_comm]
--   -- rw [dual_fg_inf_submodule_dual_sup_dual hC hfg]
--   -- rw [sup_assoc]; nth_rw 2 [sup_comm]
--   -- rw [← dual_fgdual_inf_submodule_dual_sup_dual hfgdual hfg]

-- lemma foo (C : PointedCone 𝕜 M) (S : Submodule 𝕜 N) :
--   ∃ T : Submodule 𝕜 M, (dual p C).restrict S = dual (Dual.eval 𝕜 T) (C.restrict T) := by sorry

-- private lemma inf_submodule_fgdual (S : Submodule 𝕜 N) {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
--     (C.restrict S).FGDual p := by
--   sorry


-- ----------------- ^^^^^^^ everything up there is proven vvvvv down there is work

-- lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog hCS : C ≤ S with h
--   · let S' : Submodule 𝕜 M := .span 𝕜 C
--     have hCS : C ≤ S' := le_submodule_span_self C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (.restrict S' C)
--       (restrict_fg_of_fg_le hCS hC)
--     sorry -- restrict_mono
--   · exact restrict_fg_of_fg_le hCS hC

-- lemma FG.restrict_fg2 (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog _ : Module.Finite 𝕜 M with h
--   · let S' := Submodule.span 𝕜 (M := M) C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (restrict S' C) _ _
--     · exact restrict_fg_of_fg_le (le_submodule_span_self C) hC
--     · exact Finite.iff_fg.mpr (span_fg hC)
--     · have hfgS : (restrict S' S).FG := sorry
--       have hfgC : (restrict S' C).FG := sorry
--       sorry
--   · exact restrict_fg' S hC

lemma FGDual.exists_fg_sup_submodule {C : PointedCone 𝕜 N} (hC : C.FGDual p)
    {S : Submodule 𝕜 N} (hS : S.FGDual p) (hCS : S ≤ C) :
      ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ S = C := by
  sorry

lemma FGDual.is_dual_finite_inf_span''''' {C : PointedCone 𝕜 N} (hC : C.FG)
    (S : Submodule 𝕜 N) (hFG : S.FG) (hS : C ≤ S) : ∃ s : Set M, s.Finite ∧ dual p s ⊓ S = C := by
  sorry

lemma FGDual.is_dual_finite_inf_span'''' {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p s ⊓ Submodule.span (M := N) 𝕜 C = C := by
  sorry

lemma FG.dual_span_finite_sup_lineal (hC : C.FG) :
    ∃ s : Set N, s.Finite ∧ dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma FG.dual_span_finset_sup_lineal (hC : C.FG) :
    ∃ s : Finset N, dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma FGDual.dual_sup_lineal (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ dual p C = D ⊔ (dual p C).lineal := by
  sorry

lemma FGDual.is_sup_fgdual_fg (hC : C.FGDual p.flip) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ D ⊔ C.lineal = C := by
  sorry

lemma FGDual.lineal_fgdual' (hC : C.FGDual p.flip) : C.lineal.FGDual p.flip := by
  sorry

lemma FG.is_dual_dual_of_finite (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p.flip (dual p s) = C := by
  sorry

lemma FG.is_dual_dual_of_fgdual (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ dual p.flip D = C := by
  sorry

end LinearOrder

end PointedCone
