/-
Copyright (c) 2025 Justus Springer, Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Justus Springer, Martin Winter
-/
import Mathlib.LinearAlgebra.Dual.Defs
import Mathlib.LinearAlgebra.PerfectPairing.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.SesquilinearForm.Basic

import Polyhedral.Mathlib.Algebra.Module.Submodule.DualClosed
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.FGDual

/-!
# Polyhedral cones

Given a bilinear pairing `p` between two `R`-modules `M` and `N`, we define
polyhedral cones to be pointed cones in `N` that are the dual of a finite set
in `M` (this means they are the intersection of finitely many halfspaces).

The main statement is that if both `M` and `N` are finite and the pairing is injective
in both arguments, then polyhedral cones are precisely the finitely generated cones, see
`isPolyhedral_iff_fg`. Moreover, we obtain that the dual of a polyhedral cone is again polyhedral
(`IsPolyhedral.dual`) and that the double dual of a polyhedral cone is the cone itself
(`IsPolyhedral.dual_dual_flip`, `IsPolyhedral.dual_flip_dual`).
-/

open Function Module LinearMap
open Submodule hiding span dual
open Set

variable {𝕜 M N : Type*}

namespace PointedCone

alias sup_fg := Submodule.FG.sup

section LinearOrder

variable [Field 𝕜] [LinearOrder 𝕜] [IsOrderedRing 𝕜] [AddCommGroup M] [AddCommGroup N]
  [Module 𝕜 M] [Module 𝕜 N] {p : M →ₗ[𝕜] N →ₗ[𝕜] 𝕜} {C : PointedCone 𝕜 M} {s : Set M} {w : N}

variable (p s w) in
/-- A set whose dual cone is `span R {w} ⊔ dual p s`, see `dual_sup_span_singleton_eq_dual` -/
private noncomputable abbrev auxGenSet : Set M :=
  {x ∈ s | 0 ≤ p x w} ∪
    .image2 (fun x y ↦ p x w • y - p y w • x) {x ∈ s | 0 ≤ p x w} {y ∈ s | p y w < 0}

variable (w) in
omit [IsOrderedRing 𝕜] in
private lemma auxGenSet_finite (hs : s.Finite) :
    (auxGenSet p s w).Finite := .union (hs.sep _) <| .image2 _ (hs.sep _) (hs.sep _)

private lemma auxGenSet_subset_span :
    (auxGenSet p s w : Set M) ⊆ span 𝕜 (s : Set M) := by
  simp only [Set.union_subset_iff, Set.image2_subset_iff, Set.mem_setOf_eq, and_imp]
  refine ⟨subset_trans (fun x hx ↦ hx.1) subset_span, fun x hxS hxw y hyS hyw ↦ ?_⟩
  -- simpa [sub_eq_add_neg] using add_mem (smul_mem (span 𝕜 s) ⟨p x w, hxw⟩ (subset_span hyS))
  --   (smul_mem _ ⟨-p y w, neg_nonneg.mpr hyw.le⟩ (subset_span hxS))
  sorry -- this code broke on mathlib/Lean update ...

private lemma span_singleton_le_dual_auxGenSet :
    span 𝕜 {w} ≤ dual p (auxGenSet p s w) := by
  simp only [span_singleton_le_iff_mem, mem_dual, Set.mem_union, Set.mem_setOf_eq, Set.mem_image2]
  rintro z (hz | ⟨x, ⟨hxS, hxw⟩, y, ⟨hyS, hyw⟩, rfl⟩)
  · exact hz.2
  · simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg]
    rw [mul_comm]

/-- The crucial lemma in the proof that a finitely generated cone is polyhedral:
The sum of a polyhedral cone and the cone generated by a single ray is again polyhedral. -/
private lemma dual_auxGenSet (hs : s.Finite) :
    dual p (auxGenSet p s w) = span 𝕜 {w} ⊔ dual p s := by
  classical
  apply ge_antisymm
  · rw [← dual_span]
    exact sup_le span_singleton_le_dual_auxGenSet <| dual_le_dual auxGenSet_subset_span
  obtain hSw | hSw := {y ∈ s | p y w < 0}.eq_empty_or_nonempty
  · simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    exact le_sup_of_le_right <| dual_le_dual fun x hx => .inl ⟨hx, hSw _ hx⟩
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]
  replace hv2 {x y : M} (hx : x ∈ s ∧ 0 ≤ p x w) (hy : y ∈ s ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_setOf_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2
  obtain hSv | ⟨y, hy⟩ := {y ∈ s | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · simp +contextual only [Set.sep_and, Set.eq_empty_iff_forall_notMem, Set.mem_inter_iff,
      Set.mem_setOf_eq, not_and, true_and, not_lt, and_imp] at hSv
    refine ⟨0, zero_mem _, v, fun x hx => ?_, zero_add _⟩
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hx, hxw⟩
    · exact hSv x hx (lt_of_not_ge hxw)
  lift s to Finset M using hs
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' <| by
    simpa [Finset.Nonempty, Set.Nonempty] using hSw.image _
  have hu : 0 ≤ u := by
    refine le_trans (mul_nonneg_of_nonpos_of_nonpos hy.2.2.le (inv_nonpos.mpr hy.2.1.le))
      (Finset.le_max' _ (p y v * (p y w)⁻¹) ?_)
    simp only [Finset.mem_image, Finset.mem_filter]
    exact ⟨y, ⟨hy.1, hy.2.1⟩, rfl⟩
  refine ⟨u • w, ?_, v - u • w, fun z hzS ↦ ?_, add_sub_cancel _ _⟩
  · rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)
  simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
  obtain hzw | hzw := lt_or_ge (p z w) 0
  · rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw), mul_inv_cancel_right₀ hzw.ne]
    exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
      Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
  obtain ⟨y, hy, t_eq : _ = u⟩ := Finset.mem_image.mp <|
    ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem <| by
      simpa [Finset.Nonempty, Set.Nonempty] using hSw.image _
  rw [Finset.mem_filter] at hy
  rw [← t_eq, ← _root_.mul_le_mul_left_of_neg hy.2, ← mul_assoc]
  nth_rw 4 [mul_comm]
  rw [mul_inv_cancel_left₀ hy.2.ne]
  exact hv2 ⟨hzS, hzw⟩ hy

------- vvvvvvvv Experiments below

-- There is something that should follow immediately from the above, but does not because
-- the proof looses information about these details. Can we reconstruct it?

variable (p 𝕜) in
lemma span_auxGenSet_eq_dual_inf_span (hs : s.Finite) (w : N) :
    span 𝕜 (auxGenSet p s w) = dual p.flip {w} ⊓ span 𝕜 s := by
  ext x
  simp
  unfold auxGenSet
  rw [span_union]
  rw [mem_sup]
  sorry

variable (p 𝕜) in
private lemma span_sup_dual_eq_dual_dual_inf_span
    (hs : s.Finite) (w : N) :
    span 𝕜 {w} ⊔ dual p s = dual p (dual p.flip {w} ∩ span 𝕜 s) := by
  rw [← Submodule.coe_inf]
  rw [← span_auxGenSet_eq_dual_inf_span 𝕜 p hs w]
  rw [dual_span, Eq.comm]
  exact dual_auxGenSet hs

variable (p 𝕜) in
private lemma span_sup_dual_eq_dual_dual_inf_span' (s : Finset N) (t : Finset M) :
    span 𝕜 s ⊔ dual p t = dual p (dual p.flip s ∩ span 𝕜 (t : Set M)) := by classical
  induction s using Finset.induction with
  | empty => simp
  | insert w s hwr hs =>
    simp
    unfold span at *
    rw [span_insert, sup_assoc, sup_comm]
    rw [hs]
    rw [dual_insert]
    repeat rw [← Submodule.coe_inf]
    rw [inf_assoc]
    nth_rw 2 [inf_comm]
    -- now use that span R {w} is dual closed.
    sorry

variable (p) in
lemma dual_fg_inf_fgdual_dual_sup_dual' {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  sorry

------- ^^^^^^ Experiments above

/-- The union of an FG cone and a FGDual cone is FGDual. -/
lemma sup_fg_fgdual {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FGDual p) : (C ⊔ D).FGDual p
    := by classical
  obtain ⟨s, rfl⟩ := hC
  induction s using Finset.induction with
  | empty => simp [hD]
  | insert w s hws hs =>
    obtain ⟨t, ht⟩ := hs
    use (auxGenSet p t.toSet w).toFinset
    simp [span_insert, sup_assoc, ← ht]
    exact dual_auxGenSet t.finite_toSet

lemma sup_fgdual_fg {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FG) : (C ⊔ D).FGDual p
    := by rw [sup_comm]; exact sup_fg_fgdual hD hC

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of a FGDual cone and an FG submodule. -/
lemma FG.exists_fgdual_inf_submodule {C : PointedCone 𝕜 N} (hC : C.FG)
    {S : Submodule 𝕜 N} (hS : S.FG) (hCS : C ≤ S) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ D ⊓ S = C := by
  wlog hC' : C = ⊥ with h
  · specialize h p fg_bot hS bot_le rfl
    obtain ⟨D, hfgdual, hD⟩ := h
    exact ⟨_, sup_fg_fgdual hC hfgdual, by simp [← sup_inf_assoc_of_le_submodule D hCS, hD]⟩
  · obtain ⟨D, hfgdual, hD⟩ := hS.exists_fgdual_disjoint p
    exact ⟨_, coe_fgdual_iff.mpr hfgdual, by simp [← restrictScalars_inf, inf_comm, hC', hD.eq_bot]⟩

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of its linear span with a FGDual cone. -/
lemma FG.exists_fgdual_inf_span {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ D ⊓ Submodule.span 𝕜 (M := N) C = C :=
  exists_fgdual_inf_submodule p hC (submodule_span_fg hC) Submodule.subset_span

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of a FGDual cone and an FG submodule. -/
lemma FG.exists_fgdual_inf_fg_submodule {C : PointedCone 𝕜 N} (hC : C.FG) :
      ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ ∃ S : Subspace 𝕜 N, S.FG ∧ D ⊓ S = C := by
  obtain ⟨D, hfgdual, hD⟩ := exists_fgdual_inf_span p hC
  exact ⟨D, hfgdual, Submodule.span 𝕜 C, submodule_span_fg hC, hD⟩

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone is the dual of a FGDual cone. -/
lemma FG.exists_fgdual_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.FGDual p.flip ∧ dual p D = C := by
  obtain ⟨D, hD, S, hS, rfl⟩ := exists_fgdual_inf_fg_submodule p hC
  obtain ⟨C', hfg, rfl⟩ := hD.exists_fg_dual
  use C' ⊔ dual p.flip S
  constructor
  · exact sup_fg_fgdual hfg <| fgdual_of_fg p.flip (coe_fg hS)
  · rw [dual_sup_dual_inf_dual]
    simp [Submodule.FG.dual_dual_flip _ hS]

@[deprecated FG.exists_fgdual_dual (since := "")]
alias FG.exists_fgdual_flip_dual := FG.exists_fgdual_dual

-- variable (p) [Fact p.flip.IsFaithfulPair] in
-- /-- An FG cone is the dual of a FGDual cone. -/
-- lemma FG.exists_fgdual_dual_flip {C : PointedCone 𝕜 M} (hC : C.FG) :
--     ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ dual p.flip D = C := exists_fgdual_flip_dual p.flip hC

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_dual_flip {C : PointedCone 𝕜 N} (hC : C.FG) : dual p (dual p.flip C) = C := by
  obtain ⟨D, hfgdual, rfl⟩ := exists_fgdual_dual p hC
  exact dual_dual_flip_dual (p := p) D

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_flip_dual {C : PointedCone 𝕜 M} (hC : C.FG) : dual p.flip (dual p C) = C :=
  FG.dual_dual_flip p.flip hC

variable (p) [Fact p.flip.IsFaithfulPair] in
lemma FG.isDualClosed {C : PointedCone 𝕜 M} (hC : C.FG) : C.DualClosed p
    := FG.dual_flip_dual p hC

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_dual_flip_eq_span (s : Finset N) : dual p (dual p.flip s) = span 𝕜 s := by
  nth_rw 2 [← dual_span]
  exact dual_dual_flip p (fg_span s.finite_toSet)

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_flip_dual_eq_span (s : Finset M) : dual p.flip (dual p s) = span 𝕜 s :=
    dual_dual_flip_eq_span p.flip s

variable [Fact p.SeparatingLeft] in
lemma FG.dual_inj {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG)
    (h : dual p C = dual p D) : C = D := by
  have h := congrArg (dual p.flip) <| congrArg SetLike.coe h
  simpa [dual_flip_dual _ hC, dual_flip_dual _ hD] using h

-- variable [Fact p.IsFaithfulPair] in
-- lemma FG.dual_flip_inj {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FG)
--     (h : dual p.flip C = dual p.flip D) : C = D := dual_inj hC hD h

variable [Fact p.SeparatingLeft] in
@[simp] lemma FG.dual_inj_iff {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p C = dual p D ↔ C = D := ⟨dual_inj hC hD, by simp +contextual⟩

-- variable [Fact p.IsFaithfulPair] in
-- @[simp] lemma FG.dual_flip_inj_iff {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.FG) :
--     dual p.flip C = dual p.flip D ↔ C = D := dual_inj_iff hC hD

variable [Fact p.SeparatingRight] in
/-- The dual of a FGDual cone is FG. -/
lemma FGDual.dual_fg {C : PointedCone 𝕜 M} (hC : C.FGDual p.flip) : (dual p C).FG := by
  obtain ⟨D, hfg, rfl⟩ := exists_fg_dual hC
  rw [FG.dual_dual_flip p hfg]
  exact hfg

-- variable [Fact p.flip.IsFaithfulPair] in
-- /-- The dual of a FGDual cone is FG. -/
-- lemma FGDual.dual_flip_fg {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
--    (dual p.flip C).FG := dual_fg hC

/- TODO: For submodules we have an alternative proof that avoids `p.SeparatingRight`.
  Can we have this here as well? -/
variable [Fact p.SeparatingRight] in
lemma FGDual.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M}
    (hC : C.FGDual p.flip) (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← FGDual.dual_flip_dual hC, ← FGDual.dual_flip_dual hD,
    ← Submodule.coe_inf, ← dual_sup_dual_inf_dual]
  exact FG.dual_dual_flip p <| sup_fg (FGDual.dual_fg hC) (FGDual.dual_fg hD)


section Module.Finite

variable [Module.Finite 𝕜 N]

variable (p) [Fact p.SeparatingRight] in
/-- A finite dimensional FG cone is also FGDual. -/
lemma FG.fgdual {C : PointedCone 𝕜 N} (hC : C.FG) : C.FGDual p := by
  obtain ⟨D, hfgdual, rfl⟩ := exists_fgdual_inf_submodule p hC Finite.fg_top (by simp)
  simpa using hfgdual

/-- A finite dimensional FGDual cone is also FG. -/
lemma FGDual.fg {C : PointedCone 𝕜 N} (hC : C.FGDual p) : C.FG := by
  obtain ⟨D, hfg, rfl⟩ := hC.to_id.exists_fg_dual
  exact FGDual.dual_fg <| FG.fgdual _ hfg

variable [Fact p.SeparatingRight] in
/-- A cone in finite dimensional space is FG if and only if it is FGDual. -/
lemma fg_iff_fgdual {C : PointedCone 𝕜 N} : C.FG ↔ C.FGDual p := ⟨FG.fgdual p, FGDual.fg⟩

-- variable [Module.Finite 𝕜 N] in
-- variable [Fact p.IsFaithfulPair] in
-- /-- A finite dimensional cone is FG if and only if it is FGDual. -/
-- lemma fg_iff_fgdual {C : PointedCone 𝕜 N} : C.FGDual p ↔ C.FG := ⟨FGDual.fg, FG.fgdual p⟩

variable (p) in
/-- In finite dimensional space, the dual of and FG cone is itself FG. -/
lemma FG.dual_fg {C : PointedCone 𝕜 M} (hC : C.FG) : (dual p C).FG := by
  rw [dual_id_map]
  exact FGDual.dual_fg <| FG.fgdual _ <| FG.map (LinearMap.restrictScalars _ p) hC

/-- In finite dimensional space, the dual of and FGDual cone is itself FGDual. -/
lemma FGDual.dual_fgdual {C : PointedCone 𝕜 N} (hC : C.FGDual p) : (dual p.flip C).FGDual p.flip
  := FG.dual_fgdual p.flip (FGDual.fg hC)

-- TODO: implement pairing lemmas that allow inference of `Module.Finite 𝕜 M`.
--  We should preferably assume `Module.Finite 𝕜 N`
omit [Module.Finite 𝕜 N] in
variable (p) [Module.Finite 𝕜 M] [Fact p.IsFaithfulPair] in
lemma FG.exists_fg_dual {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ dual p D = C := by
  use dual p.flip C
  exact ⟨FG.dual_fg p.flip hC, FG.dual_dual_flip p hC⟩

end Module.Finite

/- NOTE: the below theorem is the basis for generalizations to certain rings. If R is an
  ordered ring that embeds discretelety in its fraction field (essentually ℤ), then
  intersections of FG cones stay FG (Gordan's lemma).
  recall at https://chatgpt.com/c/691078e5-7f50-8326-8f04-98ae7185da74 -/

/-- The intersection of two FG cones is an FG cone. -/
lemma inf_fg {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) : (C ⊓ D).FG := by
  wlog _ : Module.Finite 𝕜 M with h
  · let CD : Submodule 𝕜 M := .span 𝕜 (C ⊔ D : PointedCone 𝕜 M)
    have hCle : C ≤ CD := le_submodule_span_of_le le_sup_left
    have hDle : D ≤ CD := le_submodule_span_of_le le_sup_right
    specialize h (restrict_fg_of_fg_le hCle hC) (restrict_fg_of_fg_le hDle hD)
      (Finite.iff_fg.mpr <| submodule_span_fg <| sup_fg hC hD)
    rw [← restrict_inf] at h
    exact fg_of_restrict_le (le_submodule_span_of_le inf_le_sup) h
  · exact FGDual.fg <| inf_fgdual (FG.fgdual .id hC) (FG.fgdual .id hD) -- inf_fg' hC hD

/- TODO: the equivalent of the below statement with FGDual instead of FG can likely be proven
  under rather weak assumptions (Noetherian or so). -/

/-- The intersection of an FG cone with an arbitrary submodule is FG. -/
lemma inf_fg_submodule {C : PointedCone 𝕜 M} (hC : C.FG) (S : Submodule 𝕜 M) : (C ⊓ S).FG := by
  rw [left_eq_inf.mpr (le_submodule_span C), inf_assoc, ← coe_inf]
  exact inf_fg hC <| coe_fg <| inf_fg_left (submodule_span_fg hC) S

lemma inf_submodule_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG)
    : (S ⊓ C : PointedCone 𝕜 M).FG := by rw [inf_comm]; exact inf_fg_submodule hC S

/-- The restriction of an FG cone to an arbitrary submodule is FG. -/
lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
    (C.restrict S).FG := by
  rw [restrict_fg_iff_inf_fg]; exact inf_submodule_fg S hC

/-- The intersection of an FG cone and a FGDual cone is FG. -/
lemma inf_fg_fgdual {C D : PointedCone 𝕜 N}
    (hC : C.FG) (hD : D.FGDual p) : (C ⊓ D).FG := by
  obtain ⟨C', hCfgdual, rfl⟩ := FG.exists_fgdual_dual .id hC
  obtain ⟨D', hDfg, rfl⟩ := FGDual.exists_fg_dual hD.to_id
  rw [← dual_sup_dual_inf_dual]
  exact FGDual.dual_fg (sup_fgdual_fg hCfgdual hDfg)

/-- The intersection of a FGDual cone and an FG cone is FG. -/
lemma inf_fgdual_fg {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FG) : (C ⊓ D).FG
    := by rw [inf_comm]; exact inf_fg_fgdual hD hC

variable (p) in
lemma exists_fg_sup_dual (s : Finset M) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p s = dual p s := by
  obtain ⟨S, hS⟩ := Submodule.exists_isCompl (dual p s).lineal
  use (dual p s) ⊓ S
  constructor
  · rw [dual_span_lineal_dual] at hS
    have h := CoFG.isCompl_fg hS (dual_finset_cofg p s)
    exact inf_fgdual_fg (fgdual_of_finset p s) (coe_fg h) -- h instead if coe_fg h would work
  · rw [← dual_span_lineal_dual]
    exact inf_sup_lineal hS.codisjoint

variable (p) in
lemma FG.exists_fg_sup_dual {C : PointedCone 𝕜 M} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p C = dual p C := by
  obtain ⟨s, rfl⟩ := hC
  simpa using PointedCone.exists_fg_sup_dual p s

lemma FGDual.exists_fg_sup_lineal {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ C.lineal = C := by
  obtain ⟨s, rfl⟩ := hC
  rw [dual_span_lineal_dual]
  exact PointedCone.exists_fg_sup_dual p s

/-- The sum of FGDual cones is FGDual. -/
lemma sup_fgdual {C D : PointedCone 𝕜 N} (hC : C.FGDual p) (hD : D.FGDual p) :
    (C ⊔ D).FGDual p := by
  obtain ⟨C', hCfg, hC'⟩ := hC.exists_fg_sup_lineal
  obtain ⟨D', hDfg, hD'⟩ := hD.exists_fg_sup_lineal
  rw [← hC', ← hD', sup_assoc]
  nth_rw 2 [sup_comm]
  rw [sup_assoc, ← sup_assoc]
  refine sup_fg_fgdual (sup_fg hCfg hDfg) ?_
  rw [← coe_sup, coe_fgdual_iff]
  exact Submodule.sup_fgdual hD.lineal_fgdual _

-- NOTE: Assumption `p.SeparatingLeft` cannot be avoided, see analogous proof for submodules. -/
variable (p) [Fact p.SeparatingLeft] in
lemma FG.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← FG.dual_flip_dual p hC, ← FG.dual_flip_dual p hD,
    ← Submodule.coe_inf, ← dual_sup_dual_inf_dual]
  exact FGDual.dual_dual_flip <| sup_fgdual (FG.dual_fgdual p hC) (FG.dual_fgdual p hD)

-- variable [Fact p.flip.IsFaithfulPair] in
-- lemma inf_fgdual_submodule {C : PointedCone 𝕜 N} {S : Submodule 𝕜 N}
--     (hC : C.FGDual p) (hS : S.FG) :
--     (C ⊓ S).FG := by
--   obtain ⟨D, hfg, hD⟩ := hC.exists_fg_sup_lineal
--   rw [← hD]
--   rw [← sup_inf_assoc_of_le_submodule]
--   refine sup_fg hfg ?_
--   rw [← coe_inf]
--   exact coe_fg (inf_fg_right _ hS)
--   --rw []
--   sorry

/- TODO: For submodules we have an alternative proof that avoids `p.Nondegenerate`.
  Can we have this here as well? -/
variable (p) [Fact p.Nondegenerate] in
lemma dual_fg_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.FGDual p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  obtain ⟨C', hC', rfl⟩ := FG.exists_fgdual_dual p.flip hC
  obtain ⟨D', hD', rfl⟩ := FGDual.exists_fg_dual hD
  rw [← Submodule.coe_inf]
  rw [← dual_sup_dual_inf_dual]
  rw [flip_flip] at hC'
  rw [FGDual.dual_dual_flip <| sup_fgdual_fg hC' hD']
  rw [FGDual.dual_dual_flip hC']
  rw [FG.dual_dual_flip p hD']

-- -- TODO: Should not need to rely on `p.flip.IsFaithfulPair`. Or maybe actually it should?
-- variable (p) [Fact p.IsFaithfulPair] [Fact p.flip.IsFaithfulPair] in
-- lemma dual_fg_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
--     (hD : D.FGDual p.flip) : dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
--   obtain ⟨C', hC', rfl⟩ := FG.exists_fgdual_dual p.flip hC
--   obtain ⟨D', hD', rfl⟩ := FGDual.exists_fg_dual hD
--   rw [← dual_sup_dual_inf_dual]
--   rw [flip_flip] at hC'
--   rw [FGDual.dual_dual_flip <| sup_fgdual_fg hC' hD']
--   rw [FGDual.dual_dual_flip hC']
--   rw [FG.dual_dual_flip p hD']

lemma dual_fg_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.FG) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

lemma dual_fgdual_inf_submodule_dual_sup_dual {C : PointedCone 𝕜 M} {S : Submodule 𝕜 M}
    (hC : C.FGDual p.flip) (hS : S.FG) :
      dual p (C ⊓ S : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p S) := by
  sorry

-- TODO: this should *not* rely on `p.flip.IsFaithfulPair`
-- variable (p)[Fact p.flip.IsFaithfulPair] in -- [Fact p.IsFaithfulPair]
-- lemma dual_inf_fgdual_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
--     dual p (C ⊓ D : PointedCone 𝕜 M) = (dual p C) ⊔ (dual p D) := by
--   simp
--   exact FG.dual_inf_dual_sup_dual p hC hD
--   -- obtain ⟨D', hfgdual, S, hfg, rfl⟩ := FG.exists_fgdual_inf_fg_submodule p.flip hD
--   -- rw [inf_comm, inf_assoc, inf_comm]
--   -- rw [dual_fg_inf_fgdual_dual_sup_dual _ (inf_fg (coe_fg hfg) hC) hfgdual]
--   -- rw [inf_comm]
--   -- rw [dual_fg_inf_submodule_dual_sup_dual hC hfg]
--   -- rw [sup_assoc]; nth_rw 2 [sup_comm]
--   -- rw [← dual_fgdual_inf_submodule_dual_sup_dual hfgdual hfg]

-- lemma foo (C : PointedCone 𝕜 M) (S : Submodule 𝕜 N) :
--   ∃ T : Submodule 𝕜 M, (dual p C).restrict S = dual (Dual.eval 𝕜 T) (C.restrict T) := by sorry

-- private lemma inf_submodule_fgdual (S : Submodule 𝕜 N) {C : PointedCone 𝕜 N} (hC : C.FGDual p) :
--     (C.restrict S).FGDual p := by
--   sorry


-- ----------------- ^^^^^^^ everything up there is proven vvvvv down there is work

-- lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog hCS : C ≤ S with h
--   · let S' : Submodule 𝕜 M := .span 𝕜 C
--     have hCS : C ≤ S' := le_submodule_span_self C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (.restrict S' C)
--       (restrict_fg_of_fg_le hCS hC)
--     sorry -- restrict_mono
--   · exact restrict_fg_of_fg_le hCS hC

-- lemma FG.restrict_fg2 (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) : (C.restrict S).FG := by
--   wlog _ : Module.Finite 𝕜 M with h
--   · let S' := Submodule.span 𝕜 (M := M) C
--     specialize @h 𝕜 S' _ _ _ _ _ (.restrict S' S) (restrict S' C) _ _
--     · exact restrict_fg_of_fg_le (le_submodule_span_self C) hC
--     · exact Finite.iff_fg.mpr (span_fg hC)
--     · have hfgS : (restrict S' S).FG := sorry
--       have hfgC : (restrict S' C).FG := sorry
--       sorry
--   · exact restrict_fg' S hC

lemma FGDual.exists_fg_sup_submodule {C : PointedCone 𝕜 N} (hC : C.FGDual p)
    {S : Submodule 𝕜 N} (hS : S.FGDual p) (hCS : S ≤ C) :
      ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ S = C := by
  sorry

lemma FGDual.is_dual_finite_inf_span''''' {C : PointedCone 𝕜 N} (hC : C.FG)
    (S : Submodule 𝕜 N) (hFG : S.FG) (hS : C ≤ S) : ∃ s : Set M, s.Finite ∧ dual p s ⊓ S = C := by
  sorry

lemma FGDual.is_dual_finite_inf_span'''' {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p s ⊓ Submodule.span (M := N) 𝕜 C = C := by
  sorry

lemma FG.dual_span_finite_sup_lineal (hC : C.FG) :
    ∃ s : Set N, s.Finite ∧ dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma FG.dual_span_finset_sup_lineal (hC : C.FG) :
    ∃ s : Finset N, dual p C = span 𝕜 s ⊔ (dual p C).lineal := by
  sorry

lemma FGDual.dual_sup_lineal (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ dual p C = D ⊔ (dual p C).lineal := by
  sorry

lemma FGDual.is_sup_fgdual_fg (hC : C.FGDual p.flip) :
    ∃ D : PointedCone 𝕜 M, D.FG ∧ D ⊔ C.lineal = C := by
  sorry

lemma FGDual.lineal_fgdual' (hC : C.FGDual p.flip) : C.lineal.FGDual p.flip := by
  sorry

lemma FG.is_dual_dual_of_finite (hC : C.FG) :
    ∃ s : Set M, s.Finite ∧ dual p.flip (dual p s) = C := by
  sorry

lemma FG.is_dual_dual_of_fgdual (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FGDual p ∧ dual p.flip D = C := by
  sorry

/- The following lemmas are proven because they have equivalents for general cones that do
  not hold without the FG assumption -/

-- @[simp] lemma dual_flip_dual_inter {C C' : PointedCone 𝕜 M} (hC : C.FG) (hC' : C'.FG) :
--     dual p.flip (dual p (C ∩ C')) = C ⊓ C' := by
--   rw [← dual_flip_dual (p := p) <| inf_fg hC hC']; simp

-- @[simp] lemma dual_dual_flip_inter {C C' : PointedCone 𝕜 N} (hC : C.FG) (hC' : C'.FG) :
--     dual p (dual p.flip (C ∩ C')) = C ⊓ C' := by
--   rw [← dual_dual_flip (p := p) <| inf_fg hC hC']; simp




-- ## FARKAS










end LinearOrder

end PointedCone
