/-
Copyright (c) 2026 Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Winter
-/
module

public import Mathlib.LinearAlgebra.AffineSpace.Dimension
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Data.Fintype.Card

/-!
# Finite-dimensional affine spaces

`AffineSpace.FiniteDimensional K P` expresses finite-dimensionality of an affine space `P`
over `K`. Its model vector space `V` is inferred from `[AddTorsor V P]`.
The definition abbreviates `FiniteDimensional K V`, so the two typeclass assumptions
are interchangeable and all of Mathlib's instances on model vector spaces apply directly.
In particular, vector spaces, products, and nonempty affine subspaces inherit finite dimension.
No conversion instances are needed in either direction.

`AffineSpace.dim K P` and `AffineSpace.finDim K P` are the dimensions of the model vector space.
An affine space is nonempty, so these do not need the bottom value used by
`AffineSubspace.dim` and `AffineSubspace.finDim`. As with `Module.finrank`, `finDim` has
the junk value zero in infinite dimension.

The predicate on affine subspaces is kept separately in
`AffineSpace/AffineSubspace/FiniteDimensional.lean`; that file provides explicit closure
lemmas and a comparison for a nonempty subspace viewed as an affine space.
-/

@[expose] public section

namespace AffineSpace

/-- An affine space is finite-dimensional when its model vector space is finite-dimensional. -/
abbrev FiniteDimensional (K P : Type*) {V : Type*} [DivisionRing K] [AddCommGroup V]
    [Module K V] [AddTorsor V P] : Prop :=
  _root_.FiniteDimensional K V

/-- The cardinal dimension of an affine space is the rank of its model vector space. -/
noncomputable def dim (K P : Type*) {V : Type*} [DivisionRing K] [AddCommGroup V]
    [Module K V] [AddTorsor V P] : Cardinal :=
  Module.rank K V

/-- The finite dimension of an affine space, with the junk value zero in infinite dimension. -/
noncomputable def finDim (K P : Type*) {V : Type*} [DivisionRing K] [AddCommGroup V]
    [Module K V] [AddTorsor V P] : ℕ :=
  Module.finrank K V

variable {K V P : Type*} [DivisionRing K] [AddCommGroup V] [Module K V] [AddTorsor V P]

theorem finiteDimensional_iff_model :
    FiniteDimensional K P ↔ _root_.FiniteDimensional K V := Iff.rfl

theorem dim_eq_rank : dim K P = Module.rank K V := rfl

theorem finDim_eq_finrank : finDim K P = Module.finrank K V := rfl

@[simp]
theorem dim_eq_zero_iff : dim K P = 0 ↔ Subsingleton P :=
  (rank_zero_iff (R := K) (M := V)).trans (AddTorsor.subsingleton_iff V P)

@[simp]
theorem dim_top : (⊤ : AffineSubspace K P).dim = (dim K P : WithBot Cardinal) :=
  by rw [AffineSubspace.dim_eq_rank (by simp), AffineSubspace.direction_top,
    _root_.rank_top]; rfl

@[simp]
theorem finDim_top : (⊤ : AffineSubspace K P).finDim = (finDim K P : WithBot ℕ) := by
  rw [AffineSubspace.finDim_eq_finrank (by simp), AffineSubspace.direction_top,
    _root_.finrank_top]
  rfl

theorem finiteDimensional_iff_dim_lt_aleph0 :
    FiniteDimensional K P ↔ dim K P < Cardinal.aleph0 :=
  Module.rank_lt_aleph0_iff.symm

theorem finDim_eq_zero_of_not_finiteDimensional (h : ¬FiniteDimensional K P) :
    finDim K P = 0 :=
  Module.finrank_of_not_finite h

namespace FiniteDimensional

variable [FiniteDimensional K P]

theorem dim_lt_aleph0 : dim K P < Cardinal.aleph0 := Module.rank_lt_aleph0 K V

theorem finDim_eq_dim : (finDim K P : Cardinal) = dim K P :=
  Module.finrank_eq_rank' K V

@[simp]
theorem finDim_eq_zero_iff : finDim K P = 0 ↔ Subsingleton P :=
  (Module.finrank_zero_iff (R := K) (M := V)).trans (AddTorsor.subsingleton_iff V P)

/-- A finite-dimensional affine space admits a finite affine basis. -/
theorem exists_affineBasis : Nonempty (AffineBasis (Fin (finDim K P + 1)) K P) :=
  AffineBasis.exists_affineBasis_of_finiteDimensional (Fintype.card_fin _)

/-- A finite-dimensional affine space is generated by finitely many points. -/
theorem exists_finset_affineSpan : ∃ S : Finset P, affineSpan K (S : Set P) = ⊤ := by
  classical
  obtain ⟨b⟩ := exists_affineBasis (K := K) (P := P)
  exact ⟨Finset.univ.image b, by simpa only [Finset.coe_image, Finset.coe_univ,
    Set.image_univ] using b.tot⟩

section Map

variable {W Q : Type*} [AddCommGroup W] [Module K W] [AddTorsor W Q]

omit [FiniteDimensional K P] in
/-- An affine space injecting into a finite-dimensional affine space is finite-dimensional. -/
theorem of_injective [FiniteDimensional K Q] (f : P →ᵃ[K] Q)
    (hf : Function.Injective f) : FiniteDimensional K P :=
  _root_.FiniteDimensional.of_injective f.linear (f.linear_injective_iff.mpr hf)

/-- A surjective affine image of a finite-dimensional affine space is finite-dimensional. -/
theorem of_surjective (f : P →ᵃ[K] Q) (hf : Function.Surjective f) :
    FiniteDimensional K Q :=
  _root_.FiniteDimensional.of_surjective f.linear (f.linear_surjective_iff.mpr hf)

/-- Finite-dimensionality is preserved by an affine equivalence. -/
theorem of_equiv (e : P ≃ᵃ[K] Q) : FiniteDimensional K Q :=
  e.linear.finiteDimensional

omit [FiniteDimensional K P] in
theorem finDim_le_of_injective [FiniteDimensional K Q] (f : P →ᵃ[K] Q)
    (hf : Function.Injective f) : finDim K P ≤ finDim K Q :=
  LinearMap.finrank_le_finrank_of_injective (f.linear_injective_iff.mpr hf)

theorem finDim_le_of_surjective (f : P →ᵃ[K] Q) (hf : Function.Surjective f) :
    finDim K Q ≤ finDim K P :=
  LinearMap.finrank_le_finrank_of_surjective (f.linear_surjective_iff.mpr hf)

end Map

end FiniteDimensional

/-- An affine space is finite-dimensional exactly when a finite set of points spans it. -/
theorem finiteDimensional_iff_exists_finset_affineSpan :
    FiniteDimensional K P ↔ ∃ S : Finset P, affineSpan K (S : Set P) = ⊤ := by
  constructor
  · intro h
    let := h
    exact FiniteDimensional.exists_finset_affineSpan
  · rintro ⟨S, hS⟩
    have h : _root_.FiniteDimensional K (affineSpan K (S : Set P)).direction :=
      finiteDimensional_direction_affineSpan_of_finite K S.finite_toSet
    rw [hS, AffineSubspace.direction_top] at h
    let := h
    exact Submodule.topEquiv.finiteDimensional

section Equiv

variable {W Q : Type*} [AddCommGroup W] [Module K W] [AddTorsor W Q]

theorem finiteDimensional_iff_of_equiv (e : P ≃ᵃ[K] Q) :
    FiniteDimensional K P ↔ FiniteDimensional K Q := by
  constructor
  · intro h
    let := h
    exact FiniteDimensional.of_equiv e
  · intro h
    let := h
    exact FiniteDimensional.of_equiv e.symm

theorem finDim_eq_of_equiv (e : P ≃ᵃ[K] Q) : finDim K P = finDim K Q :=
  e.linear.finrank_eq

end Equiv

end AffineSpace
