/-
Copyright (c) 2025 Justus Springer, Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Justus Springer, Martin Winter
-/
module

public import Polyhedral.Mathlib.Algebra.Module.Submodule.Dual.Field
public import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.DualFinite

/-! This file proves facts about the duals of finitely generated cones. In particular, it
establishes the *Minkowski-Weyl theorem* for cones. It states that duals of polyhedral cones are
polyhedral. We prove a number of results that amount to the same but work in infinite dimensional
space:
* duals of FG cones are DualFG (true by definition).
* duals of DualFG cones are FG.

If the ambient space is finite dimensional, then
* a cones is DualFG if and only if it is FG.
* duals of FG cones are FG if the ambient space is finite dim.

We also derive that intersections of FG cones are FG. This should however change in the future.

TODO: First prove that intersections of FG cones are FG, and use this fact to improve the
duality theory developed here. Some reasons:
* this fact holds more generally over `DivisionRing`, which needs to be a `Field` as soon as we
  work with duality.
* this fact also holds over rings like ℤ or certain modules over the tropical semifield. Perhaps
  a more unified theory can be provided.
-/

public section

open Function Module LinearMap
open Submodule hiding dual
open Set

variable {𝕜 M N : Type*}

namespace PointedCone

section LinearOrder

variable [Field 𝕜] [LinearOrder 𝕜] [IsOrderedRing 𝕜]
variable [AddCommGroup M] [Module 𝕜 M]
variable [AddCommGroup N] [Module 𝕜 N]

variable {p : M →ₗ[𝕜] N →ₗ[𝕜] 𝕜}
variable {C : PointedCone 𝕜 M} {s : Set M} {w : N}

/-- This states `(C ⊔ S*)* = C* ⊓ S` for a dual closed submodule `S`. -/
lemma dual_sup_submodule_dualClosed_eq_dual_inf_dual {S : Submodule 𝕜 N}
    (hS : S.DualClosed p.flip) : dual p (C ⊔ dual p.flip S : PointedCone 𝕜 M) = dual p C ⊓ S := by
  rw [dual_sup_dual_inf_dual]
  nth_rw 2 [← LinearMap.flip_flip p]
  nth_rw 3 [← coe_ofSubmodule]
  rw [DualClosed.coe_iff.mpr hS]

variable (p) [Fact p.SeparatingRight] in
/-- This states `(C ⊔ S*)* = C* ⊓ S` for an FG submodule `S`. -/
lemma dual_sup_submodule_fg_eq_dual_inf_dual {S : Submodule 𝕜 N} (hS : S.FG) :
    dual p (C ⊔ dual p.flip S : PointedCone 𝕜 M) = dual p C ⊓ S :=
  dual_sup_submodule_dualClosed_eq_dual_inf_dual <| hS.dualClosed _

-- # MINKOWSKI WEYL

variable (p s w) in
/-- A set whose dual cone is `span R {w} ⊔ dual p s`, see `dual_sup_span_singleton_eq_dual` -/
private noncomputable abbrev auxGenSet : Set M :=
  {x ∈ s | 0 ≤ p x w} ∪
    .image2 (fun x y ↦ p x w • y - p y w • x) {x ∈ s | 0 ≤ p x w} {y ∈ s | p y w < 0}

variable (w) in
omit [IsOrderedRing 𝕜] in
private lemma auxGenSet_finite (hs : s.Finite) :
    (auxGenSet p s w).Finite := .union (hs.sep _) <| .image2 _ (hs.sep _) (hs.sep _)

private lemma auxGenSet_subset_hull :
    (auxGenSet p s w : Set M) ⊆ hull 𝕜 (s : Set M) := by
  simp only [Set.union_subset_iff, Set.image2_subset_iff, Set.mem_ofPred_eq, and_imp]
  refine ⟨subset_trans (fun x hx ↦ hx.1) subset_hull, fun x hxS hxw y hyS hyw ↦ ?_⟩
  simpa [sub_eq_add_neg, ← neg_smul] using add_mem (smul_mem (hull 𝕜 s) hxw (subset_hull hyS))
    (smul_mem _ (neg_nonneg.mpr hyw.le) (subset_hull hxS))

private lemma hull_singleton_le_dual_auxGenSet :
    hull 𝕜 {w} ≤ dual p (auxGenSet p s w) := by
  simp only [span_singleton_le_iff_mem, mem_dual, mem_union, mem_ofPred_eq, mem_image2]
  rintro z (hz | ⟨x, ⟨hxS, hxw⟩, y, ⟨hyS, hyw⟩, rfl⟩)
  · exact hz.2
  · simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg]
    rw [mul_comm]

/-- The crucial lemma in the proof that a finitely generated cone is polyhedral:
The sum of a polyhedral cone and the cone generated by a single ray is again polyhedral. -/
private lemma dual_auxGenSet (hs : s.Finite) :
    dual p (auxGenSet p s w) = hull 𝕜 {w} ⊔ dual p s := by
  apply ge_antisymm
  · rw [← dual_hull]
    exact sup_le hull_singleton_le_dual_auxGenSet <| dual_le_dual auxGenSet_subset_hull
  obtain hSw | hSw := {y ∈ s | p y w < 0}.eq_empty_or_nonempty
  · simp only [Set.sep_eq_empty_iff_mem_false, not_lt] at hSw
    exact le_sup_of_le_right <| dual_le_dual fun x hx => .inl ⟨hx, hSw _ hx⟩
  rw [dual_union]
  intro v ⟨hv1, hv2⟩
  rw [Submodule.mem_sup]
  replace hv2 {x y : M} (hx : x ∈ s ∧ 0 ≤ p x w) (hy : y ∈ s ∧ p y w < 0) :
      p y w * p x v ≤ p y v * p x w := by
    simp only [SetLike.mem_coe, mem_dual, Set.mem_image2, Set.mem_ofPred_eq,
      forall_exists_index, and_imp] at hv2
    specialize hv2 x hx.1 hx.2 y hy.1 hy.2 rfl
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul,
      sub_nonneg] at hv2
    nth_rw 2 [mul_comm] at hv2
    exact hv2
  obtain hSv | ⟨y, hy⟩ := {y ∈ s | p y w < 0 ∧ p y v < 0}.eq_empty_or_nonempty
  · simp +contextual only [Set.sep_and, Set.eq_empty_iff_forall_notMem, Set.mem_inter_iff,
      Set.mem_ofPred_eq, not_and, true_and, not_lt, and_imp] at hSv
    refine ⟨0, zero_mem _, v, fun x hx => ?_, zero_add _⟩
    by_cases hxw : 0 ≤ p x w
    · exact hv1 ⟨hx, hxw⟩
    · exact hSv x hx (lt_of_not_ge hxw)
  lift s to Finset M using hs
  let u : 𝕜 := ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max' <| by
    simpa [Finset.Nonempty, Set.Nonempty] using hSw
  have hu : 0 ≤ u := by
    refine le_trans (mul_nonneg_of_nonpos_of_nonpos hy.2.2.le (inv_nonpos.mpr hy.2.1.le))
      (Finset.le_max' _ (p y v * (p y w)⁻¹) ?_)
    simp only [Finset.mem_image, Finset.mem_filter]
    exact ⟨y, ⟨hy.1, hy.2.1⟩, rfl⟩
  refine ⟨u • w, ?_, v - u • w, fun z hzS ↦ ?_, add_sub_cancel _ _⟩
  · rw [← Nonneg.mk_smul _ hu]
    exact Submodule.smul_mem _ _ (Submodule.subset_span rfl)
  simp only [map_sub, map_smul, smul_eq_mul, sub_nonneg]
  obtain hzw | hzw := lt_or_ge (p z w) 0
  · rw [← _root_.mul_le_mul_right_of_neg (inv_neg''.mpr hzw), mul_inv_cancel_right₀ hzw.ne]
    exact Finset.le_max' _ (p z v * (p z w)⁻¹) <|
      Finset.mem_image.mpr ⟨z, Finset.mem_filter.mpr ⟨hzS, hzw⟩, rfl⟩
  obtain ⟨y, hy, t_eq : _ = u⟩ := Finset.mem_image.mp <|
    ({y ∈ s | p y w < 0}.image (fun y => p y v * (p y w)⁻¹)).max'_mem <| by
      simpa [Finset.Nonempty, Set.Nonempty] using hSw
  rw [Finset.mem_filter] at hy
  rw [← t_eq, ← _root_.mul_le_mul_left_of_neg hy.2, ← mul_assoc]
  nth_rw 4 [mul_comm]
  rw [mul_inv_cancel_left₀ hy.2.ne]
  exact hv2 ⟨hzS, hzw⟩ hy

/-- The union of an FG cone and a DualFG cone is DualFG. -/
lemma sup_fg_dualfg {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.DualFG p) :
    (C ⊔ D).DualFG p := by classical
  obtain ⟨s, rfl⟩ := hC
  induction s using Finset.induction with
  | empty => simp [hD]
  | insert w s hws hs =>
    obtain ⟨t, ht⟩ := hs
    use (auxGenSet p t w).toFinset
    simp only [toFinset_union, SetLike.mem_coe, toFinset_image2, Finset.coe_union, coe_toFinset,
      Finset.coe_image₂, Finset.coe_insert, Submodule.span_insert, sup_assoc, ← ht]
    exact dual_auxGenSet t.finite_toSet

lemma sup_dualfg_fg {C D : PointedCone 𝕜 N} (hC : C.DualFG p) (hD : D.FG) : (C ⊔ D).DualFG p := by
  rw [sup_comm]
  exact sup_fg_dualfg hD hC

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of a DualFG cone and an FG submodule. -/
lemma FG.exists_dualfg_inf_submodule {C : PointedCone 𝕜 N} (hC : C.FG) {S : Submodule 𝕜 N}
    (hS : S.FG) (hCS : C ≤ S) : ∃ D : PointedCone 𝕜 N, D.DualFG p ∧ D ⊓ S = C := by
  wlog hC' : C = ⊥ with h
  · obtain ⟨D, hdualfg, hD⟩ := h p fg_bot hS bot_le rfl
    refine ⟨_, sup_fg_dualfg hC hdualfg, ?_⟩
    simp [sup_inf_assoc_of_le_submodule D hCS, hD]
  · obtain ⟨D, hdualfg, hD⟩ := hS.exists_dualfg_disjoint p -- <~~ submodule duality theory
    refine ⟨D, coe_dualfg_iff.mpr hdualfg, ?_⟩
    simp [← restrictScalars_inf, inf_comm, hC', hD.eq_bot]

variable (p) [Fact p.SeparatingRight] in
/-- An FG cone can be written as the intersection of its linear span with a DualFG cone. -/
lemma FG.exists_dualfg_inf_span {C : PointedCone 𝕜 N} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.DualFG p ∧ D ⊓ span 𝕜 (C : Set N) = C :=
  exists_dualfg_inf_submodule p hC (FG.span_fg hC) Submodule.subset_span

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_dual_flip {C : PointedCone 𝕜 N} (hC : C.FG) :
    dual p (dual p.flip C) = C := by
  obtain ⟨_, hD, hDC⟩ := exists_dualfg_inf_span p hC
  obtain ⟨C', _, rfl⟩ := hD.exists_fg_dual
  rw [← hDC, ← dual_sup_submodule_fg_eq_dual_inf_dual p hC.span, dual_dual_flip_dual]

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of an FG cone is the cone itself. -/
@[simp] lemma FG.dual_flip_dual {C : PointedCone 𝕜 M} (hC : C.FG) : dual p.flip (dual p C) = C :=
  FG.dual_dual_flip p.flip hC

variable (p) [Fact p.SeparatingLeft] in
lemma FG.dualClosed {C : PointedCone 𝕜 M} (hC : C.FG) : C.DualClosed p := FG.dual_flip_dual p hC

variable (p) [Fact p.SeparatingRight] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_dual_flip_eq_hull (s : Finset N) : dual p (dual p.flip s) = hull 𝕜 s := by
  nth_rw 2 [← dual_hull]
  exact dual_dual_flip p (fg_span s.finite_toSet)

-- NOTE: we keep this flipped version because it is a simp lemma.
variable (p) [Fact p.SeparatingLeft] in
/-- The double dual of a finite set is its span. -/
@[simp] lemma FG.dual_flip_dual_eq_hull (s : Finset M) : dual p.flip (dual p s) = hull 𝕜 s :=
    dual_dual_flip_eq_hull p.flip s

variable [Fact p.SeparatingLeft] in
lemma FG.dual_inj {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG)
    (h : dual p C = dual p D) : C = D := by
  have h := congrArg (dual p.flip) <| congrArg SetLike.coe h
  simpa [dual_flip_dual _ hC, dual_flip_dual _ hD] using h

variable [Fact p.SeparatingLeft] in
@[simp] lemma FG.dual_inj_iff {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p C = dual p D ↔ C = D := ⟨dual_inj hC hD, by simp +contextual⟩

/- NOTE: this is very likely true (a plausible argument was given by ChatGPT), but
a proof requires more machinery than currently available. -/
/-- The sup of an FG cone and a dual closed submodule is dual closed. -/
lemma DualClosed.fg_sup_submodule_dualClosed {C : PointedCone 𝕜 M} (hC : C.FG)
    {S : Submodule 𝕜 M} (hS : S.DualClosed p) : (C ⊔ S).DualClosed p := by
  have : Fact p.SeparatingLeft := sorry -- this assumption is not necessary, we remove it later.
  rw [← DualClosed.coe_iff] at hS
  rw [← hC.dualClosed p, ← hS]
  nth_rw 1 [← flip_flip p]
  rw [dual_inf_eq_sup_dual_iff_dualClosed (dual_dualClosed _ _) (dual_dualClosed _ _)]
  -- This now finishes with `(C ⊓ S)* = C* ⊔ S*` with `C` DualFG and `S` dual closed.
  sorry

variable [Fact p.SeparatingRight] in
/-- The dual of a DualFG cone is FG. -/
lemma DualFG.dual_fg {C : PointedCone 𝕜 M} (hC : C.DualFG p.flip) : (dual p C).FG := by
  obtain ⟨D, hfg, rfl⟩ := exists_fg_dual hC
  rw [FG.dual_dual_flip p hfg]
  exact hfg

/- Q: For submodules we have an alternative proof that avoids `p.SeparatingRight`. Can we
have this here as well? -/
variable [Fact p.SeparatingRight] in
/-- This states `(C ⊓ D)* = C* ⊔ D*` for `C` and `D` DualFG. -/
lemma DualFG.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M}
    (hC : C.DualFG p.flip) (hD : D.DualFG p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← DualFG.dual_flip_dual hC, ← DualFG.dual_flip_dual hD,
    ← Submodule.coe_inf, ← dual_sup_dual_inf_dual]
  exact FG.dual_dual_flip p <| sup_fg (DualFG.dual_fg hC) (DualFG.dual_fg hD)

section Module.Finite

variable [Module.Finite 𝕜 N]

/- TODO: implement instances lemmas that allow inference of `Module.Finite 𝕜 M` from assumptions
about `p`. We should preferably assume `Module.Finite 𝕜 N`. -/

variable (p) [Fact p.SeparatingRight] in
/-- A finite dimensional FG cone is also DualFG. -/
lemma FG.dualfg {C : PointedCone 𝕜 N} (hC : C.FG) : C.DualFG p := by
  obtain ⟨D, hdualfg, rfl⟩ := exists_dualfg_inf_submodule p hC Finite.fg_top (by simp)
  simpa using hdualfg

/-- A finite dimensional DualFG cone is also FG. -/
lemma DualFG.fg {C : PointedCone 𝕜 N} (hC : C.DualFG p) : C.FG := by
  obtain ⟨D, hfg, rfl⟩ := hC.id.exists_fg_dual
  exact DualFG.dual_fg <| FG.dualfg _ hfg

variable [Fact p.SeparatingRight] in
/-- A cone in finite dimensional space is FG if and only if it is DualFG. -/
lemma fg_iff_dualfg {C : PointedCone 𝕜 N} : C.FG ↔ C.DualFG p := ⟨FG.dualfg p, DualFG.fg⟩

variable (p) in
/-- In finite dimensional space, the dual of an FG cone is itself FG. -/
lemma FG.dual_fg {C : PointedCone 𝕜 M} (hC : C.FG) : (dual p C).FG := by
  rw [dual_id_map]
  exact DualFG.dual_fg <| FG.dualfg _ <| FG.map (LinearMap.restrictScalars _ p) hC

/-- In finite dimensional space, the dual of a DualFG cone is itself DualFG. -/
lemma DualFG.dual_dualfg {C : PointedCone 𝕜 N} (hC : C.DualFG p) : (dual p.flip C).DualFG p.flip
  := FG.dual_dualfg p.flip (DualFG.fg hC)

end Module.Finite

/- TODO: this also holds over `DivisionRing` and should therefore be proven without invoking
duality theory. It also holds over ℤ and in some tropical modules. -/
/-- The intersection of two FG cones is an FG cone. -/
lemma inf_fg {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) : (C ⊓ D).FG := by
  wlog _ : Module.Finite 𝕜 M with h
  · let CD : Submodule 𝕜 M := .span 𝕜 (C ⊔ D : PointedCone 𝕜 M)
    have hCle : C ≤ CD := le_trans le_sup_left Submodule.subset_span
    have hDle : D ≤ CD := le_trans le_sup_right Submodule.subset_span
    specialize h (restrict_fg_of_fg_le hCle hC) (restrict_fg_of_fg_le hDle hD)
      (Finite.iff_fg.mpr <| FG.span_fg <| sup_fg hC hD)
    rw [← restrict_inf] at h
    exact fg_of_restrict_le (le_trans inf_le_sup <| Submodule.subset_span) h
  · exact DualFG.fg <| (FG.dualfg .id hC).inf (FG.dualfg .id hD) -- inf_fg' hC hD

/- TODO: the ananlogue of the below statement with DualFG inplace of FG can likely be proven
under quite weak assumptions (Noetherian or so). -/

/-- The intersection of an FG cone with a submodule is FG. -/
lemma inf_fg_submodule {C : PointedCone 𝕜 M} (hC : C.FG) (S : Submodule 𝕜 M) : (C ⊓ S).FG := by
  rw [left_eq_inf.mpr (le_span (C := C)), inf_assoc, ← coe_inf]
  exact inf_fg hC <| FG.coe_fg <| FG.of_le (FG.span_fg hC) inf_le_left

/-- The intersection of a submodule with an FG is FG. -/
lemma inf_submodule_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
    (S ⊓ C : PointedCone 𝕜 M).FG := by rw [inf_comm]; exact inf_fg_submodule hC S

/-- The restriction of an FG cone to a submodule is FG. -/
lemma FG.restrict_fg (S : Submodule 𝕜 M) {C : PointedCone 𝕜 M} (hC : C.FG) :
    (C.restrict S).FG := by
  rw [restrict_fg_iff_inf_fg]; exact inf_submodule_fg S hC

/-- The intersection of an FG cone and a DualFG cone is FG. -/
lemma inf_fg_dualfg {C D : PointedCone 𝕜 N} (hC : C.FG) (hD : D.DualFG p) :
    (C ⊓ D).FG := by
  rw [← hC.dual_dual_flip .id]
  obtain ⟨_, hDfg, rfl⟩ := DualFG.exists_fg_dual hD.id
  rw [← dual_sup_dual_inf_dual]
  exact DualFG.dual_fg <| sup_dualfg_fg (FG.dual_dualfg _ hC) hDfg

/-- The intersection of a DualFG cone and an FG cone is FG. -/
lemma inf_dualfg_fg {C D : PointedCone 𝕜 N} (hC : C.DualFG p) (hD : D.FG) :
    (C ⊓ D).FG := by
  rw [inf_comm]; exact inf_fg_dualfg hD hC

variable (p) in
lemma exists_fg_sup_dual (s : Finset M) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p s = dual p s := by
  obtain ⟨S, hS⟩ := Submodule.exists_isCompl (dual p s).lineal
  use (dual p s) ⊓ S
  constructor
  · rw [dual_lineal_eq_submodule_dual] at hS
    have h := CoFG.fg_of_isCompl hS (dual_finset_cofg p s)
    exact inf_dualfg_fg (DualFG.dual_of_finset p s) (FG.coe_fg h) -- h instead if coe_fg h is workin
  · rw [← dual_lineal_eq_submodule_dual]
    exact inf_sup_lineal hS.codisjoint

variable (p) in
lemma FG.exists_fg_sup_dual {C : PointedCone 𝕜 M} (hC : C.FG) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ Submodule.dual (R := 𝕜) p C = dual p C := by
  obtain ⟨s, rfl⟩ := hC
  simpa using PointedCone.exists_fg_sup_dual p s

lemma DualFG.exists_fg_sup_lineal {C : PointedCone 𝕜 N} (hC : C.DualFG p) :
    ∃ D : PointedCone 𝕜 N, D.FG ∧ D ⊔ C.lineal = C := by
  obtain ⟨s, rfl⟩ := hC
  rw [dual_lineal_eq_submodule_dual]
  exact PointedCone.exists_fg_sup_dual p s

/-- The sum of DualFG cones is DualFG. -/
lemma sup_dualfg {C D : PointedCone 𝕜 N} (hC : C.DualFG p) (hD : D.DualFG p) :
    (C ⊔ D).DualFG p := by
  obtain ⟨C', hCfg, hC'⟩ := hC.exists_fg_sup_lineal
  obtain ⟨D', hDfg, hD'⟩ := hD.exists_fg_sup_lineal
  rw [← hC', ← hD', sup_assoc]
  nth_rw 2 [sup_comm]
  rw [sup_assoc, ← sup_assoc]
  refine sup_fg_dualfg (FG.sup hCfg hDfg) ?_
  rw [← coe_sup, coe_dualfg_iff]
  exact Submodule.sup_dualfg hD.lineal_dualfg _  -- <~~ submodule duality theory

-- NOTE: Assumption `p.SeparatingLeft` cannot be avoided, see analogous proof for submodules. -/
variable (p) [Fact p.SeparatingLeft] in
lemma FG.dual_inf_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG) (hD : D.FG) :
    dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  nth_rw 1 [← FG.dual_flip_dual p hC, ← FG.dual_flip_dual p hD,
    ← Submodule.coe_inf, ← dual_union, ← dual_sup]
  exact DualFG.dual_dual_flip <| sup_dualfg (FG.dual_dualfg p hC) (FG.dual_dualfg p hD)

/- Q: For submodules we have an alternative proof that avoids `p.Nondegenerate`.
Can we have this here as well? -/
variable (p) [Fact p.Nondegenerate] in
lemma dual_fg_inf_dualfg_dual_sup_dual {C D : PointedCone 𝕜 M} (hC : C.FG)
    (hD : D.DualFG p.flip) : dual p (C ∩ D) = (dual p C) ⊔ (dual p D) := by
  rw [← hC.dual_dual_flip p.flip]
  obtain ⟨D', hD', rfl⟩ := DualFG.exists_fg_dual hD
  rw [← Submodule.coe_inf]
  rw [← dual_sup_dual_inf_dual]
  have : DualFG p (dual p.flip.flip C) := FG.dual_dualfg p hC
  rw [DualFG.dual_dual_flip <| sup_dualfg_fg this hD']
  rw [DualFG.dual_dual_flip this]
  rw [FG.dual_dual_flip p hD']

end LinearOrder

end PointedCone
