
import Polyhedral.Polyhedral.Basic
import Polyhedral.Polyhedral.Faces2
import Polyhedral.Polyhedral.Exposed

namespace PointedCone


/- Wishlist:
 * all faces are polyhedral
 * all faces are exposed
 * there are only finitely many faces
 * salient => generated by its rays
 * duality flips the face lattice
 * face lattice is an abstract polytope
-/

-- ## IS FACE OF

section Ring

variable {R : Type*} [Ring R] [LinearOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {N : Type*} [AddCommGroup N] [Module R N]
variable {C C₁ C₂ F : PointedCone R M}

-- ...

end Ring

section Field

variable {R : Type*} [Field R] [LinearOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {N : Type*} [AddCommGroup N] [Module R N]
variable {C C₁ C₂ F : PointedCone R M}

lemma IsPolyhedral.face_exposed (hC : C.IsPolyhedral) (hF : F.IsFaceOf C) :
    F.IsExposedFaceOf C := by
  sorry

lemma IsPolyhedral.face (hC : C.IsPolyhedral) (hF : F.IsFaceOf C) : F.IsPolyhedral := by
  unfold IsPolyhedral salientQuot
  rw [hF.lineal_eq]
  sorry


-- ## KREIN MILMAN


end Field




-- ## FACE

section Ring

variable {R : Type*} [Ring R] [LinearOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {N : Type*} [AddCommGroup N] [Module R N]
variable {C C₁ C₂ F : PointedCone R M}

 -- ...

end Ring

section Field

variable {R : Type*} [Field R] [LinearOrder R] [IsOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {N : Type*} [AddCommGroup N] [Module R N]
variable {C C₁ C₂ F : PointedCone R M}


/- TODO:
 * face lattice is graded
 * all faces exposed
-/
instance {C : PolyhedralCone R M} :
    CoeOut (Face (C : PointedCone R M)) (PolyhedralCone R M) where
  coe F := ⟨F, C.isPolyhedral.face F.isFaceOf⟩

instance {C : PolyhedralCone R M} : Finite (Face (C : PointedCone R M)) := sorry

/-- Ideas:
  * `atoms` gives the lowest dimensional non-trivial faces
  * `rays` gives the rays and might be empty
  * a version of Krein-Milman with atoms
  * a version of Krein-Milman for rays if the cone is salient
-/

def atoms : Set (Face (C : PointedCone R M)) := sorry
def rays : Set (Face (C : PointedCone R M)) := sorry

def coatoms : Set (Face (C : PointedCone R M)) := sorry

-- lemma face_exposed (F : Face C) : F.IsExposed := sorry

end Field

end PointedCone
