/-
Copyright (c) 2025 Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Winter
-/
module

public import Polyhedral.Mathlib.Algebra.Module.Submodule.Dual.DualFinite

import Mathlib.LinearAlgebra.Dual.Defs
import Mathlib.LinearAlgebra.PerfectPairing.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.SesquilinearForm.Basic
import Mathlib.LinearAlgebra.Dual.Lemmas

/-! This file proves results about duality for finite dimensional subspaces.

Main declarations:
* `FG.dualClosed` and `FG.dual_flip_dual` state that a finitely generated submodule is dual
  closed as long as the pairing is separating.
* `DualFG.sup` state that the sup of any submodule with a DualFG submodule is DualFG.
* `DualFG.of_dualfg_le` a submodule that contains a DualFG submodule is itself DualFG.

This file also proves `(S ⊓ T)* = S* ⊔ T*` for when
* `S` is dual closed and `T` is DualFG
* `S` and `T` are DualFG
* `S` is FG and `T`is DualFG
* `S` and `T` are FG (`FG.dual_inf_dual_sup_dual`) assuming `p.SeparatingLeft`
* `S` is dual closed and `T` is FG (`FG.dual_inf_dual_sup_dual`)
-/

public section

open Function Module LinearMap
open Submodule hiding span dual

variable {R M N : Type*}

namespace Submodule

variable [Field R]
variable [AddCommGroup M] [Module R M]
variable [AddCommGroup N] [Module R N]

variable {p : M →ₗ[R] N →ₗ[R] R}
variable {S T : Submodule R M}

-- This is an alternative direct proof of `FG.dual_flip_dual` below.
variable (p) [Fact p.SeparatingLeft] in
@[simp] lemma FG.dual_flip_dual' (hS : S.FG) :
    dual p.flip (dual p S) = S := by
  have := Module.Finite.iff_fg.mpr (hS.map p)
  rw [dual_dualCoannihilator' p S, dual_dualAnnihilator' p.flip,
    Subspace.dualCoannihilator_dualAnnihilator_eq]
  exact comap_map_eq_self (by simp)

/- The main trick in the proof below (prior to golfing) was to define
  `T := { p s w • t - p t w • s | (s ∈ S) (t ∈ S) }`
This generating set appears on both sides of the identity:
  * `dual p T = dual p S ⊔ span R {w}`
  * `span R T = S ⊓ dual p.flip {w}`
-/
/-- This is a version of `(S ⊓ T)* = S* ⊔ T*` with `S` being dual closed and `T` a halfspace
generated by a single vector `w`. It states `(S ⊓ ⟨w⟩*)* = S* ⊔ ⟨w⟩** = S* ⊔ ⟨w⟩` without
using the middle expression.
-/
private lemma dual_inf_dual_singleton_dual_sup_singleton (hS : S.DualClosed p) (w : N) :
    dual p (S ∩ dual p.flip {w}) = dual p S ⊔ span R {w} := by
  by_cases hw : w ∈ dual p S
  · rw [← span_eq (dual p S), ← span_union, ← hS]
    simp [← coe_inf, ← dual_union, hw]
  simp only [mem_dual, SetLike.mem_coe, not_forall] at hw
  obtain ⟨s₀, hs₀, hw₀⟩ := hw
  push Not at hw₀
  ext x
  simp only [mem_dual, Set.mem_inter_iff, SetLike.mem_coe, Set.mem_singleton_iff, flip_apply,
    forall_eq, and_imp, mem_sup, mem_span_singleton, exists_exists_eq_and]
  constructor
  · intro hx
    let c := (p s₀ w)⁻¹ * p s₀ x
    refine ⟨x - c • w, ?_, c, sub_add_cancel _ _⟩
    intro s hs
    have h := hx (sub_mem (S.smul_mem (p s w) hs₀) (S.smul_mem (p s₀ w) hs)) (by simp [mul_comm])
    simp only [map_sub, map_smul, smul_eq_mul] at h ⊢
    rw [eq_comm, sub_eq_zero]
    have h' : p s₀ w * p s x = p s w * p s₀ x :=
      (sub_eq_zero.mp h.symm).symm
    calc p s x = (p s₀ w)⁻¹ * (p s₀ w * p s x) := by
                rw [← mul_assoc, inv_mul_cancel₀ hw₀.symm, one_mul]
             _ = (p s₀ w)⁻¹ * (p s w * p s₀ x) := by rw [h']
             _ = c * p s w := by dsimp [c]; ring
  · rintro ⟨y, hy, c, rfl⟩ s hs hsw
    simp [← hy hs, ← hsw]

/-- This is a version of `(S ⊓ T)* = S* ⊔ T*` with `S` being dual closed and `T` being DualFG.
More precisely, it states `(S ⊓ T*)* = S* ⊔ T** = S* ⊔ T`, where now `T` is FG, and
we avoiding proving the middle identities which would need dual closedness of FG submodules.
-/
lemma dual_inf_dual_finite_dual_sup_finite (hS : S.DualClosed p) (s : Finset N) :
    dual p (S ∩ dual p.flip s) = dual p S ⊔ span R s := by classical
  induction s using Finset.induction with
  | empty => simp
  | insert w s hws hs =>
    rw [Finset.coe_insert, span_insert, dual_insert, ← coe_inf]
    nth_rw 2 [sup_comm, inf_comm]
    rw [← sup_assoc, ← hs, ← inf_assoc]
    simpa using dual_inf_dual_singleton_dual_sup_singleton
      (inf_dualClosed hS <| dual_dualClosed p.flip s) w

/-- This is a version of `(S ⊓ T)* = S* ⊔ T*` with `S` being dual closed and `T` being DualFG.
More precisely, it states `(S ⊓ T*)* = S* ⊔ T** = S* ⊔ T`, where now `T` is FG, and
we avoiding proving the middle identities which would need dual closedness of FG submodules.
-/
lemma dual_inf_dual_fg_dual_sup_fg (hS : S.DualClosed p) {T : Submodule R N} (hT : T.FG) :
    dual p (S ∩ dual p.flip T) = dual p S ⊔ T := by
  obtain ⟨s, rfl⟩ := hT
  simpa using dual_inf_dual_finite_dual_sup_finite hS s

-- # DUAL CLOSED

lemma DualClosed.sup_span_finite (hS : S.DualClosed p) (s : Finset M) :
    (S ⊔ span R s).DualClosed p := by
  rw [← hS, ← dual_inf_dual_finite_dual_sup_finite (dual_dualClosed p _) s]
  exact dual_dualClosed _ _

lemma DualClosed.sup_span_singleton (hS : S.DualClosed p) (w : M) :
    (S ⊔ span R {w}).DualClosed p := by
  rw [← Finset.coe_singleton]
  exact hS.sup_span_finite {w}

lemma DualClosed.sup_fg (hS : S.DualClosed p) (hT : T.FG) :
    (S ⊔ T).DualClosed p := by
  obtain ⟨t, rfl⟩ := hT
  exact sup_span_finite hS t

variable (p) [Fact p.SeparatingLeft] in
lemma DualClosed.singleton (w : M) : (span R {w}).DualClosed p := by
  simpa using sup_span_finite dualClosed_bot {w}

variable (p) [Fact p.SeparatingLeft] in
lemma DualClosed.finite (s : Finset M) : (span R s).DualClosed p := by
  simpa using sup_span_finite dualClosed_bot s

variable [Fact p.SeparatingLeft] in
@[simp] lemma dual_flip_dual_finite (s : Finset M) : dual p.flip (dual p s) = span R s := by
  nth_rw 2 [← dual_span]
  exact DualClosed.finite p s

variable [Fact p.SeparatingRight] in
@[simp] lemma dual_dual_flip_finite (s : Finset N) : dual p (dual p.flip s) = span R s :=
    dual_flip_dual_finite _

variable (p) [Fact p.SeparatingLeft] in
/-- FG submodules are dual closed. -/
lemma FG.dualClosed (hS : S.FG) : S.DualClosed p := by
  simpa using DualClosed.sup_fg dualClosed_bot hS

variable (p) in
lemma FG.dualClosed_of_ker_le (hS : S.FG) (h : ker p ≤ S) : S.DualClosed p := by
  simpa [h] using DualClosed.sup_fg (p := p) dualClosed_ker hS

variable (p) [Fact p.SeparatingRight] in
lemma FG.dualClosed_flip {S : Submodule R N} (hS : S.FG) : S.DualClosed p.flip :=
  FG.dualClosed p.flip hS

variable (p) [Fact p.SeparatingLeft] in
@[simp] lemma FG.dual_flip_dual (hS : S.FG) : dual p.flip (dual p S) = S := by
  exact FG.dualClosed p hS

variable (p) [Fact p.SeparatingRight] in
@[simp] lemma FG.dual_dual_flip {S : Submodule R N} (hS : S.FG) : dual p (dual p.flip S) = S :=
    dual_flip_dual _ hS

variable (p) in
lemma FG.dual_flip_dual_sup_ker (hS : S.FG) : dual p.flip (dual p S) = S ⊔ ker p := by
  nth_rw 2 [← dual_union_ker, ← dual_span]
  simpa [sup_comm] using dualClosed_ker.sup_fg hS

variable (p) in
lemma FG.dual_dual_flip_sup_ker {S : Submodule R N} (hS : S.FG) :
    dual p (dual p.flip S) = S ⊔ ker p.flip := dual_flip_dual_sup_ker p.flip hS

variable (p) in
lemma FG.sup_ker_dualClosed (hS : S.FG) : (S ⊔ ker p).DualClosed p := by
  simpa [DualClosed, dual_sup, dual_union_ker] using dual_flip_dual_sup_ker p hS

variable [Fact p.SeparatingLeft] in
lemma DualFG.dual_fg {S : Submodule R N} (hS : S.DualFG p) : FG (dual p.flip S) := by
  obtain ⟨T, hfg, rfl⟩ := hS.exists_fg_dual
  simp [hfg]

lemma DualFG.dual_fg_sup_ker {S : Submodule R N} (hS : S.DualFG p) :
    ∃ T : Submodule R M, T.FG ∧ T ⊔ ker p = dual p.flip S := by
  obtain ⟨T, hfg, rfl⟩ := hS.exists_fg_dual
  use T
  simpa [hfg, Eq.comm] using hfg.dual_flip_dual_sup_ker p

/- There is a shorter proof of the theorem below that assumes `p.SeparatingRight`:
```
  obtain ⟨s, rfl⟩ := hT
  simpa only [dual_dual_flip_finite] using dual_inf_dual_finite_dual_sup_finite hS s
```
-/
/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` being dual closed and `T` being DualFG. -/
lemma dual_inf_dual_sup_dualfg (hS : S.DualClosed p) (hT : T.DualFG p.flip) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  obtain ⟨S', hfg, rfl⟩ := hT.exists_fg_dual
  rw [hfg.dual_dual_flip_sup_ker p]
  nth_rw 2 [sup_comm]
  rw [← sup_assoc]
  rw [sup_eq_left.mpr (dual_dualClosed p S).ker_le]
  exact dual_inf_dual_fg_dual_sup_fg hS hfg

/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` and `T` being DualFG. -/
lemma DualFG.dual_inf_dual_sup_dual (hS : S.DualFG p.flip) (hT : T.DualFG p.flip) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  exact dual_inf_dual_sup_dualfg hS.dualClosed hT

/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` being FG and `T` being DualFG. -/
lemma dual_fg_inf_dualfg_dual_sup_dual (hS : S.FG) (hT : T.DualFG p.flip) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  rw [← dual_union_ker, ← coe_inf, ← dual_sup, inf_comm]
  rw [inf_sup_assoc_of_le]
  · rw [inf_comm, coe_inf]
    rw [dual_inf_dual_sup_dualfg (hS.sup_ker_dualClosed p) hT]
    rw [dual_sup, dual_union_ker]
  exact hT.ker_le

/-- The sup of a DualFG submodule and an FG submodule is DualFG.

This is private because it is superseded by `DualFG.sup`. -/
private lemma sup_dualfg_fg {S T : Submodule R N} (hS : S.DualFG p) (hT : T.FG) :
    (S ⊔ T).DualFG p := by
  rw [← sup_eq_left.mpr (hS.ker_le),sup_assoc, sup_comm]
  nth_rw 2 [sup_comm]
  rw [← hS.dualClosed_flip, ← hT.sup_ker_dualClosed p.flip, LinearMap.flip_flip, sup_comm,
    ← dual_inf_dual_sup_dualfg]
  · rw [← coe_inf]
    obtain ⟨S', hfg, hS'⟩ := hS.dual_fg_sup_ker
    rw [← hS', inf_comm, ← inf_sup_assoc_of_le]
    · rw [dual_sup, dual_union_ker]
      exact dual_of_fg p (FG.of_le hfg inf_le_right)
    exact ker_le_dual_flip _
  · exact dual_dualClosed _ _
  · simpa [dual_sup, dual_union_ker] using dual_of_fg _ hT

/-- The sum of an DualFG submodule with an arbitrary submodule is DualFG. -/
lemma DualFG.sup {S : Submodule R N} (hS : S.DualFG p) (T : Submodule R N) :
    (S ⊔ T).DualFG p := by
  have h := CoFG.restrict (S ⊔ T) hS.cofg
  obtain ⟨U, hUST⟩ := exists_isCompl (restrict (S ⊔ T) S)
  have hU := h.fg_of_isCompl hUST
  have H := congrArg embed <| hUST.codisjoint.eq_top
  simp only [embed_sup, embed_restrict, embed_top] at H
  rw [← H]
  simpa using sup_dualfg_fg hS (embed_fg_of_fg hU)

alias sup_dualfg := DualFG.sup

/-- The sum of any submodule with a DualFG submodule is DualFG. -/
lemma dualfg_sup (S : Submodule R N) {T : Submodule R N} (hT : T.DualFG p) :
    (S ⊔ T).DualFG p := by
  rw [sup_comm]
  exact sup_dualfg hT S

/- NOTE: Proving this first (before `sup_dualfg`) might shorten total proof length. -/
/-- A submodule that contains an DualFG submodule is itself DualFG. -/
lemma DualFG.of_dualfg_le {S T : Submodule R N} (hS : S.DualFG p) (hST : S ≤ T) :
    T.DualFG p := by
  rw [← sup_eq_right.mpr hST]
  exact hS.sup T

/- NOTE: The assumption `SeparatingLeft` cannot be dropped. Consider submodules with `S ⊓ T = ⊥`,
but where `S ⊔ ker p = T ⊔ ker p = ⊤`. -/
variable [Fact p.SeparatingLeft] in
/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` and `T` being FG. -/
lemma FG.dual_inf_dual_sup_dual (hS : S.FG) (hT : T.FG) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  simp only [← Set.inf_eq_inter]
  rw [← dual_inf_eq_sup_dual_iff_dualClosed (hS.dualClosed p) (hT.dualClosed p)]
  refine DualFG.dualClosed <| DualFG.sup (hS.dual_dualfg p) _

/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` being FG and `T` being dual closed. -/
lemma FG.dual_inf_dual_dualClosed_sup_dual (hS : S.FG) (hT : T.DualClosed p) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  rw [← coe_inf, ← dual_union_ker, ← dual_sup]
  rw [sup_comm, ← sup_inf_assoc_of_le S hT.ker_le, sup_comm]
  have hclosed : (dual p (S ⊔ ker p : Submodule R M) ⊔ dual p T).DualClosed p.flip := by
    simpa only [dual_sup, dual_union_ker] using ((hS.dual_dualfg p).sup (dual p T)).dualClosed_flip
  simpa only [coe_inf, Set.inf_eq_inter, dual_sup, dual_union_ker] using
    dual_inf_dual_sup_dual_of_dualClosed (hS.sup_ker_dualClosed p) hT hclosed

alias DualClosed.dual_f_inf_dual_sup_dual := FG.dual_inf_dual_dualClosed_sup_dual

/-- This states `(S ⊓ T)* = S* ⊔ T*` for `S` being dual closed and `T` being FG. -/
lemma FG.dual_dualClosed_inf_dual_sup_dual (hS : S.DualClosed p) (hT : T.FG) :
    dual p (S ∩ T) = dual p S ⊔ dual p T := by
  rw [sup_comm, Set.inter_comm]
  exact hT.dual_inf_dual_dualClosed_sup_dual hS

alias DualClosed.dual_inf_dual_fg_sup_dual := FG.dual_dualClosed_inf_dual_sup_dual

-- # COFG

variable (p) [Fact p.SeparatingRight] in
lemma CoFG.dual_fg {S : Submodule R M} (hS : S.CoFG) : (dual p S).FG := by
  apply fg_of_fg_map_injective p.flip SeparatingRight.injective
  rw [S.dual_dualAnnihilator', map_comap_eq]
  exact FG.of_le hS.dualAnnihilator_fg inf_le_right

/- NOTE: from `CoFG S` does *not* follow `(S ⊔ ker p).DualClosed p `!
Consider `M = N` the space finitely supported sequences. Let S be the subspace of sequences
with `sum x_i = 0`. Then `S* = ⊥` and `S** = ⊤`. -/

variable (p) in
/-- The dual of a CoFG submodule can be written as the sum of an FG submodule with the kernel
of the flipped pairing. -/
lemma CoFG.exists_fg_sup_ker_eq_dual {S : Submodule R M} (hS : S.CoFG) :
    ∃ T : Submodule R N, T.FG ∧ T ⊔ ker p.flip = dual p S := by
  rw [dual_dualAnnihilator' p S]
  obtain ⟨T, hT, h⟩ :=
    FG.exists_fg_comap_eq_sup_ker (f := p.flip) hS.dualAnnihilator_fg
  exact ⟨T, hT, h.symm⟩

/-- A submodule is DualFG if and only if it is CoFG and dual closed. The forward direction
is provided by separate lemmas. This lemma provides the backwards direction. -/
theorem CoFG.dualfg_of_dualClosed {S : Submodule R N} (hS : S.CoFG) (hS' : S.DualClosed p.flip) :
    S.DualFG p := by
  obtain ⟨T, hfg, hT⟩ := hS.exists_fg_sup_ker_eq_dual p.flip
  rw [← hS', ← hT, dual_sup, dual_union_ker]
  exact hfg.dual_dualfg _

end Submodule
