/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: M Winter
-/
module

public import Mathlib.Data.Set.Finite.Basic
public import Mathlib.Data.Set.Lattice
public import Mathlib.Order.Hom.CompleteLattice

public import Polyhedral.Mathlib.GroupTheory.GroupAction.SubMulActionWithZero

/-!
# Closure and finiteness of `SubMulActionWithZero`

In this file we define the closure of a set as a `SubMulActionWithZero`, and define
finite generation for `SubMulActionWithZero`.
-/

@[expose] public section

namespace SubMulActionWithZero

variable {R M : Type*}

section SMul

/-- The `SubMulActionWithZero` generated by a set `s`.

This is the intersection of all `SubMulActionWithZero`s containing `s`. In particular,
the generated object always contains `0`, even if `0 ∉ s`. -/
def closure (R : Type*) {M : Type*} [Zero M] [SMul R M] (s : Set M) :
    SubMulActionWithZero R M :=
  sInf { p | s ⊆ (p : Set M) }

-- TODO: consider to use this definition, it has better definitional properties, but needs
--  stronger assumptions.
def closure' (R : Type*) [MonoidWithZero R] {M : Type*} [Zero M]
    [MulActionWithZero R M] (s : Set M) : SubMulActionWithZero R M where
  carrier := insert 0 {r • x | (x ∈ s) (r : R)}
  zero_mem' := by simp
  smul_mem' r x hx := by
    rcases hx with hx0 | ⟨x, hx, r', rfl⟩
    · simp [hx0]
    · right; exact ⟨x, hx, r * r', by rw [smul_smul]⟩

-- TODO: use definition with better definitional properties, such as
--   `{r • x | (r : R) (x ∈ s)}` or `Ici (0 : R) • s`

/- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
/-- Notation for the `SubMulActionWithZero` generated from a set `s`, short for
`SubMulActionWithZero.closure R s`. -/
scoped notation:70 R:70 " ∙ " s:70 => SubMulActionWithZero.closure R s

variable {R M : Type*} [Zero M] [SMul R M]
variable {s t : Set M} {x : M}

theorem mem_closure :
    x ∈ closure R s ↔ ∀ p : SubMulActionWithZero R M, s ⊆ p → x ∈ p := by
  simp [closure]

theorem subset_closure : s ⊆ closure R s := by
  intro x hx
  exact mem_closure.2 fun _ hp => hp hx

theorem mem_closure_of_mem (hx : x ∈ s) : x ∈ closure R s :=
  subset_closure hx

theorem smul_mem_closure_of_mem (hx : x ∈ s) (r : R) : r • x ∈ closure R s :=
  smul_mem _ r (subset_closure hx)

@[simp] theorem closure_eq (p : SubMulActionWithZero R M) :
    closure R p = p := by
  ext x
  constructor <;> intro h
  · rw [mem_closure] at h
    exact h p (subset_refl _)
  · exact mem_closure_of_mem h

@[simp]
theorem zero_mem_closure : (0 : M) ∈ closure R s :=
  (closure R s).zero_mem

theorem closure_le {p : SubMulActionWithZero R M} : closure R s ≤ p ↔ s ⊆ p := by
  constructor
  · intro h x hx
    exact h (subset_closure hx)
  · intro h x hx
    exact mem_closure.1 hx p h

@[gcongr]
theorem closure_mono (h : s ⊆ t) : closure R s ≤ closure R t := by
  rw [closure_le]
  exact h.trans (subset_closure (R := R) (s := t))

@[gcongr]
theorem closure_monotone : Monotone (closure R : Set M → SubMulActionWithZero R M) :=
  fun _ _ => closure_mono

variable (R) in
def closureOrderHom : Set M →o SubMulActionWithZero R M where
  toFun := closure R
  monotone' := closure_monotone

lemma closure_union (s t : Set M) : closure R (s ∪ t) = closure R s ⊔ closure R t := sorry

lemma closure_inter (s t : Set M) : closure R (s ∩ t) = closure R s ⊓ closure R t := sorry

variable (R) in
def closureLatticeHom : LatticeHom (Set M) (SubMulActionWithZero R M) where
  toFun := closure R
  map_sup' := closure_union
  map_inf' := closure_inter

/-- A `SubMulActionWithZero` is finitely generated if it is the closure of a finite set. -/
def FG (p : SubMulActionWithZero R M) : Prop :=
  ∃ (s : Set M), s.Finite ∧ p = closure R s

theorem fg_iff {p : SubMulActionWithZero R M} :
    p.FG ↔ ∃ (s : Finset M), p = closure R s :=
  Set.exists_finite_iff_finset

end SMul

section SMulWithZero

variable [Zero M] [SMulZeroClass R M]
variable {s t : Set M} {x : M}

lemma closure_sInf (s : Set (Set M)) : closure R (sInf s) = sInf (closure R '' s) := sorry

lemma closure_sSup (s : Set (Set M)) : closure R (sSup s) = sSup (closure R '' s) := sorry

variable (R) in
def closureCompleteLatticeHom : CompleteLatticeHom (Set M) (SubMulActionWithZero R M) where
  toFun := closure R
  map_sInf' := closure_sInf
  map_sSup' := closure_sSup

@[simp]
theorem closure_empty : closure R (∅ : Set M) = ⊥ := by
  ext x
  rw [mem_bot]
  constructor <;> intro h
  · rw [mem_closure] at h
    simpa using h ⊥
  · simp [h]

end SMulWithZero

section MulActionWithZero

variable [MonoidWithZero R] [Zero M] [MulActionWithZero R M]
variable {s t : Set M} {x : M}

theorem mem_closure_iff_exists_smul (hs : s.Nonempty) :
    x ∈ closure R s ↔ ∃ y ∈ s, ∃ r : R, r • y = x where
  mp := by
    intro h
    let p : SubMulActionWithZero R M := {
      carrier := insert 0 {r • x | (x ∈ s) (r : R)}
      zero_mem' := by simp
      smul_mem' r x hx := by
        rcases hx with hx0 | ⟨x, hx, r', rfl⟩
        · simp [hx0]
        · right; exact ⟨x, hx, r * r', by rw [smul_smul]⟩ }
    rw [mem_closure] at h
    have : s ⊆ p := by
      intro x hx
      simp only [mk_eq, Set.mem_insert_iff, Set.mem_setOf_eq, p]
      right; exact ⟨x, hx, 1, by simp⟩
    rcases h p this with h | h
    · simpa [h] using ⟨_, hs.choose_spec, 0, by simp⟩
    · exact h
  mpr := by
    rintro ⟨y, hy, r, rfl⟩
    exact smul_mem _ r (subset_closure hy)

theorem mem_closure_iff_exists_smul_of_not_zero (hx : x ≠ 0) :
    x ∈ closure R s ↔ ∃ y ∈ s, ∃ r : R, r • y = x := by
  by_cases h : s.Nonempty
  · exact mem_closure_iff_exists_smul h
  rw [Set.not_nonempty_iff_eq_empty] at h
  simp [h, hx]

-- This can become defeq if we change the definition of closure.
theorem mem_closure_iff_not_zero_exists_smul :
    x ∈ closure R s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, r • y = x where
  mp h := by
    by_cases hx0 : x = 0
    · left; exact hx0
    · right; exact (mem_closure_iff_exists_smul_of_not_zero hx0).mp h
  mpr h := by
    cases h with
    | inl h => simp [h]
    | inr h =>
      obtain ⟨y, hy, r , rfl⟩ := h
      exact smul_mem_closure_of_mem hy r

-- theorem mem_closure_iff_not_zero_exists_smul :
--     x ∈ closure R s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, r • y = x where
--   mp := by
--     intro h
--     let p : SubMulActionWithZero R M := {
--       carrier := insert 0 {r • x | (x ∈ s) (r : R)}
--       zero_mem' := by simp
--       smul_mem' r x hx := by
--         rcases hx with hx0 | ⟨x, hx, r', rfl⟩
--         · simp [hx0]
--         · right; exact ⟨x, hx, r * r', by rw [smul_smul]⟩ }
--     rw [mem_closure] at h
--     refine h p (fun x hx => ?_)
--     simp only [mk_eq, Set.mem_insert_iff, Set.mem_setOf_eq, p]
--     right; exact ⟨x, hx, 1, by simp⟩
--   mpr := by
--     rintro (hx0 | ⟨y, hy, r, rfl⟩)
--     · simp [hx0]
--     exact smul_mem _ r (subset_closure hy)

end MulActionWithZero

end SubMulActionWithZero
