/-
Copyright (c) 2026 Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Winter
-/

import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Lattice
import Mathlib.Order.Hom.CompleteLattice
import Mathlib.Order.Monotone.Defs

import Polyhedral.Mathlib.GroupTheory.GroupAction.SubMulActionWithZero

/-!
# Closure and finiteness of `SubMulActionWithZero`

In this file we define the closure of a set as a `SubMulActionWithZero`, and define
finite generation for `SubMulActionWithZero`.
-/

@[expose] public section

namespace SubMulActionWithZero

open Function Set

variable {R M : Type*}

section SMul

variable [Zero M] [SMul R M]
variable {s t : Set M} {x : M}

variable (R) in
/-- The `SubMulActionWithZero` generated by a set `s`.

This is the intersection of all `SubMulActionWithZero`s containing `s`. In particular,
the generated object always contains `0`, even if `0 ∉ s`. -/
def closure (s : Set M) : SubMulActionWithZero R M := sInf { p | s ⊆ (p : Set M) }

theorem mem_closure :
    x ∈ closure R s ↔ ∀ p : SubMulActionWithZero R M, s ⊆ p → x ∈ p := by
  simp [closure]

theorem subset_closure : s ⊆ closure R s :=
  fun _ hx => mem_closure.2 fun _ hp => hp hx

theorem smul_mem_closure_of_mem (r : R) (hx : x ∈ s) : r • x ∈ closure R s :=
  smul_mem _ r (subset_closure hx)

@[simp] theorem closure_eq (p : SubMulActionWithZero R M) :
    closure R p = p := by
  ext x
  constructor <;> intro h
  · rw [mem_closure] at h
    exact h p (subset_refl _)
  · exact subset_closure h

@[simp]
theorem zero_mem_closure : 0 ∈ closure R s :=
  (closure R s).zero_mem

theorem closure_le {p : SubMulActionWithZero R M} : closure R s ≤ p ↔ s ⊆ p := by
  constructor
  · intro h x hx
    exact h (subset_closure hx)
  · intro h x hx
    exact mem_closure.1 hx p h

@[gcongr]
theorem closure_mono (h : s ⊆ t) : closure R s ≤ closure R t := by
  rw [closure_le]
  exact h.trans subset_closure

@[gcongr]
theorem closure_monotone : Monotone (closure R : Set M → SubMulActionWithZero R M) :=
  fun _ _ => closure_mono

variable (R) in
def closureOrderHom : Set M →o SubMulActionWithZero R M where
  toFun := closure R
  monotone' := closure_monotone

lemma closure_sInf (s : Set (Set M)) : closure R (sInf s) ≤ sInf (closure R '' s) := by
  intro _ ht
  simpa using fun _ hx => closure_mono (sInf_le hx) ht

lemma closure_inter_le (s t : Set M) : closure R (s ∩ t) ≤ closure R s ⊓ closure R t :=
  fun _ ha => ⟨closure_mono inf_le_left ha, closure_mono inf_le_right ha⟩

/-- A `SubMulActionWithZero` is finitely generated if it is the closure of a finite set. -/
def FG (p : SubMulActionWithZero R M) : Prop :=
  ∃ (s : Set M), s.Finite ∧ p = closure R s

theorem fg_iff {p : SubMulActionWithZero R M} :
    p.FG ↔ ∃ (s : Finset M), p = closure R s :=
  Set.exists_finite_iff_finset

lemma closure_gc : GaloisConnection (closure R : Set M → SubMulActionWithZero R M) (↑) := by
  sorry

end SMul

section SMulWithZero

variable [Zero M] [SMulZeroClass R M]
variable {s t : Set M} {x : M}

lemma closure_union (s t : Set M) : closure R (s ∪ t) = closure R s ⊔ closure R t := by
  sorry

lemma closure_sSup (s : Set (Set M)) : closure R (sSup s) = sSup (closure R '' s) := by
  sorry

@[simp]
theorem closure_empty : closure R (∅ : Set M) = ⊥ := by
  ext x
  rw [mem_bot]
  constructor <;> intro h
  · rw [mem_closure] at h
    simpa using h ⊥
  · simp [h]

end SMulWithZero

section MulActionWithZero

variable [MonoidWithZero R] [Zero M] [MulActionWithZero R M]
variable {s t : Set M} {x : M}

/- # SMUL SET CLOSURE -/

variable (R) in
def smulSet (s : Set M) : SubMulActionWithZero R M where
  carrier := {x | x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y}
  zero_mem' := by simp
  smul_mem' r x hx := by
    rcases hx with hx0 | ⟨x, hx, r', rfl⟩
    · simp [hx0]
    · right; exact ⟨x, hx, r * r', by rw [smul_smul]⟩

/- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
/-- Notation for the `SubMulActionWithZero` generated from a set `s`, short for
`SubMulActionWithZero.smulSet R s`. -/
scoped notation:70 R:70 " ∙ " s:70 => SubMulActionWithZero.smulSet R s

theorem mem_smulSet :
    x ∈ R ∙ s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y := .rfl

theorem mem_smulSet_iff_exists_ne_zero (hx : x ∈ R ∙ s) :
    x = 0 ∨ ∃ y ∈ s, y ≠ 0 ∧ ∃ r : R, r ≠ 0 ∧ x = r • y := by
  rcases hx with (rfl | ⟨y, hy, r, rfl⟩)
  · exact .inl rfl
  · by_cases hy0 : y = 0
    · simp [hy0]
    by_cases hr0 : r = 0
    · simp [hr0]
    exact .inr ⟨y, hy, hy0, r, hr0, rfl⟩

theorem mem_smulSet_of_ne_zero (hx : x ≠ 0) :
    x ∈ R ∙ s ↔ ∃ y ∈ s, ∃ r : R, x = r • y where
  mp := by
    rintro (rfl | h)
    · contradiction
    · exact h
  mpr := .inr

theorem mem_smulSet_of_nonempty (hs : s.Nonempty) :
    x ∈ R ∙ s ↔ ∃ y ∈ s, ∃ r : R, x = r • y where
  mp := by
    rintro (rfl | h)
    · exact ⟨_, hs.choose_spec, 0, (zero_smul _ _).symm⟩
    · exact h
  mpr := .inr

theorem subset_smulSet : s ⊆ R ∙ s :=
  fun x hx => .inr ⟨x, hx, 1, (one_smul _ _).symm⟩

theorem mem_smulSet_of_mem (hx : x ∈ s) : x ∈ R ∙ s :=
  .inr ⟨x, hx, 1, (one_smul R x).symm⟩

theorem smul_mem_smulSet_of_mem (r : R) (hx : x ∈ s) : r • x ∈ R ∙ s :=
  .inr ⟨x, hx, r, rfl⟩

@[simp] theorem smulSet_eq (p : SubMulActionWithZero R M) :
    R ∙ p = p := by
  refine le_antisymm ?_ subset_smulSet
  rintro x (rfl | ⟨y, hy, r, rfl⟩)
  · exact zero_mem
  · exact p.smul_mem r hy

@[simp] theorem zero_mem_smulSet : 0 ∈ R ∙ s := .inl rfl

theorem smulSet_le {p : SubMulActionWithZero R M} : R ∙ s ≤ p ↔ s ⊆ p := by
  constructor
  · exact fun h _ hx => h (subset_smulSet hx)
  · intro h x hx
    rcases hx with (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem
    · exact p.smul_mem r (h hy)

@[gcongr]
theorem smulSet_mono (h : s ⊆ t) : R ∙ s ≤ R ∙ t := by
  rw [smulSet_le]
  exact h.trans subset_smulSet

@[gcongr]
theorem smulSet_monotone : Monotone (smulSet R : Set M → SubMulActionWithZero R M) :=
  fun _ _ => smulSet_mono

variable (R) in
def smulSetOrderHom : Set M →o SubMulActionWithZero R M where
  toFun := smulSet R
  monotone' := smulSet_monotone

@[simp]
theorem smulSet_empty : R ∙ (∅ : Set M) = ⊥ := by
  ext x
  rw [mem_bot]
  constructor <;> intro h
  · rcases h with (rfl | ⟨_, h, _, _⟩)
    · rfl
    · contradiction
  · simp [h]

lemma smulSet_inter_le (s t : Set M) : R ∙ (s ∩ t) ≤ R ∙ s ⊓ R ∙ t := by
  rintro x (rfl | ⟨y, hy, r, rfl⟩)
  · exact zero_mem
  · exact ⟨smul_mem _ r (subset_smulSet hy.1), smul_mem _ r (subset_smulSet hy.2)⟩

lemma smulSet_sInf_le (S : Set (Set M)) : R ∙ (sInf S) ≤ ⨅ s ∈ S, (R ∙ s) := by
  intro x
  simp only [iInf, SetLike.mem_sInf, mem_range, forall_exists_index, forall_apply_eq_imp_iff,
    exists_prop, and_imp]
  rintro (rfl | ⟨y, hy, r, rfl⟩) s hs
  · exact zero_mem
  · exact smul_mem _ r <| subset_smulSet (hy s hs)

lemma smulSet_sInf_le_sInf_image (S : Set (Set M)) : R ∙ (sInf S) ≤ sInf ((R ∙ ·) '' S) := by
  simpa using smulSet_sInf_le S

lemma smulSet_sInf_le_sInf_smulSet_image (S : Set (Set M)) :
    R ∙ (sInf S) ≤ sInf ((R ∙ ·) '' S) := by
  simpa using smulSet_sInf_le S

lemma smulSet_union (s t : Set M) : R ∙ (s ∪ t) = R ∙ s ⊔ R ∙ t := by
  apply le_antisymm
  · rintro x (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem
    · rcases hy with hy | hy
      · exact .inl <| Or.inr ⟨y, hy, r, rfl⟩
      · exact .inr <| Or.inr ⟨y, hy, r, rfl⟩
  · rw [sup_le_iff]
    constructor; all_goals
    · rintro x (rfl | ⟨y, hy, r, rfl⟩)
      · exact zero_mem
      · exact smul_mem _ _ (subset_smulSet <| by simp [hy])

lemma smulSet_sSup (S : Set (Set M)) : R ∙ (sSup S) = sSup ((R ∙ ·) '' S) := by
  apply le_antisymm
  · rintro x (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem
    · obtain ⟨t, htS, hyt⟩ := hy
      simpa using .inr ⟨t, htS, smul_mem_smulSet_of_mem r hyt⟩
  · rintro x (rfl | ⟨y, hy, h⟩)
    · exact zero_mem
    · obtain ⟨s, rfl⟩ := hy
      simp only [mem_image, iUnion_exists, mem_iUnion, SetLike.mem_coe, exists_prop,
        exists_and_right] at h
      obtain ⟨⟨s, hs, rfl⟩, (rfl | ⟨z, hz, r, rfl⟩)⟩ := h
      · exact zero_mem
      · exact smul_mem _ _ <| (le_trans (le_sSup hs) subset_smulSet) hz

lemma smulSet_sSup_eq_iSup_smulSet (S : Set (Set M)) : R ∙ (sSup S) = ⨆ s ∈ S, (R ∙ s) := by
  rw [← sSup_image]
  exact smulSet_sSup S

variable (R) in
theorem closure_eq_smulSet (s : Set M) : closure R s = R ∙ s := by
  ext x; constructor
  · have := closure_mono (R := R) <| subset_smulSet (R := R) (s := s)
    rw [closure_eq] at this
    exact fun hx => this hx
  · rintro (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem
    · exact smul_mem_closure_of_mem _ hy

theorem mem_closure_iff_not_zero_exists_smul :
    x ∈ closure R s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y :=
  SetLike.ext_iff.mp (closure_eq_smulSet R s) x

theorem mem_smulSet_iff_forall_mem_of_subset :
    x ∈ R ∙ s ↔ ∀ p : SubMulActionWithZero R M, s ⊆ p → x ∈ p := by
  rw [← closure_eq_smulSet, mem_closure]

end MulActionWithZero

section GroupWithZero

variable [GroupWithZero R] [Zero M] [MulActionWithZero R M]
variable {s t : Set M} {x : M}

lemma smulSet_smulSet_inter (s t : Set M) :
    R ∙ ((R ∙ s) ∩ t) = R ∙ s ⊓ R ∙ t := by
  apply le_antisymm
  · simpa only [smulSet_eq] using smulSet_inter_le (R := R) (R ∙ s) t
  rintro x ⟨hx, (rfl | ⟨y, hy, r, rfl⟩)⟩
  · exact zero_mem
  · by_cases hr0 : r = 0
    · simp [hr0]
    · exact .inr ⟨y, ⟨mem_of_smul_mem hr0 hx, hy⟩, ⟨r, rfl⟩⟩

lemma smulSet_inter_smulSet (s t : Set M) :
    R ∙ (s ∩ (R ∙ t)) = R ∙ s ⊓ R ∙ t := by
  rw [Set.inter_comm, inf_comm, smulSet_smulSet_inter]

lemma smulSet_inter_left (s : SubMulActionWithZero R M) (t : Set M) :
    R ∙ (s ∩ t) = s ⊓ R ∙ t := by
  rw [← smulSet_eq s]
  exact smulSet_smulSet_inter ..

lemma smulSet_inter_right (s : Set M) (t : SubMulActionWithZero R M) :
    R ∙ (s ∩ t) = R ∙ s ⊓ t := by
  rw [Set.inter_comm, inf_comm, smulSet_inter_left]

end GroupWithZero

end SubMulActionWithZero
