/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: M Winter
-/
module

public import Mathlib.Data.Set.Finite.Basic
public import Mathlib.Data.Set.Lattice
public import Mathlib.Order.Hom.CompleteLattice
public import Mathlib.Order.Monotone.Defs

public import Polyhedral.Mathlib.GroupTheory.GroupAction.SubMulActionWithZero

/-!
# Closure and finiteness of `SubMulActionWithZero`

In this file we define the closure of a set as a `SubMulActionWithZero`, and define
finite generation for `SubMulActionWithZero`.
-/

@[expose] public section

namespace SubMulActionWithZero

open Function Set

variable {R M : Type*}

section SMul

variable {R M : Type*} [Zero M] [SMul R M]
variable {s t : Set M} {x : M}

variable (R) in
/-- The `SubMulActionWithZero` generated by a set `s`.

This is the intersection of all `SubMulActionWithZero`s containing `s`. In particular,
the generated object always contains `0`, even if `0 ∉ s`. -/
def closure (s : Set M) : SubMulActionWithZero R M := sInf { p | s ⊆ (p : Set M) }

theorem mem_closure :
    x ∈ closure R s ↔ ∀ p : SubMulActionWithZero R M, s ⊆ p → x ∈ p := by
  simp [closure]

theorem subset_closure : s ⊆ closure R s :=
  fun _ hx => mem_closure.2 fun _ hp => hp hx

theorem smul_mem_closure_of_mem (r : R) (hx : x ∈ s) : r • x ∈ closure R s :=
  smul_mem _ r (subset_closure hx)

@[simp] theorem closure_eq (p : SubMulActionWithZero R M) :
    closure R p = p := by
  ext x
  constructor <;> intro h
  · rw [mem_closure] at h
    exact h p (subset_refl _)
  · exact subset_closure h

@[simp]
theorem zero_mem_closure : 0 ∈ closure R s :=
  (closure R s).zero_mem

theorem closure_le {p : SubMulActionWithZero R M} : closure R s ≤ p ↔ s ⊆ p := by
  constructor
  · intro h x hx
    exact h (subset_closure hx)
  · intro h x hx
    exact mem_closure.1 hx p h

@[gcongr]
theorem closure_mono (h : s ⊆ t) : closure R s ≤ closure R t := by
  rw [closure_le]
  exact h.trans subset_closure

@[gcongr]
theorem closure_monotone : Monotone (closure R : Set M → SubMulActionWithZero R M) :=
  fun _ _ => closure_mono

variable (R) in
def closureOrderHom : Set M →o SubMulActionWithZero R M where
  toFun := closure R
  monotone' := closure_monotone

lemma closure_sInf (s : Set (Set M)) : closure R (sInf s) ≤ sInf (closure R '' s) := by
  refine fun _ hx => hx _ fun _ hx => ?_
  simpa using fun S hS => subset_closure (hx S hS)

lemma closure_inter_le (s t : Set M) : closure R (s ∩ t) ≤ closure R s ⊓ closure R t :=
  fun _ hx => hx _ fun _ hx => ⟨subset_closure hx.1, subset_closure hx.2⟩

/-- A `SubMulActionWithZero` is finitely generated if it is the closure of a finite set. -/
def FG (p : SubMulActionWithZero R M) : Prop :=
  ∃ (s : Set M), s.Finite ∧ p = closure R s

theorem fg_iff {p : SubMulActionWithZero R M} :
    p.FG ↔ ∃ (s : Finset M), p = closure R s :=
  Set.exists_finite_iff_finset

lemma closure_gc :
    GaloisConnection (closure R : Set M → SubMulActionWithZero R M) (SetLike.coe) := by
  sorry

end SMul

section SMulWithZero

variable [Zero M] [SMulZeroClass R M]
variable {s t : Set M} {x : M}

lemma closure_union (s t : Set M) : closure R (s ∪ t) = closure R s ⊔ closure R t := by
  sorry

lemma closure_sSup (s : Set (Set M)) : closure R (sSup s) = sSup (closure R '' s) := by
  sorry

@[simp]
theorem closure_empty : closure R (∅ : Set M) = ⊥ := by
  ext x
  rw [mem_bot]
  constructor <;> intro h
  · rw [mem_closure] at h
    simpa using h ⊥
  · simp [h]

end SMulWithZero

section MulActionWithZero

variable [MonoidWithZero R] [Zero M] [MulActionWithZero R M]
variable {s t : Set M} {x : M}

/- # SMUL SET CLOSURE -/

variable (R) in
def smulSet (s : Set M) : SubMulActionWithZero R M where
  carrier := {x | x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y}
  zero_mem' := by simp
  smul_mem' r x hx := by
    rcases hx with hx0 | ⟨x, hx, r', rfl⟩
    · simp [hx0]
    · right; exact ⟨x, hx, r * r', by rw [smul_smul]⟩

/- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
/-- Notation for the `SubMulActionWithZero` generated from a set `s`, short for
`SubMulActionWithZero.smulSet R s`. -/
scoped notation:70 R:70 " ∙ " s:70 => SubMulActionWithZero.smulSet R s

theorem mem_smulSet :
    x ∈ R ∙ s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y := .rfl

theorem mem_smulSet_of_ne_zero (hx : x ≠ 0) :
    x ∈ R ∙ s ↔ ∃ y ∈ s, ∃ r : R, x = r • y where
  mp := by
    rintro (rfl | h)
    · contradiction
    · exact h
  mpr := .inr

theorem mem_smulSet_of_nonempty (hs : s.Nonempty) :
    x ∈ R ∙ s ↔ ∃ y ∈ s, ∃ r : R, x = r • y where
  mp := by
    rintro (rfl | h)
    · exact ⟨_, hs.choose_spec, 0, (zero_smul _ _).symm⟩
    · exact h
  mpr := .inr

theorem subset_smulSet : s ⊆ R ∙ s :=
  fun x hx => .inr ⟨x, hx, 1, (one_smul _ _).symm⟩

theorem smul_mem_smulSet_of_mem (r : R) (hx : x ∈ s) : r • x ∈ R ∙ s :=
  .inr ⟨x, hx, r, rfl⟩

@[simp] theorem smulSet_eq (p : SubMulActionWithZero R M) :
    R ∙ p = p := by
  refine le_antisymm ?_ subset_smulSet
  rintro x (rfl | ⟨y, hy, r, rfl⟩)
  · exact zero_mem _
  · exact p.smul_mem r hy

@[simp] theorem zero_mem_smulSet : 0 ∈ R ∙ s := .inl rfl

theorem smulSet_le {p : SubMulActionWithZero R M} : R ∙ s ≤ p ↔ s ⊆ p := by
  constructor
  · exact fun h _ hx => h (subset_smulSet hx)
  · intro h x hx
    rcases hx with (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem _
    · exact p.smul_mem r (h hy)

@[gcongr]
theorem smulSet_mono (h : s ⊆ t) : R ∙ s ≤ R ∙ t := by
  rw [smulSet_le]
  exact h.trans subset_smulSet

@[gcongr]
theorem smulSet_monotone : Monotone (smulSet R : Set M → SubMulActionWithZero R M) :=
  fun _ _ => smulSet_mono

variable (R) in
def smulSetOrderHom : Set M →o SubMulActionWithZero R M where
  toFun := smulSet R
  monotone' := smulSet_monotone

lemma smulSet_inter_le (s t : Set M) : R ∙ (s ∩ t) ≤ R ∙ s ⊓ R ∙ t := by
  intro x hx
  -- TODO
  sorry

lemma smulSet_inter_left (s : SubMulActionWithZero R M) (t : Set M) :
    R ∙ (s ∩ t) = R ∙ s ⊓ R ∙ t := by
  apply le_antisymm
  · exact smulSet_inter_le ..
  intro x hx
  -- TODO
  sorry

lemma smulSet_inter_right (s : Set M) (t : SubMulActionWithZero R M) :
    R ∙ (s ∩ t) = R ∙ s ⊓ R ∙ t := by
  rw [Set.inter_comm, inf_comm, smulSet_inter_left]

lemma smulSet_sInf (s : Set (Set M)) : R ∙ (sInf s) ≤ sInf ((R ∙ ·) '' s) :=
  sorry

lemma smulSet_union (s t : Set M) : R ∙ (s ∪ t) = R ∙ s ⊔ R ∙ t := by
  sorry

lemma smulSet_sSup (s : Set (Set M)) : R ∙ (sSup s) = sSup ((R ∙ ·) '' s) := by
  sorry

@[simp]
theorem smulSet_empty : R ∙ (∅ : Set M) = ⊥ := by
  ext x
  rw [mem_bot]
  constructor <;> intro h
  · rcases h with (rfl | ⟨_, h, _, _⟩)
    · rfl
    · contradiction
  · simp [h]

variable (R) in
theorem closure_eq_smulSet (s : Set M) : closure R s = R ∙ s := by
  ext x; constructor
  · exact fun h => h (R ∙ s) fun _ hx => subset_smulSet hx
  · rintro (rfl | ⟨y, hy, r, rfl⟩)
    · exact zero_mem _
    · exact smul_mem_closure_of_mem _ hy

theorem mem_closure_iff_not_zero_exists_smul :
    x ∈ closure R s ↔ x = 0 ∨ ∃ y ∈ s, ∃ r : R, x = r • y :=
  SetLike.ext_iff.mp (closure_eq_smulSet R s) x

theorem mem_smulSet_iff_forall_mem_of_subset :
    x ∈ R ∙ s ↔ ∀ p : SubMulActionWithZero R M, s ⊆ p → x ∈ p := by
  rw [← closure_eq_smulSet, mem_closure]

end MulActionWithZero

end SubMulActionWithZero
