/-
Copyright (c) 2026 Martin Winter. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Winter
-/

import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.VPolyhedral.Lattice
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Finite.Face.Basic

/-! This file proves basic facts about faces of polyhedral cones. -/

variable {R M M₁ M₂ N : Type*}

namespace PointedCone

open Module Function Pointwise OrderDual
open Submodule (span)

/- TODO:
 * all faces are polyhedral
 * all faces are exposed
 * there are only finitely many faces
 * salient => generated by its rays
 * duality flips the face lattice
 * face lattice is an abstract polytope
-/

/- NOTE: Many things proven in this file might be true more generally, e.g. for
  facially semi-exposed cones or so. This might include
    * all faces are exposed
    * face lattice of C and C* are anti-isomorphic
    * all faces are duals of faces
-/

-- # IS FACE OF

section Ring

variable [Ring R] [PartialOrder R] [IsOrderedRing R]
variable [AddCommGroup M] [Module R M]

variable {C F : PointedCone R M}

/-- Faces of FG cones are FG. -/
lemma IsFaceOf.isVPolyhedral (hC : C.IsVPolyhedral) (hF : F.IsFaceOf C) : F.IsVPolyhedral := by
  sorry

@[coe] def Face.toVPolyhedralCone {C : VPolyhedralCone R M} (F : Face (C : PointedCone R M)) :
    VPolyhedralCone R M :=
  ⟨F.toPointedCone, F.isFaceOf.isVPolyhedral C.isVPolyhedral⟩

instance {C : VPolyhedralCone R M} :
  CoeOut (Face (C : PointedCone R M)) (VPolyhedralCone R M) := ⟨Face.toVPolyhedralCone⟩

end Ring

section Field

variable [Field R] [LinearOrder R] [IsOrderedRing R]
variable [AddCommGroup M] [Module R M]

variable {C F : PointedCone R M}

/-- The face lattice of a polyhedral cone is isomorphic to the face lattice of an FG cone
in the same module. -/
lemma IsVPolyhedral.exists_fg_face_orderIso (hC : C.IsVPolyhedral) :
    ∃ D : PointedCone R M, D.FG ∧ Nonempty (Face C ≃o Face D) := by
  let ⟨S, hS⟩ := exists_isCompl C.lineal
  exact ⟨C ⊓ S, hC.fg_inf_of_isCompl hS, ⟨(Face.inf_isCompl_lineal_orderIso hS).symm⟩⟩

/-- A polyhedral cone has finitely many faces -/
lemma IsVPolyhedral.finite_face (hC : C.IsVPolyhedral) : Finite (Face C) := by
  let ⟨D, hfg, ⟨e⟩⟩ := hC.exists_fg_face_orderIso
  rw [Equiv.finite_iff e.toEquiv]
  exact FG.finite_face hfg

instance {C : VPolyhedralCone R M} : Finite (Face (C : PointedCone R M)) :=
  C.isVPolyhedral.finite_face

end Field

section Field

variable [Field R] [LinearOrder R] [IsOrderedRing R]
variable [AddCommGroup M] [Module R M]
variable [AddCommGroup N] [Module R N]

variable {C F : PointedCone R M}
variable {p : M →ₗ[R] N →ₗ[R] R}

-- # DUAL

lemma IsFaceOf.dualClosed_of_dualClosed_of_isVPolyhedral (hC : C.IsVPolyhedral)
    (hdc : C.DualClosed p) (hF : F.IsFaceOf C) : F.DualClosed p := by
  rw [hC.dualClosed_iff_lineal] at hdc
  rw [(hF.isVPolyhedral hC).dualClosed_iff_lineal]
  rw [PointedCone.IsFaceOf.lineal_congr hF]
  exact hdc

/-- Face duality on a dual closed polyhedral cone is involutive. -/
lemma IsVPolyhedral.face_dual_dual_flip_of_dualClosed (hC : C.IsVPolyhedral) (hdc : C.DualClosed p)
    (F : Face C) : (F.dual p).dual_flip p = F := by
  have hFfsr := F.isFaceOf.finSalRank hC.finSalRank
  have hFdc := F.isFaceOf.dualClosed_of_finSalRank p hdc hC.finSalRank
  have hsFdc := DualClosed.coe_iff.mpr <| DualClosed.span_dualClosed hFdc hFfsr
  rw [← Face.toPointedCone_eq_iff]
  rw [Face.coe_dual_flip, ← Face.coe_toPointedCone, Face.coe_dual]
  rw [← dual_lineal_eq_submodule_dual]
  rw [← dual_submodule_span]
  rw [Submodule.coe_inf]
  rw [dual_inf_dual_sup_dual_of_dualClosed (dual_dualClosed p C) ?_ ?_]
  · rw [hdc, ← dual_coe_coe_eq_dual_coe]
    iterate 2
      rw [coe_ofSubmodule]
      rw [dual_eq_submodule_dual]
    rw [show F = ((F : PointedCone R M) : Set M) from rfl]
    rw [DualClosed.span_dualClosed hFdc hFfsr]
    rw [IsFaceOf.sup_span_lineal_eq_span F.isFaceOf]
    exact F.isFaceOf.inf_span
  · rw [← coe_ofSubmodule]
    exact dual_dualClosed p _
  · nth_rw 4 [← coe_ofSubmodule]
    rw [hdc, ← Face.coe_toPointedCone, hsFdc]
    rw [dualClosed_iff_lineal _ (sup_submodule hC _)]
    rw [F.isFaceOf.sup_span_lineal_eq_span]
    rw [← DualClosed.coe_iff]
    exact hsFdc

variable (p) [Fact (Surjective p.flip)] in
/-- Face duality is on a polyhedral cone is involutive. -/
lemma IsVPolyhedral.face_dual_dual_flip (hC : C.IsVPolyhedral) (F : Face C) :
    (F.dual p).dual_flip p = F :=
  hC.face_dual_dual_flip_of_dualClosed (hC.dualClosed p) F

/-- Face duality on a dual closed polyhedral cone is involutive. -/
lemma IsVPolyhedral.face_dual_flip_dual_of_dualClosed (hC : C.IsVPolyhedral) (hdc : C.DualClosed p)
    (F : Face (.dual p C)) : (F.dual_flip p).dual p = F := by
  have h := (hC.dual p).face_dual_dual_flip_of_dualClosed (dual_dualClosed p C) F
  have hflip : (F.dual_flip p : Set M) = (F.dual p.flip : Set M) :=
    congrArg SetLike.coe (F.dual_flip_eq_dual_flip hdc)
  rw [← Face.toPointedCone_eq_iff] at h ⊢
  rw [Face.coe_dual_flip] at h
  rw [Face.coe_dual, hflip]
  simpa only [LinearMap.flip_flip] using h

/-- Face duality is antitone. -/
lemma IsVPolyhedral.face_dual_antitone_iff (hC : C.IsVPolyhedral) (hdc : C.DualClosed p)
    {F₁ F₂ : Face C} : F₁.dual p ≤ F₂.dual p ↔ F₂ ≤ F₁ where
  mpr h := Face.dual_antitone p h
  mp h := by
    rw [← hC.face_dual_dual_flip_of_dualClosed hdc F₁]
    rw [← hC.face_dual_dual_flip_of_dualClosed hdc F₂]
    exact Face.dual_flip_antitone p h

/-- Face duality is antitone. -/
lemma IsVPolyhedral.face_dual_flip_antitone_iff (hC : C.IsVPolyhedral) (hdc : C.DualClosed p)
    {F₁ F₂ : Face (.dual p C)} : F₁.dual_flip p ≤ F₂.dual_flip p ↔ F₂ ≤ F₁ where
  mp h := by
    rw [← hC.face_dual_flip_dual_of_dualClosed hdc F₂]
    rw [← hC.face_dual_flip_dual_of_dualClosed hdc F₁]
    exact Face.dual_antitone p h
  mpr h := Face.dual_flip_antitone p h

/-- For a polyhedral cone, the face lattice of the dual cone is anti-isomorphic to the face
lattice of the primal cone. -/
def IsVPolyhedral.dual_face_orderIso_of_dualClosed (hC : C.IsVPolyhedral) (hdc : C.DualClosed p) :
    Face (.dual p C) ≃o (Face C)ᵒᵈ where
  toFun := toDual ∘ .dual_flip p
  invFun := .dual p ∘ ofDual
  left_inv F := by simp [face_dual_flip_dual_of_dualClosed hC hdc]
  right_inv F := by simp [face_dual_dual_flip_of_dualClosed hC hdc]
  map_rel_iff' := by intro _ _; exact hC.face_dual_flip_antitone_iff hdc

variable (p) [Fact (Surjective p.flip)] in
/-- For a polyhedral cone, the face lattice of the dual cone is anti-isomorphic to the face
lattice of the primal cone. -/
def IsVPolyhedral.dual_face_orderIso (hC : C.IsVPolyhedral) :
    Face (.dual p C) ≃o (Face C)ᵒᵈ :=
  hC.dual_face_orderIso_of_dualClosed (hC.dualClosed p)

variable (p) in
/-- The dual of a face of an FG cone is an exposed face. -/
lemma Face.dual_isExposed_of_isVPolyhedral (hC : C.IsVPolyhedral) (F : Face C) :
    (F.dual p).IsExposed :=
  F.dual_isExposed_of_nonempty_relint p <|
    relint_nonempty_of_finSalRank (F.isFaceOf.isVPolyhedral hC).finSalRank

/-- Every face of a polyhedral cone is exposed. -/
lemma Face.isExposed_of_polyhedral (hC : C.IsVPolyhedral) (F : Face C) :
    F.IsExposed := by
  have h := hC.dualClosed (Dual.eval R M)
  rw [← hC.face_dual_dual_flip_of_dualClosed h F]
  rw [IsExposed, dual_flip_eq_dual_flip _ h]
  have hdual := Face.dual_isExposed_of_isVPolyhedral (Dual.eval R M).flip
    (hC.dual (Dual.eval R M)) (F.dual (Dual.eval R M))
  unfold Face.IsExposed IsExposedFaceOf at *
  simpa only [h] using hdual

/- NOTE: this proof currently relies on the unproven `DualClosed.face_dual_dual_flip_iff_isExposed`,
but could also be proven using `Face.isExposed_of_polyhedral` if necessary. -/
/-- Every face of a polyhedral cone is exposed. -/
lemma IsFaceOf.isExposed_of_polyhedral (hC : C.IsVPolyhedral) (hF : F.IsFaceOf C) :
    F.IsExposedFaceOf C := by
  let F' : Face C := ⟨F, hF⟩
  change F'.IsExposed
  rw [← Face.dual_dual_flip_iff_isExposed_of_dualClosed_of_finSalRank (Dual.eval R M)
    (hC.dualClosed _) hC.finSalRank]
  exact IsVPolyhedral.face_dual_dual_flip_of_dualClosed hC (hC.dualClosed _) _

end Field

end PointedCone
